### ISSUE TITLE
Smooth mouse movement

### ISSUE THREAD

**Issue by Lucashsmello** [Xian55/WowClassicGrindBot#106]
I'm intending to implement smoother mouse movement in order to make the bot less detectable. But, first i need opinion from other people. Is this really worth it? Does Blizzard takes weird mouse movements into account?

**Comment by Xian55** [comment]
Hey, sorry but i won't go into details about this topic here. Since it has no relation to the project, if you still interested you can get more info here. https://discord.gg/5qwedVa
