### ISSUE TITLE
Bag-Space does not update after selling

### ISSUE THREAD

**Issue by rafaelscheel** [Xian55/WowClassicGrindBot#113]
First of all, thanks so much for keeping this project running!
Let me know if I can help in any way.

I am stuck with a bug that is probably simple to fix. 
After Vendoring, the bag space in the BlazorServer UI does not update, thus the bag is still full and the char runs to the vendor over and over again... 

**To Reproduce**
1. Use Warlock_1.json configuration
2. Fill your bags
3. Macro on 'C' (example 'sell' function from documentation is not available in 'Test' macro): 
/target Adlin Pridedrift
4. Let bot run
5. All Items will be vendored, 

The button "initState" in the UI works, and there the item count in the bag works perfectly. 
Also the addon gathers the information correctly:
![image](https://user-images.githubusercontent.com/5481554/133907798-fcfba841-aab8-4b8e-89eb-10aee89985d6.png)

Let me know if any logs would be helpful. 
Thanks for any hint in the right direction.

**Comment by Xian55** [comment]
Hey thanks for reaching out. Thanks for the detailed report, with that in mind it was really easy to track down the issue. Nice one!

After the merge the issue should be solved. if you could report about it, i would really appreciate it: 🙇

**Comment by rafaelscheel** [comment]
<3 Wow thx for the fast fix =) Works like a charm!
