### ISSUE TITLE
can you explain what SetCursorPosition(Point p)  does?

### ISSUE THREAD

**Issue by alejo9010** [Xian55/WowClassicGrindBot#148]
i mean, what i understand it should set the mouse pos relative to the active window right? but the mouse seems off the coordinate.

**Comment by alejo9010** [comment]
for me, it seems the mouse is off from where it should move, i pick  apoint in the game window, and hard code a point to that point, and the mouse is way off the actual point

**Comment by Xian55** [comment]
If i recall correctly the simulator based mouse input is not used anywhere in the project currently. 

So you must be using some custom code on your machine. Please be sure that when you passing coordinates around in your code they are using the same coordinate system.
