### ISSUE TITLE
[.net core 3.1.413 (x64)] Bitmap.ctor() - ArgumentException: Paramater is not valid. 🤷 

### ISSUE THREAD

**Issue by hoooooolty** [Xian55/WowClassicGrindBot#154]
I used mage start the bot in Zangarmarsh,Sometimes the character dead can go back to the dead body, Sometimes the character in the graveyard locations the server had exception

![serverscreenshot](https://user-images.githubusercontent.com/3388250/138689914-3f74377b-2492-420d-8ca4-98f686dc0e45.png)

[out20211025_001.log](https://github.com/Xian55/WowClassicGrindBot/files/7409735/out20211025_001.log)

**Comment by Xian55** [comment]
Hey may i ask, have you experienced the 
> Bitmap.ctor() - ArgumentException: Paramater is not valid Exception
after we last talked about it ?
