### ISSUE TITLE
What can I do to contribute?

### ISSUE THREAD

**Issue by AsterNighT** [Xian55/WowClassicGrindBot#164]
I spent like 4 hours on the original repo and finally got it to work before I found your work! This is really amazing to see someone is doing the same things I did, and it seems you have done much more! I'm willing to contribute and got a few questions here.

1. Has this fork done anything about none-english clients? The original DataToColor won't work properly on my chinese client.
2. Is there a changelist or milestone I could find to get myself updated? I'm not sure what you have or haven't done thus feeling a bit awkward.

**Comment by Xian55** [comment]
Hey thanks for reaching out. First trying to answer your questions.

1. Actually yes, not so long ago made it possible to use the project with non english based clients. Tried to eliminate all the English client based stuffs. ex. replacing the spell names with texture id's. 

2. Actually i made a release not so long ago where i tried to summarize the very recently added features [1.1.35](https://github.com/Xian55/WowClassicGrindBot/releases/tag/1.1.35) and there's a little bit more change list in https://github.com/Xian55/WowClassicGrindBot/pull/149

On the other hand the original `DataToColor` has been heavily modified in the repo, made some performance related improvements and by reduced in-game addon and backend communication time significantly(from ~250ms to ~10-20ms). Now days the addon flush the state around the main display refresh rate. I've been experimenting and managed play with 120fps and the backend side mostly can keep up with, around 10-20ms.

The whole project is now capable of doing complete complex class rotations. you can find already one [Beast Master hunter](https://github.com/Xian55/WowClassicGrindBot/blob/main/Json/class/Hunter_62.json)

And thirdly spent lot of time extending the pathfinding. There's a third party repo which allows to generate path very quickly zone wide. [Remote V3](https://github.com/Xian55/AmeisenNavigation/tree/feature/guess-z-coord-after-rewrite)

**Comment by AsterNighT** [comment]
Thanks! I'll see what I can do.

**Comment by Xian55** [comment]
If you can and interested in joining [Discord](https://discord.gg/9ZAhfpA)
