### ISSUE TITLE
`frame_config.json` Configuration mismatch - Mana data changing wildly

### ISSUE THREAD

**Issue by jacobhamblin** [Xian55/WowClassicGrindBot#185]
### Description

Hello again! Thanks for the prompt response on my last bug submission.

I expected to drink after a fight per my class profile. Instead, the character never drinks, except for a millisecond randomly while walking around. I noticed that this matches the depiction of the goals from the Blazor UI, where the value for mana jumps around wildly.

### Addon Version

1.1.47

### World of Warcraft Client

Season of Mastery

### Reproduction Steps

1. Start the game
2. Enter world on mage
3. Start the bot
4. Load a profile
5. Watch for drinking, see it happen at unexpected times

### Last Good Version

1.1.42

### Screenshots

![mana_mayhem_smallerrrr](https://user-images.githubusercontent.com/7588474/144154638-bbf9ca28-2843-487a-80c6-2f2f372ff2a0.gif)

### Logs

[out20211130_001 - Copy.log](https://github.com/Xian55/WowClassicGrindBot/files/7629938/out20211130_001.-.Copy.log)

**Comment by Xian55** [comment]
:wave: Hello there.

**In short**
I've been encountered the same issue before. The saved `frame_config.json` data mismatches what the currently shown pixel cells. Most likely the coordinates doesn't match and for example now one of the cells bleeding into an another one cells location.

The easiest way to solve this kind of issue is to repeat the [5. Configuration process](https://github.com/Xian55/WowClassicGrindBot#5-configuration-process) from the `Frame Configuration`.

**Detailed**
I do not know what cause the issue exactly. I assume something regarding how the ui rendering has been done while considering the following variables:
- Game window resolution changes
- wow UI scale changing
- pixel rounding errors

While doing `Frame Configuration` process, currently only the ~46th(Race + Class) cell is being used as validation. Might be worth to do more sanity checks. 🤔

**Comment by jacobhamblin** [comment]
Thank you! I'll double check the resolution and scaling and report back a little later.

**Comment by jacobhamblin** [comment]
Repeating the config process fixed the issue for me. Thanks again :pray:
