### ISSUE TITLE
Retail Works?

### ISSUE THREAD

**Issue by underyimo** [Xian55/WowClassicGrindBot#186]
can i use that on retail?

**Comment by Xian55** [comment]
:wave: Hello there

The project current goal is to support `Burning Crusade Classic` and `SoM`. Retail is not in the scope at the moment.

At the current state, some of the core features just won't work properly, due lack of [data](https://github.com/Xian55/WowClassicGrindBot/tree/dev/Json) (client data and navigation data).

The client data(dbc) could be solved using the [Utility extractor project](https://github.com/Xian55/WowClassicGrindBot/tree/dev/Utilities/ReadDBC_CSV).

Navigation data is more challenging, there are no MPQ files, so the V1 pathfinding not gonna work at all. V3 could work based on what expansion TrinityCore supports.
