### ISSUE TITLE
[Druid] Travel Form does not count for IsMounted

### ISSUE THREAD

**Issue by TheGuyWhoBots** [Xian55/WowClassicGrindBot#189]
Hi,

Working great! i'm just wondering how i'd go about making sure when "Follow Route Goal" is active to turn into Travel Form as Druid, i tried implementing it myself but it kept changing back to no form then back to travel form. Also, do you have a discord group?

Thanks & Kind Regards

**Comment by Xian55** [comment]
Hey thanks for making contact! 

> "Follow Route Goal" is active to turn into Travel Form as Druid ... but it kept changing back to no form then back to travel form

This one is an issue yes. Started working on it, however as the PTR is down need some time to test it. Fix coming in few days.

> Also, do you have a discord group?

As of yet date, there are not public discord available. 

Until then, gooday!

**Comment by Xian55** [comment]
After #191. Should be able to make it work without any hassle.

There are only one requirement. You must include `Travel Form` `KeyAction` in the class profile file. like
https://github.com/Xian55/WowClassicGrindBot/blob/fafdfa18d020a6dc13549a282898d1e8236f12b3/Json/class/Druid_30_cat_bear.json#L28

**Comment by Xian55** [comment]
Better way #192
