### ISSUE TITLE
Feature Request: Change default Movement keys

### ISSUE THREAD

**Issue by nofearr** [Xian55/WowClassicGrindBot#202]
hi, im struggled on character moving, i dont know why, pls tell me what am doing wrong. Thanks
![move](https://user-images.githubusercontent.com/96659345/147388709-3cb9f735-37c6-4afc-a802-f33f9fa4d919.jpg)

**Comment by Xian55** [comment]
Hello please upload the **full log** file.

**Comment by nofearr** [comment]
Thanks for respond. I just forgot to run PathingAPI. Now everything works. One question, can i edit default keybinds? For examaple. I want moving on keyarrows not on WASDE? is it possible?

**Comment by Xian55** [comment]
Hello there 👋 !

Im glad you found out the issue of yours. 

> can i edit default keybinds? 

Yes it is possible to alter _many_ key bindings in the `ClassConfiguration` file.

> For examaple. I want moving on keyarrows not on WASDE? is it possible?

By default the player movement is done via the arrow keys. As of yet date it is not possible to change the key bindings of the movement keys.

**Comment by Xian55** [comment]
After #203 should be able to change the default movement keys. (arrows) to any ConsoleKey.

Look at the example how to change to `WASD`
https://github.com/Xian55/WowClassicGrindBot/blob/62d05e7c5c687f007122a5b0a6adb114fd6360e4/Json/class/Warrior_1_MovementKeys.json#L4
