### ISSUE TITLE
Stuck on NPC Goal

### ISSUE THREAD

**Issue by TalkingBaboon** [Xian55/WowClassicGrindBot#220]
### Description

Hello I'm a bit stuck. The bot won't move towards the vendor in the gnome starting zone. I have double checked everything is setup. I can see it's stuck on the sell goal. It will turn and face the direction of the NPC but won't target the NPC. It just freezes and jiggles a bit to the left and right. 

As far as I can tell it's working until it gets to that point although the pathing might not be correct. I can't tell if the combat is working just because it can see the mobs, and it's not actually moving on it's own to the waypoints properly. I don't know much C#. 

### Addon Version

1.1.42

### World of Warcraft Client

Season of Mastery

### Reproduction Steps

Followed the steps in the readme and made sure everything was setup the way it needed to be. It built without any errors.
I started a new profile and selected warrior, made sure the path profile were loaded and started the bot until it reached the npc vendor goal. 

### Logs

[out20220108.log](https://github.com/Xian55/WowClassicGrindBot/files/7833263/out20220108.log)

Last error in log file was:

[13:09:46:937 ERR] PerformAction on AdhocNPCGoal
System.NullReferenceException: Object reference not set to an instance of an object.
   at WowTriangles.ChunkedTriangleCollection.FindStandableAt1(Single x, Single y, Single min_z, Single max_z, Single& z0, Int32& flags, Single toonHeight, Single toonSize, Boolean IgnoreGradient, Int32[] allowedFlags) in C:\WowClassicGrindBot\PathingAPI\PPather\Triangles\ChunkedTriangleCollection.cs:line 842
   at PathingAPI.Search.GetZValueAt(Single x, Single y, Int32[] allowedModels) in C:\WowClassicGrindBot\PathingAPI\Search\Search.cs:line 61
   at PathingAPI.Search.CreateLocation(Single x, Single y) in C:\WowClassicGrindBot\PathingAPI\Search\Search.cs:line 44
   at PathingAPI.PPatherService.GetWorldLocation(Int32 uiMapId, Single v1, Single v2) in C:\WowClassicGrindBot\PathingAPI\Search\PPatherService.cs:line 88
   at BlazorServer.LocalPathingApi.FindRoute(Int32 map, Vector3 fromPoint, Vector3 toPoint) in C:\WowClassicGrindBot\BlazorServer\PathingApi\LocalPathingApi.cs:line 64
   at Core.Goals.AdhocNPCGoal.FillRouteToDestination() in C:\WowClassicGrindBot\Core\Goals\AdhocNPCGoal.cs:line 295
   at Core.Goals.AdhocNPCGoal.PerformAction() in C:\WowClassicGrindBot\Core\Goals\AdhocNPCGoal.cs:line 117
   at Core.Goals.GoalThread.GoapPerformGoal() in C:\WowClassicGrindBot\Core\Goals\GoalThread.cs:line 114
[13:09:46:945 INF] Input: KeyDown UpArrow SetKeyState-StopForward - Cancel interact
[13:09:46:968 INF] Input: KeyUp UpArrow
[13:09:47:015 INF] Stopped!

**Comment by Xian55** [comment]
Hello there 👋 

Review the logs the mentioned issue. It seems the Frame configuration process were not successful or the game client top left part of the screen is blocked by other application. Because the log says

> 2022-01-08 11:01:09.776 +00:00 [DBG] Woohoo, I have read the player class. You are a None None.

Instead of the `none none` should see the player Race and Class respectively.

Try to repeat the [Frame Configuration](https://github.com/Xian55/WowClassicGrindBot#5-configuration-process) process you might have to do it multiple times. After it says its `Successful` and restarts, you can validate by checking few values. like

* In the Route component you can check player coordinate and compare it to the in-game one you may need an addon to see that. or you can type the following in chat [Checking coordinates without addons](https://wowpedia.fandom.com/wiki/Map_coordinates)
```lua
/run z = C_Map.GetBestMapForUnit("player"); pos = C_Map.GetPlayerMapPosition(z,"player"); print(C_Map.GetMapInfo(z).name, math.ceil(pos.x*10000)/100, math.ceil(pos.y*10000)/100)
```
with the browser
![image](https://user-images.githubusercontent.com/367101/148646370-92e284dd-6099-46fd-8499-210289b403dc.png)

* By looking at the `Player` component in the browser and targeting someone you see the health% name and npcid.
![image](https://user-images.githubusercontent.com/367101/148646406-124d5496-c7db-49e6-9bba-ff95f2fbc46b.png)

**Comment by TalkingBaboon** [comment]
Hey thanks for replying. Followed the steps above and used an addon to read map coords to confirm it's updating correctly and it is. It reads the class and tells me Gnome warrior but still gets stuck on the NPC goal. Log is attached. 

###Logs
[out20220110.txt](https://github.com/Xian55/WowClassicGrindBot/files/7834572/out20220110.txt)

**Comment by Xian55** [comment]
can you prove an image of the frontend, from the browser, during you experience the issue?

**Comment by TalkingBaboon** [comment]
Yes. Which part did you want to look at?
![Untitled](https://user-images.githubusercontent.com/88790664/148677374-79fd329d-5730-4041-aaf3-db1f675dcb9a.png)

**Comment by Xian55** [comment]
Mainly the `Goals` component and what color of the badges do they have. However make sure to include the `Player` component as well.

**Comment by TalkingBaboon** [comment]
![Untitled](https://user-images.githubusercontent.com/88790664/148677433-f9358fd3-1df0-44c9-b6eb-443c6da7bd3c.png)

**Comment by Xian55** [comment]
Alright so the `BagFull` is green which means the backend thinks your inventory is full.

**Comment by TalkingBaboon** [comment]
![2022-01-09 09_54_53-Window](https://user-images.githubusercontent.com/88790664/148677481-a885fe3d-4658-41f4-898d-a67635ecfc84.png)

**Comment by Xian55** [comment]
Can you do the following sequence
1. Press the `Stop bot` button. 
1. Press the `Init State` button.

Then report back what happens with the `BagFull` badge.

**Comment by Xian55** [comment]
Hang on it seems there's an issue at my end. Sorry! Possible fix coming in really soon.

**Comment by Xian55** [comment]
Can you pull from the `dev` branch and check with the included fix? https://github.com/Xian55/WowClassicGrindBot/pull/221

**Comment by TalkingBaboon** [comment]
It's working so far but it gave me this when I started the server:

C:\WowClassicGrindBot\PathingAPI\PPather\Triangles\ChunkedTriangleCollection.cs(20,22): warning CS0649: Field 'ChunkedTriangleCollection.UseOctree' is never assigned to, and will always have its default value false [C:\WowClassicGrindBot\PathingAPI\PathingAPI.csproj]
C:\WowClassicGrindBot\PathingAPI\PPather\Triangles\WmoFile.cs(218,17): warning CA1806: Load creates a new instance of WmoGroupFile which is never used. Pass the instance as an argument to another method, assign the instance to a variable, or remove the object creation if it is unnecessary. [C:\WowClassicGrindBot\PathingAPI\PathingAPI.csproj]

Thanks for your help though I've let it run for 10 minutes and no other issues?

**Comment by TalkingBaboon** [comment]
I see now the green lines on the map, where it's actually finding the waypoint as long as the bot is in the correct zone. That wasn't happening before.

**Comment by Xian55** [comment]
```
C:\WowClassicGrindBot\PathingAPI\PPather\Triangles\ChunkedTriangleCollection.cs(20,22): warning CS0649: Field 'ChunkedTriangleCollection.UseOctree' is never assigned to, and will always have its default value false [C:\WowClassicGrindBot\PathingAPI\PathingAPI.csproj]
C:\WowClassicGrindBot\PathingAPI\PPather\Triangles\WmoFile.cs(218,17): warning CA1806: Load creates a new instance of WmoGroupFile which is never used. Pass the instance as an argument to another method, assign the instance to a variable, or remove the object creation if it is unnecessary. [C:\WowClassicGrindBot\PathingAPI\PathingAPI.csproj]
```

Don't bother with these. These are just warnings. They wont do any harm.

**Comment by TalkingBaboon** [comment]
Just let me read a few books on C# and I'll come back and help you. Thanks again!

**Comment by Xian55** [comment]
The backend is written in c# for sure. However there is the frontend which mix if blazor and pure html and css with bootstrap, contribution to those also appreciated! 👋

**Comment by TalkingBaboon** [comment]
Is there a discord?

**Comment by Xian55** [comment]
Only for the devs currently.
