### ISSUE TITLE
Question: Indoor pathing

### ISSUE THREAD

**Issue by MojoOli** [Xian55/WowClassicGrindBot#265]
I have a question, so you stated "Indoors pathfinding only works properly if PathFilename is exists." in your readme. Do you mean buildings or dungeons by that? Because as far as I know, you cannot read the x,y,z coordinates inside dungeons (without memory reading) which basically makes it really hard to navigate the bot. But then I also so your project with AmeisenNavigation where u basically did all that. I am really interested in your thought process on how you handled all that.

If you have time, I would really like to get in touch with u because I am programming a bot based on your HappyPixel adjustments in Kotlin. I didn't know how I could get in touch with you outside of making an issue.

**Comment by Xian55** [comment]
Hello there!

> I have a question, so you stated "Indoors pathfinding only works properly if PathFilename is exists." in your readme. Do you mean buildings or dungeons by that?

*"Indoors"* means, outdoor zones where you have a sealing above your head, such as underground, caves, buildings. As you said correctly the related minimap API only yields valid result while outside of instances and raids, those feature have been disabled long ago.
