### ISSUE TITLE
[RemoteV1] Stuck at `Startup` while discovering available pathing services.

### ISSUE THREAD

**Issue by JuanMaestro** [Xian55/WowClassicGrindBot#266]
### Description

Stuck on this message after doing FrameConfiguration

RemotePathingAPIV3 PingServer 2014ms False

The webpage just never loads.

### Addon Version

1.2.4

### World of Warcraft Client

The Burning Crusade Classic

### Reproduction Steps

Just followed the guide and it happened after doing frameconfig.
Running in vmware

### Logs

2022-03-02 21:23:35.671 +01:00 [DBG] Startup()
2022-03-02 21:23:38.043 +01:00 [INF] RemotePathingAPIV3 PingServer 2043ms False

**Comment by JuanMaestro** [comment]
Just started working.. I don't even know why

**Comment by JuanMaestro** [comment]
It happened again, I use local pathing tho

**Comment by Xian55** [comment]
Hello there!

Without any details, its impossible to give support.

 Please describe your situation in more verbose. 

First and foremost **upload the whole log file** what you have. Next to the executable you can find them.

**Comment by JuanMaestro** [comment]
The log doesn't show more than this
2022-03-03 15:58:20.106 +01:00 [DBG] Startup()
2022-03-03 15:58:31.241 +01:00 [INF] RemotePathingAPIV3 PingServer 2048ms False

Only one time yesterday it just went past it, no idea how that happened.

I haven't done anything related to the remotepathing as it seemed a bit too complicated for me.

Just did the initial setup with the frameconfig and then it "reboots"

Some more info:
[15:58:20:106 DBG] Startup()
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://0.0.0.0:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\WowClassicGrindBot\BlazorServer
[15:58:31:241 INF] RemotePathingAPIV3 PingServer 2048ms False

**Comment by Xian55** [comment]
Do you have any other application running which actively uses port **5001** and/or **47111** ?

**Comment by Xian55** [comment]
What kind of operation system are you running the virtual machine?

**Comment by Xian55** [comment]
Which branch and what commit did you checked out?

**Comment by JuanMaestro** [comment]
I using windows 10 on a clean install. Nothing else but WoW and the bot.
Using the dev branch.

On host and VM i'm not using port 5001 or 47111. Checked with netstat

**Comment by Xian55** [comment]
Does the game window top left corner appear visible on your screen and not obstructed by any other application?

**Comment by JuanMaestro** [comment]
It visible and nothing obstructs it. I even made it a tiny bit larger with the cell size - tried both cell size 2 and 3

**Comment by Xian55** [comment]
Are you starting `BlazorServer` with admin privileges ?
Are you running  World of Warcraft client with admin privileges ?

**Comment by JuanMaestro** [comment]
I've run the .bat file with admin and wow with admin.
Doesn't change anything.
Should I try on a different Win version? or maybe deploy another VM and start fresh?

**Comment by Xian55** [comment]
> I've run the .bat file with admin and wow with admin.

Do **not** run either the `.bat` and the `wow client` with admin privileges. Since the BlazorServer wont have access to specific input, over the wow client!

> Should I try on a different Win version?

No.


Can you do a proper windows 10 restart inside the virtual machine. Like not shutting down via vmware gui, but **start menu -> Power -> Restart**

**Comment by JuanMaestro** [comment]
Tried restarting normally, did sadly not help.
Thanks for the help so far! Very kind of you.

**Comment by Xian55** [comment]
For further support please click here:

**Comment by Xian55** [comment]
Thanks for giving insight about the situation, the issue was on my side! 🙇
