### ISSUE TITLE
unable to read player class

### ISSUE THREAD

**Issue by amirh-esmz** [Xian55/WowClassicGrindBot#291]
Hi 
when i want to do frame configuration , this error show's up
"unable to read player class"

also there are some errors with addon
like "attempt to call global 'UnitCharacterPoints' (a nil value)" => quera.lua:503
like "attempt to call global 'GetNumTalentTabs' (a nil value)" => ${title}.lua:394

I installed wow with battle net
thank you for your good work

**Comment by Xian55** [comment]
Hello there!

I would like to ask you to create a new issue following this [template](https://github.com/Xian55/WowClassicGrindBot/issues/new?assignees=&labels=bug&template=bug_report.yml)

**Comment by Xian55** [comment]
Does the issue have been resolved ?

**Comment by amirh-esmz** [comment]
yes , i have installed wrong game client
