### ISSUE TITLE
[HeadlessServer] Dotnet build failure due missing `*_config.json`

### ISSUE THREAD

**Issue by adamssullivan** [Xian55/WowClassicGrindBot#328]
### Description

When I am following the setup instructions for the dev branch I am getting an error "C:\Program Files\dotnet\sdk\6.0.302\Microsoft.Common.CurrentVersion.targets(5097,5): error MSB3030: Could not copy the
file "C:\Funforme\HeadlessServer\data_config.json" because it was not found. [C:\Funforme\HeadlessServer\HeadlessServer
.csproj]
C:\Program Files\dotnet\sdk\6.0.302\Microsoft.Common.CurrentVersion.targets(5097,5): error MSB3030: Could not copy the
file "C:\Funforme\HeadlessServer\frame_config.json" because it was not found. [C:\Funforme\HeadlessServer\HeadlessServe
r.csproj]
C:\Program Files\dotnet\sdk\6.0.302\Microsoft.Common.CurrentVersion.targets(5097,5): error MSB3030: Could not copy the
file "C:\Funforme\HeadlessServer\addon_config.json" because it was not found. [C:\Funforme\HeadlessServer\HeadlessServe
r.csproj]
    0 Warning(s)
    3 Error(s)"

I am using version sdk 6.0.302 and 6.0.100

### Addon Version

I have not gotten this far in the instructions

### World of Warcraft Client

The Burning Crusade Classic

### Reproduction Steps

1. Open PowerShell (x86)
2. CD to location of files
3. Type dotnet build --configuration Release  (Version of dotnet SDK 6.0.302 and 6.0.100)
4. Build fails with 3 errors listed above

### Screenshots

![image](https://user-images.githubusercontent.com/3653097/178650770-2f982a53-1281-4575-98ae-5d2869bbd704.png)

**Comment by Xian55** [comment]
Hello there, thanks for brining this to my attention!

Regarding the issue, it was my short sight, and laziness to copy the related `*_config.json` files to the project folder by hand. 

https://github.com/Xian55/WowClassicGrindBot/pull/329 should fix the issue and requires some documentation, how to setup 
 properly. Going to update the readme and make a wiki about it, soon.

Have a nice day! 👋

**Comment by Xian55** [comment]
Update: https://github.com/Xian55/WowClassicGrindBot/pull/330 Added an example `run.bat` and documentation how to run `HeadlessServer` please look at the documentation near
https://github.com/Xian55/WowClassicGrindBot#5-blazorserver-configuration-process
and 
https://github.com/Xian55/WowClassicGrindBot#7-optional---running-headlessserver


Let me know if you have any further questions.
