### ISSUE TITLE
[Request] Assist focus mode target the NPC the focus target is targeting

### ISSUE THREAD

**Issue by adamssullivan** [Xian55/WowClassicGrindBot#333]
**Is your feature request related to a problem? Please describe.**
When the focus target targets an NPC the assist focus bot does not target the NPC

**Describe the solution you'd like**
I would like while in assist focus mode to target the NPC that the focus target is targeting

**Describe alternatives you've considered**
I have set up auto-sharing and auto-accepting quest add-ons. I don't see a way to turn in without actually clicking on the NPC at least once

**Additional context**
Just need an option to have the bot change targets to an NPC if they are being selected by the focus target.

**Comment by Xian55** [comment]
Hello there, thanks for reaching out!

As of today, the `AssistFocus` mode, the bot only switches the focused unit's target when its hostile. The initial goal was to help killing the focus target npc.
https://github.com/Xian55/WowClassicGrindBot/blob/68b0863b686a31b869190ea36ac08fba06631e91/Core/Goals/TargetFocusTargetGoal.cs#L21

I will look into it, how i can expand to fit the requirement. 👍

**Comment by adamssullivan** [comment]
Thanks for looking into it. Appreciate the work done on this.

**Comment by Xian55** [comment]
Hey, 

I've pushed a new branch called `feature/assist-focus-friendly` which has a new behavior added to the `AsssitFocus` Mode.

Full description here: https://github.com/Xian55/WowClassicGrindBot/pull/335/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R1257

If you have the time to checkout and validate, it would be great! 🤝 

**Note**: You have to be sure that using Addon version `1.4.1`. 
* After pulling the branch create a build and start `BlazorServer` project. 
* There going to be a prompt at the index page to `New addon version available` 
* Press `Update`
* Press `Install & Save` then you should see in the chat Addon Version `1.4.1`.

At this point you can try out the new `AsssitFocus` Mode behavior.

-----

Incase you want to revert back to the `dev` branch. 
* checkout `dev` branch
* create a `BlazorServer` build and start
* navigate to the `Addon Config` side tab.
* Press `Install & Save` then you should see in the chat Addon Version `1.4.0` as of current standing.

**Comment by Xian55** [comment]
Addon version bumped to `1.4.2`

**Comment by Xian55** [comment]
Addon version bumped to `1.4.3`

**Comment by Xian55** [comment]
#335 merged to `dev` and thus closed the issue. 

Let me know if you encounter any troubles. 🙇
