### ISSUE TITLE
Judgement of Wisdom - Unknown Requirement

### ISSUE THREAD

**Issue by adamssullivan** [Xian55/WowClassicGrindBot#336]
### Description

When I added to look for Judgment of Wisdom buff it says unknown requirement. 
![image](https://user-images.githubusercontent.com/3653097/179360913-f04fa009-6056-493d-ac1e-78e1fc11b1a9.png)
I was able to use the same setup for Judgement of the Crusader.

### Addon Version

1.3.5

### World of Warcraft Client

The Burning Crusade Classic

### Reproduction Steps

1. Add a requirement for Judgment of Wisdom.
2. Unknown requirement error is displayed.

### Screenshots

![image](https://user-images.githubusercontent.com/3653097/179361219-79b057e4-f920-453c-9184-9a613984d33c.png)

### Logs

[out20220716.log](https://github.com/Xian55/WowClassicGrindBot/files/9126109/out20220716.log)

**Comment by adamssullivan** [comment]
Thank you! I am going to test the other feature you added today. I will report back in the other comment.

**Comment by Xian55** [comment]
Hey, just make sure to double check the Addon version when you attempt to try out the new features! 🙇
