### ISSUE TITLE
Support for herb skinnable creatures

### ISSUE THREAD

**Issue by AsterNighT** [Xian55/WowClassicGrindBot#338]
**Is your feature request related to a problem? Please describe.**
There are certain creatures in the game that can be gathered as herb when killed. It is similar to skinning but now there seems no support for it yet. There are creatures that can be mined too.

**Describe the solution you'd like**
Now the bot check the local area database to see if the creature id is in a `skinnable` list. The datas seem to be loaded from `Json/area/<mapid>.json`. There could be a new `gatherable` or `minable` list for each area and copy & paste the skinning logic for herbalism and mining.

**Describe alternatives you've considered**
Now I simply disable the code that checks if the mob is in the skinnable list. That works but slightly slows down the looting of a non-skinnable mob.

**Additional context**
BTW, I really admire the author for the persistant committment in this project.

**Comment by Xian55** [comment]
Hello there!

It is a great idea indeed.  👏   The gathering feature it self going to be more prominent in the upcoming classic expansion.

One hacky way by adding the corresponding NPC ids to the `Json/area/<mapid>.json` `skinning` database, as long as a fully fledged idea is added. 

Will look into it, soon. 🙇

**Comment by Xian55** [comment]
Just pushed a branch called `feature/more-gatherable-npc`. if you have the time to checkout, and test if its working at your side, i would be grateful, 🙇 

Let me know if you encounter any issues.

**Comment by AsterNighT** [comment]
That's really a lightning fast update. But I ran into some trouble.
I set mode to "AttendedGrind", true for herb and false for skinning and mining. The bot looted the mob but did not try to gather it.
I believe these are the related logs:
```
[18:19:09:232 INF] New Plan=  Consume Corpse
[18:19:09:369 INF] ----- Safe to consume a corpse.
[18:19:09:382 INF] New Plan=  Loot
[18:19:09:410 INF] NpcNameFinder.ChangeNpcType = Corpse | searchMode = Simple
[18:19:09:411 INF] NpcNameFinder.ChangeNpcType = None | searchMode = Simple
[18:19:09:414 INF] Look at possible corpse and try again
[18:19:09:415 INF] NpcNameFinder.ChangeNpcType = Corpse | searchMode = Simple
[18:19:11:513 INF] LootGoal: No corpse name found - check last dead target exists
[18:19:11:618 INF] LootGoal: Should gather 18124 ? True
[18:19:11:620 INF] LootGoal: Found last dead target
[18:19:11:724 DBG] CombatUtil:   Went for corpse 0.0001ms
[18:19:12:597 INF] LootGoal: Last dead target double
[18:19:13:364 INF] LootGoal: Loot Successfull
[18:19:14:278 INF] New Plan=  Skinning
[18:19:17:068 INF] SkinningGoal: Target(0) is not skinnable - NPC Count: 4
[18:19:18:082 INF] SkinningGoal: Loot Failed
[18:19:18:092 INF] NpcNameFinder.ChangeNpcType = None | searchMode = Simple
[18:19:18:107 INF] New Plan=  Corpse Consumed
[18:19:18:113 INF] ----- Corpse consumed. Remaining: 0
```

**Comment by AsterNighT** [comment]
I guess it has something to do with the font. I'll switch to a bolder font and try again.
UPD: Nope, the font is already Roboto Medium and to zoom in does not help either,

**Comment by Xian55** [comment]
Hi thanks for checking out. It seems the feature it self working. Found a Gaterable (herbalism) npcid [18124](https://www.wowhead.com/npc=18124/withered-giant) in the database. 

The issue seems to be, conflicting features
```
[18:19:12:597 INF] LootGoal: Last dead target double
```
and 
```
[18:19:17:068 INF] SkinningGoal: Target(0) is not skinnable - NPC Count: 4
```
where `Target(0)` means it was unable to click on the hithox, but `NPC Count: 4` means the `NpcNameFinder` component actually found something!

Those mobs(18124) are quite huge in height, so probably the corpse name was too far away from the actual hitbox.

I've been keep updating locally, where im fighting with Nagas, or those Bog Lords. like
https://github.com/Xian55/WowClassicGrindBot/blob/a22e9048d9850383346e0840f1c72db2c0f0530d/Core/GoalsComponent/NpcNameTargeting.cs#L47

```cs
locFindByCursorType = new Point[]
{
    new Point(0, 0),
    new Point(0, 25).Scale(npcNameFinder.ScaleToRefWidth, npcNameFinder.ScaleToRefHeight),
    new Point(0, 75).Scale(npcNameFinder.ScaleToRefWidth, npcNameFinder.ScaleToRefHeight),
    new Point(0, 100).Scale(npcNameFinder.ScaleToRefWidth, npcNameFinder.ScaleToRefHeight),
    new Point(0, 125).Scale(npcNameFinder.ScaleToRefWidth, npcNameFinder.ScaleToRefHeight),
};
Array.Reverse(locFindByCursorType);
```

which has pros and cons:
* pro: can find really tall npcs
* pro: starts the search from bottom to top so more likely to click on it
* cons: takes more sample to find the corpse
* cons: for small creatures takes longer to find them

i've been thinking about making a small and huge modelid based system, however just haven't found the dataset for it. Which should actually fix the issue.

**Comment by Xian55** [comment]
Hey, my apologies, took the short circuit before. The issue was on my end, not properly using the API, even tho compiled, but had faulty mechanism detecting multiple `CursorType`s.

Same branch with https://github.com/Xian55/WowClassicGrindBot/pull/340/commits/5c274f1216ca28317f951c5a932fa43d8d707111 commit should do the work.

**Comment by Xian55** [comment]
After some further testing at the PTR, found out that having 3x more latency than i usually play so ran into some hiccups where prematurely marked failed the Gathering cast, attempted to loot too early. Managed to eliminate these kinds of issues by considering the `World Latency` ms. 

Tested with Skinning + Herb enabled at the same time. I saw that you attempted to herb `18124` which has a really huge model. sometimes the name goes outside of the screen. Temporarily managed to solve it by extending max camera range by 
```lua
/console cameraDistanceMaxZoomFactor 2.6
```

The default value looks like, according to some forum
```lua
/console cameraDistanceMaxZoomFactor 1.8
```

Same branch with https://github.com/Xian55/WowClassicGrindBot/pull/340/commits/618e5a8e139ce8af6ee25377b40895583e701dab commit should do the work.

**Comment by AsterNighT** [comment]
Uhh, I think the latency problem persists. With the latest version I noticed that the bot tried to loot too early (when the death animation was still on. The giant fell slow) so the loot succeeded but the gathering fails. This should be the log:
```
[09:38:54:319 INF] New Plan=  Consume Corpse
[09:38:54:320 INF] ----- Safe to consume a corpse.
[09:38:54:334 INF] New Plan=  Loot
[09:38:54:335 INF] NpcNameFinder.ChangeNpcType = Corpse | searchMode = Simple
[09:38:54:672 INF] NpcNameTargeting: NPC found! Height=9, width=112, pos={X=1063,Y=390}
[09:38:54:673 INF] LootGoal: Found corpse - clicked
[09:38:54:702 INF] LootGoal: Found target after 28.6744ms
[09:38:54:702 INF] LootGoal: Should gather 18124 ? True
[09:38:54:752 DBG] CombatUtil:   Went for corpse 48.9175ms
[09:38:55:902 INF] LootGoal: Had to move so interact again
[09:38:56:469 INF] LootGoal: Loot Successfull
[09:38:56:538 INF] New Plan=  Skinning
[09:38:59:354 INF] SkinningGoal: Target(0) is not skinnable - NPC Count: 3
[09:39:00:370 INF] SkinningGoal: Loot Failed
[09:39:00:376 INF] NpcNameFinder.ChangeNpcType = None | searchMode = Simple
[09:39:00:377 INF] New Plan=  Corpse Consumed
[09:39:00:377 INF] ----- Corpse consumed. Remaining: 0
[09:39:00:392 INF] New Plan=  Wait
[09:39:00:393 INF] Waiting
```

**Comment by Xian55** [comment]
Prev commit, only waited `World Latency / 2`. 

From https://github.com/Xian55/WowClassicGrindBot/pull/340/commits/0078edf5b0d84d49d5b48061f7afeed39fd2e9c0 it going to wait the whole World Latency duration. For me its 47ms.

If you could share yours would be helpfull. 🙇

**Comment by AsterNighT** [comment]
I may have expressed my problem in a bad way. If you mean the network latency It is like 40~50ms for me. But by latency I mean there's an animation to be played when the mob dies. And for a mob like `18124` which is huge the animation takes quite some time. So the following would happen:

1. The mob dies.
2. The bot found the nameplate and click the corpse.
3. The animation plays. And it causes the corpse to "move" away from the cursor.
4. The bot does not seem to recognize the "moved" corpse and does not try to gather it.

**Comment by Xian55** [comment]
Hey i'm aware of the mentioned issue. 

Currently the only way to make it slightly better, by reversing the search order from **top to bottom** to **bottom to top** that way more likely to hit the corpse hitbox.

For those big mobs you may have to add extra Y positions for `locFindByCursorType`

In my previous comment already shared a possible solution

> Hi thanks for checking out. It seems the feature it self working. Found a Gatherable (herbalism) npcid [18124](https://www.wowhead.com/npc=18124/withered-giant) in the database.
> 
> The issue seems to be, conflicting features
> 
> ```
> [18:19:12:597 INF] LootGoal: Last dead target double
> ```
> 
> and
> 
> ```
> [18:19:17:068 INF] SkinningGoal: Target(0) is not skinnable - NPC Count: 4
> ```
> 
> where `Target(0)` means it was unable to click on the hithox, but `NPC Count: 4` means the `NpcNameFinder` component actually found something!
> 
> Those mobs(18124) are quite huge in height, so probably the corpse name was too far away from the actual hitbox.
> 
> I've been keep updating locally, where im fighting with Nagas, or those Bog Lords. like
> 
> https://github.com/Xian55/WowClassicGrindBot/blob/a22e9048d9850383346e0840f1c72db2c0f0530d/Core/GoalsComponent/NpcNameTargeting.cs#L47
> 
> ```cs
> locFindByCursorType = new Point[]
> {
>     new Point(0, 0),
>     new Point(0, 25).Scale(npcNameFinder.ScaleToRefWidth, npcNameFinder.ScaleToRefHeight),
>     new Point(0, 75).Scale(npcNameFinder.ScaleToRefWidth, npcNameFinder.ScaleToRefHeight),
>     new Point(0, 100).Scale(npcNameFinder.ScaleToRefWidth, npcNameFinder.ScaleToRefHeight),
>     new Point(0, 125).Scale(npcNameFinder.ScaleToRefWidth, npcNameFinder.ScaleToRefHeight),
> };
> Array.Reverse(locFindByCursorType);
> ```
> 
> which has pros and cons:
> 
> * pro: can find really tall npcs
> * pro: starts the search from bottom to top so more likely to click on it
> * cons: takes more sample to find the corpse
> * cons: for small creatures takes longer to find them
> 
> i've been thinking about making a small and huge modelid based system, however just haven't found the dataset for it. Which should actually fix the issue.

**Comment by AsterNighT** [comment]
Oh my bad. I did not fully understand that. So I do some more tests and there are interesting results.
I'm testing the config with a mage and I may need to drink water after every kill. If I drink after the kill, there will be enough time for the mob to fall, and the gather attempt fails. But if I do not drink and loot instantly after the kill, the gather succeeds!
I did some measurement on the screen and consider 125 not enough. Instead I change it to something like
```c#
            locFindByCursorType = new Point[]
            {
                new Point(0, 0),
                new Point(0, 25).Scale(npcNameFinder.ScaleToRefWidth, npcNameFinder.ScaleToRefHeight),
                new Point(0, 75).Scale(npcNameFinder.ScaleToRefWidth, npcNameFinder.ScaleToRefHeight),
                new Point(0, 100).Scale(npcNameFinder.ScaleToRefWidth, npcNameFinder.ScaleToRefHeight),
                new Point(0, 200).Scale(npcNameFinder.ScaleToRefWidth, npcNameFinder.ScaleToRefHeight),
                new Point(0, 300).Scale(npcNameFinder.ScaleToRefWidth, npcNameFinder.ScaleToRefHeight),
                new Point(0, 400).Scale(npcNameFinder.ScaleToRefWidth, npcNameFinder.ScaleToRefHeight),
                new Point(0, 500).Scale(npcNameFinder.ScaleToRefWidth, npcNameFinder.ScaleToRefHeight),
                new Point(0, 600).Scale(npcNameFinder.ScaleToRefWidth, npcNameFinder.ScaleToRefHeight),
            };
            Array.Reverse(locFindByCursorType);
```
Work like a charm. I've tested it without the `500` and `600` ones and it still fails occationally on the big ones. I do not feel any sensible fallback on performance.
I assume this is a "good enough" solution to this once and for all. Just filling enough values in the array.

**Comment by Xian55** [comment]
What game client locale are you using?
