### ISSUE TITLE
Cant Loot, Unable to find an entry point named 'GetDpiForSystem' in DLL 'user32.dll.

### ISSUE THREAD

**Issue by Billdong1997** [Xian55/WowClassicGrindBot#34]
Dear Author
Thank you for sharing the improved bot, it's very nice. But I encounter some troubles in Looting. My bot can't loot properly. When mobs died, The lootgoal can't perform well. The problem is that unable to find an entry point named 'GetDpiForSystem' in DLL 'user32.dll. How can I solve it? thank you.  OS is win8.1. Is win10 needed? 
![image](https://user-images.githubusercontent.com/83825966/117533205-2919db80-b01e-11eb-9d8e-1a76a2f9948b.png)

**Comment by Xian55** [comment]
Hey thanks for reaching out. `GetDpiForSystem` requires windows 10 to be installed.
`Windows 10, version 1607 [desktop apps only]`

https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getdpiforsystem

might to do something about it in the future days. Until then try to switch to the mentioned windows version.

**Comment by Xian55** [comment]
Hello there!
i've made a fix about the mentioned issue. At this point of time i'm unable to test it under the given win 8.1 nor win 7.
With the supplied fix, it should work on win 7 and 8.1 as well.

If i may ask a favour, could you check out `https://github.com/Xian55/WowClassicGrindBot/tree/fix/i/34` or in short the given `fix/i/34` branch and test it. I would be really grateful on your feedback.

Thanks,
Xii

**Comment by Billdong1997** [comment]
Hey！ 
I have already test it and everything is OK with win8.1! The problem has been fixed and the bot can loot properly. You are excellent. Thank you very much :)

**Comment by Xian55** [comment]
Thanks for the feedback and testing the branch.
