### ISSUE TITLE
Character is stuck in the sea

### ISSUE THREAD

**Issue by AsterNighT** [Xian55/WowClassicGrindBot#343]
### Description

During grinding the character could be attracted to mobs in the sea. And sometimes the character cannot find a way back to the shore. 
I'm not sure if the bot can tell that you are swimming or not. A possible last resort may be to record the latest position on the shore/can find a path and to go straight towards the positon if no path can be found.

### Addon Version

1.4.5

### World of Warcraft Client

The Burning Crusade Classic

### Reproduction Steps

1. Use any profille, melee class profile preferred.
2. Use some seaside path, the hinterlands 48-50 turtle path and the tanaris turtle path are good choices.
3. Let the bot run for a moment, you can manaully select mobs far from the shore to accelarate the process.
4. At a certain distance the bot fails to find a way back.

### Last Good Version

Nope

### Logs

You just get tons of `Character stuck` info.

**Comment by alex498** [comment]
If i remember properly, there not only turtles and sometimes mapid changing cause of location change
Also our local coordinates changing dramatically that is the reason of this kind of bug

**Comment by AsterNighT** [comment]
I don't think that's the case for me, at lease not for hinterlands and tanaris.

**Comment by Xian55** [comment]
Hello there!

`Character stuck` means that most likely you are moved outside of the navmesh thus the pathfinder unable to calculate path back to the route location.

**Comment by AsterNighT** [comment]
I looked into the code a llittle bit. There seem to be two types of "stuck".
1. The character is literally blocked by some structure, thus being unable to change its distance to navagation target. This includes routing target(https://github.com/Xian55/WowClassicGrindBot/blob/dev/Core/GoalsComponent/Navigation.cs) and pull target(https://github.com/Xian55/WowClassicGrindBot/blob/dev/Core/Goals/PullTargetGoal.cs)
2. The pathing API cannot find a path from the character positon to target potison. This happens in routing only. (https://github.com/Xian55/WowClassicGrindBot/blob/dev/Core/GoalsComponent/Navigation.cs#L377)

The bot now handles the two "stuck" types in the same way. It turns and moves randomly (https://github.com/Xian55/WowClassicGrindBot/blob/dev/Core/GoalsComponent/StuckDetector.cs#L75).

For "stuck" no.1 it usually works. A possible enhancement to it may be to extend the turning and moving time as the "stuck" persists. Since the short random moves does not solve the problem.

But for "stuck" no.2 it seldom works actually. The character could be miles away from the the nav mesh. What saves the character is often a mob that changes the target to pull and combat. But generally it happens on those "plain" areas like in the sea (Otherwise you would not go this far in the first place). I'm wondering if there will be a better solution to it, like simply head back to the last "good" position.

Oh, and some kind of notification could be useful too.

**Comment by Xian55** [comment]
Nice findings, been working on other things at the moment, primarily improving the loot and skinning, but the rabbit hole goes so deep and ran into some unexpected inconsistencies so all my focus goes there. Sorry for not responding in a more detailed manner.

[StuckDetector](https://github.com/Xian55/WowClassicGrindBot/blob/dev/Core/GoalsComponent/StuckDetector.cs#L75) definitely requires some more in-depth strategies to attempt to recover from stuck. 

Over the last update, probably tightened too much the navigation constraints, relying on the pathfinder too much, as calling the it on each `Navigation.routeToNextWaypoint` points. I did it on purpose, to give support _non-uniform-distance_ routes such as [_vein and _herb](https://github.com/Xian55/WowClassicGrindBot/blob/dev/Json/path/_herb/12_Elwynn%20Forest_herb_optimal.json) as they not recorded by human, but filtered and generated based of wowhead data.

Well the last known good location is the _previously reached route location_(**PRRL**) . However sometimes its just not good enough to look at the **PRRL** and move straight forward, as there could unknown slopes which prevents to go forward.

I've been thinking about for a while, to improve what a single Path file contains. Not just the list of Vector3 coordinates, but like `uimapid` and more, but it takes significant effort to update the tooling and regenerate the existing paths...

I would be willing to take time to integrate [discord.net](https://discordnet.dev/index.html) been using on other project, by only starting the _discord bot_ when a notification is needed, and the cold start is awful, like 6seconds or something. Might be using the API wrong, for that part. However at first glance the project doesn't seems to stable for me.

**Comment by AsterNighT** [comment]
> Well the last known good location is the previously reached route location(PRRL) . However sometimes its just not good enough to look at the PRRL and move straight forward, as there could unknown slopes which prevents to go forward.

Well if you are out of nav mesh, there does not seem to be any better ideas. It could be some "do sth (i.e. hearthstone) if being stuck for too long".

> I've been thinking about for a while, to improve what a single Path file contains. Not just the list of Vector3 coordinates, but like uimapid and more, but it takes significant effort to update the tooling and regenerate the existing paths.

Maybe the old paths don't have to be updated, or a default value would suffice.

> I would be willing to take time to integrate [discord.net](https://discordnet.dev/index.html) been using on other project, by only starting the discord bot when a notification is needed, and the cold start is awful, like 6seconds or something. Might be using the API wrong, for that part. However at first glance the project doesn't seems to stable for me.

So you were trying to host the bot locally? Does that mean the token has to be distributed?

**Comment by Xian55** [comment]
> So you were trying to host the bot locally? Does that mean the token has to be distributed?

No, everyone has to create a Discord bot at the [discord developer](https://discord.com/developers) site obtain the secret key for it. Create a dummy discord server and make sure you and your newly created bot are connected, that way the bot can send you private messages and images.

At the Master of puppet bot side in a config file / cmd have to give that secret key, and the your user profile id.

**Comment by AsterNighT** [comment]
That does not seem to make sense. Discord bot is nothing but Rest API. There's no reason it would require a 6-seconds-long start.
I'm willing to look into it, if you consider it worth implementing. The goapkey system is still a little confusing to me:facepalm:.

**Comment by Xian55** [comment]
> I'm willing to look into it, if you consider it worth implementing

Personally, not really high prio feature for me. Just got access to the new beta version, so i rather focus on those first.

> The goapkey system is still a little confusing to me

The project attempts to use [this GOAP](https://gamedevelopment.tutsplus.com/tutorials/goal-oriented-action-planning-for-a-smarter-ai--cms-20793) implementation. In short GOAPKeys are essentially a `WorldState` object keys which as of today booleans.

**Comment by Xian55** [comment]
If you have the time, to checkout and share your findings with the given `fix/stuck-detector-increase-base-movement-time` branch i would appreciate 🙇

**Comment by AsterNighT** [comment]
Not in a fortnight :facepalm:. I leave the bot running and totally forget about it which leads to a temporary suspension.

**Comment by Xian55** [comment]
While using PPather navigation, after https://github.com/Xian55/WowClassicGrindBot/commit/c0e00dd89ee20a33217447b715debdb02e0deaea player should be able to navigate while its in the water.
