### ISSUE TITLE
Use bot path finding in instance

### ISSUE THREAD

**Issue by coolzoom** [Xian55/WowClassicGrindBot#344]
Love this project, I have tried it appears only able to find path in outdoors, Is it possible to use pathfinding in an instance? And how to use removtv3 path finding?

**Comment by Xian55** [comment]
Hello there!

> Is it possible to use pathfinding in an instance?

To this point i was unable to find any solution for this, sadly as of today no. Once you enter an instance. and type
`/dump C_Map.GetPlayerMapPosition(C_Map.GetBestMapForUnit("player"), "player"):GetXY()`
returns with **0, 0** coordinates. As it works as the in-game api intended.

> how to use removtv3 path finding?

[Here's a short how to setup](https://github.com/Xian55/WowClassicGrindBot#22-using-v3-remote-pathing) Remote Pathing V3. In a little bit verbose, what `Create a build` means. 

First you have to download Visual Studio 2019 and make sure to check the `Desktop development with C++` box
![image](https://user-images.githubusercontent.com/367101/180349825-31d66a8d-cd8e-4700-b274-040a7caf7f2d.png)
Open the solution, select the currently using windows version and press build.

Going to update the related docs, thanks for bringing it to my attention.

One quick note, since the PPather project had been refactored quite a lot, the Local V1 pathing is capable of decent performance, so i suggest, only attempt to use Remote V3 if you encounter any breaking issues with V1.

**Comment by coolzoom** [comment]
Hello man, Thanks for the response, yes, when I looked into this, using the DataToColor method is not able to get the game coordinate inside the instance, it is reading the XY location from the addon API you mentioned above, so we have to read the game memory to get the physical X/Y/Z location for instance, also for Remove V3 when I read the document from Trinity core it appears it is using the physical X/Y/Z location, not the coordinate read by the addon API.
If we are able to hook the memory and read the XYZ locations, we might be able to make the pathing work anywhere, but I'm not sure how to find the correct addresses for those, Are you able to hook the memory and find the physical X/Y/Z locations?

**Comment by lavjamanxd** [comment]
i think theres a reason why its called a pixel based bot, all what it can do is done without reading the games memory to reduce the chances of getting caught

**Comment by Xian55** [comment]
> have to read the game memory

Certainly that would be the solution, however goes against the the project principle as _"No DLL injection or memory watching"_

I encourage you to take time, create a fork of the project and feel free to integrate the change you intended. 🙇 

[Here](https://drewkestell.us/Article/6/Chapter/1) a wonderfully written blog about how you can achieve that.

**Comment by coolzoom** [comment]
Yes agreed, thanks for the info, i will do some study on that.
Best wishes

**Comment by coolzoom** [comment]
Comment this for discussion only, I've managed to hook to the memory and find the correct offset,
https://github.com/coolzoom/WowClassicGrindBot/commits/dev

so this allows us to navigate it anywhere, including dungeons,
but WowClassic is an x64 program, we have to compile the bot into the x64 program.
However, the PPather rely on the x86 StormLib and ccode.dll(no source code), were x86 dll, so if we are going to use the memory hook to get the location, we can only use the remoteV3 recast navigation method, I have tested it works,
Also, the navigation system was written for the UI coordinate, so it also needs heavy change because the coordinate system changes.

I'm afraid to make PR for this, so let me know if we needs to move ahead use memeory hook which allows the possibility of navigation inside dungeons.

**Comment by Xian55** [comment]
Hi, hmm didn't expected that, you really took time for the research 🙇 

Couple of months back tried grab the latest [StormLib](https://github.com/ladislav-zezula/StormLib), managed to compile it to x64, but after replacing the Storm.dll file around, `SFileOpenArchive` consistently failed with 'Unknown image' error or something like that, stopped working on it...

In recent times i've extract the PPather into its own project, which is working for now, till end of Wrath of the Lich king. However after then, the cataclysm map rework going to happen. Have to do something with the MPQ navigation anyway.

Im glad you took the time for prepping this up, but as i stated before, memory tampering is not what i would gladly include to the project. The whole memory pattern searching means that, whenever a new executable comes out, have to provide the offsets as soon as possible, for 4? different client version, SoM, Classic TBC, Classic Wotlk, and retail.

On the other hand, can you provide some risk assessment, about `Process.NET` ?

**Comment by coolzoom** [comment]
>
_"On the other hand, can you provide some risk assessment, about Process.NET ?"_

it is an open-source process tool based on the native windows method https://github.com/lolp1/Process.NET,
if we are not changing the memory, just monitor, it should be very safe. i think.

> 
_"In recent times i've extract the PPather into its own project, which is working for now, till end of Wrath of the Lich king. However after then, the cataclysm map rework going to happen. Have to do something with the MPQ navigation anyway."_

yes appears the recast navigation method should be the better way while we have reference from the trinity core team
