### ISSUE TITLE
[Hunter] doesn't use any skills

### ISSUE THREAD

**Issue by Adrinalin4ik** [Xian55/WowClassicGrindBot#35]
Hi, I just install and launch your bot and it seems like the bot won't attack a target using some spells. I checked out a class profile file and everything there is correct. Could you suggest me smth?

**Comment by Xian55** [comment]
Hey!
With the given info its very vague, can't say anything specific. It would be the best if you could attack every `*.log` file you so i can take a look. Thanks

**Comment by Xian55** [comment]
bump

**Comment by Adrinalin4ik** [comment]
Hi! Thank you for your response. Finally, I figured out that the problem was in the incorrect battle state defenition, so I just fixed this and it works:). Next, I faced the loot issue. it works really bad for the hunter, I figure out how to deal with it but I had to modify some code.  Btw I created a hunter profile which is probably will be beneficial for the others.

**Comment by Adrinalin4ik** [comment]
I tested this profile on my hunter and got quite good results.

**Comment by Xian55** [comment]
Thanks for sharing your experience. May i ask what issue you encountered when mentioned the 
`"Next, I faced the loot issue. it works really bad for the hunter"` is it related to https://github.com/Xian55/WowClassicGrindBot/issues/34 ?

On the other hand `"I figure out how to deal with it but I had to modify some code"` if you have the time to share with others, you can open a pull request about it, and we can discuss about in detail.

Personally i haven't been used it with hunter leveling

**Comment by Billdong1997** [comment]
Thanks for sharing the profile but may i ask you change the names into English so that we can understand your profile better. :) best wishes.

**Comment by Adrinalin4ik** [comment]
> Thanks for sharing your experience. May i ask what issue you encountered when mentioned the
> `"Next, I faced the loot issue. it works really bad for the hunter"` is it related to #34 ?
> 
> On the other hand `"I figure out how to deal with it but I had to modify some code"` if you have the time to share with others, you can open a pull request about it, and we can discuss about in detail.
> 
> Personally i haven't been used it with hunter leveling but made lot of progress in `PullGoal` and `CombatGoal` using warlock and utilize the pet.
> 
> Can you describe what difficulties you had when tried to setup? Im trying to imply on `"Setting up is terrible"`

Your warlock's profiles really help me, thanks. My issues is not connected with #34.  
- I've added new precondition to  followRouteGoal ->  !hastarget, 
- combatGoal -> remove condition with incombatrange (this was current issue that stops bot of using the skills). 
- Next I've implemented DelayBeforeCast and DelayAfterCast hooks to adhocGoal, 
- I've enable block on 114 line of LootGoal with a 4s delay - this one help me to w8 until hunter come to the mob and pick up the loot.
- I also issued with the map bug and some crashes, I have fixed it. This one in MPQTriangleSupplier in SetContinent method. Sometimes location is null and it cause fatal error after a while.  it looks like bot is trying to find location but it doesn't exist in json with locations. On kalimdor I didn't have such issue but azeroth didn't works. I just made a return condition if continent is null.
- Next I've fixed a mob selection. It seems like program always click on name of mob, but it is not a good way. I've added 30px more to Y axes in order to click right on mob, it works almost perfect.
- The last one I've added new precondition to pullGoal -> targetisalive

**Comment by Adrinalin4ik** [comment]
Btw, maybe you can help me with another issue. When I come to mob, sometimes I haven't reached him and I'm stayling in blind zone and can't attack. After a few second, bot rotating with RightArrow for 999ms (looks like 180 degree). I've tried to find the likes of code with this logic but it wasn't succeed

**Comment by Xian55** [comment]
Hunter have dead zones that's a thing, personally I haven't checked hunter yet, working on other stuffs atm. The original author stated the hunter is not supported yet tho.

`"the bot rotating with RightArrow for 999ms (looks like 180 degrees). I've tried to find the likes of code with this logic but it wasn't successful."`
The given description fits for all of the melee classes atm, especially if low level when have to fight with signature/neutral npcs. That case the bot switches to the `FollowRouteGoal` and immediately switch back to `CombatGoal` and keep bouncing between these two. I know about this issue but haven't found a good solution for a problem.

**Comment by Xian55** [comment]
> Btw, maybe you can help me with another issue. When I come to the mob, sometimes I haven't reached him and I'm staying in a blind zone and can't attack. After a few seconds, the bot rotating with RightArrow for 999ms (looks like 180 degrees). I've tried to find the lines of code with this logic but it wasn't successful.

Its called `CastingHandler.InteractOnUIError`

**Comment by Billdong1997** [comment]
> Btw, maybe you can help me with another issue. When I come to the mob, sometimes I haven't reached him and I'm staying in a blind zone and can't attack. After a few seconds, the bot rotating with RightArrow for 999ms (looks like 180 degrees). I've tried to find the lines of code with this logic but it wasn't 
I have an idea about this problem. When you cant attack and you are in the battle range (8-35 yard), if there is a tree/house/stone or other obstacles, the character cant attack or cast. Once it occurs, we can let the bot run out of the 35 yard range to make the distance > 35 yard, then we can press the key "interact" again. It will find another way to the mob until the distance <35 yard.  I have tested this method in other casting classes(mage/warlock) and it works (at this time the distance is 30 yard of Frostbolt/ShadowBolt ). I make it on another simple scripting language to make a bot, i dont know how to write it in C# it's a little hard for me now:) But I think the idea is a kind of way to solve the problem. Just for your reference.

**Comment by Billdong1997** [comment]
> Next, I've fixed a mob selection. It seems like the program always clicks on the name of the mob, but it is not a good way. I've added 30px more to Y axes in order to click right on mob, it works almost perfect.
@Adrinalin4ik 
Which .cs should i modify to added 30px in y axes? Thank you

**Comment by Adrinalin4ik** [comment]
checkout #44

**Comment by Adrinalin4ik** [comment]
To fix an issue with a dead zone highly important to have an exact value of the range, not only whether I can attack or not. It would be more flexible if it'll be like a requirement. If I had a range I just can check it and if it's a dead zone just use StepBackAfterCast in combat requence and the problem is solved.

**Comment by Adrinalin4ik** [comment]
Another important thing which I looking forward to is to have the health of my per and the fedness.

**Comment by Adrinalin4ik** [comment]
Let's continue the conversation there #43

**Comment by Xian55** [comment]
Hey we can continue the discussion in a more immediate manner. I appreciate your feedback about the hunter. If you want you can join us https://discord.gg/wuSWxyD

**Comment by Xian55** [comment]
If you have a moment, could you check out the following branch. https://github.com/Xian55/WowClassicGrindBot/tree/feature/class/hunter

Beside the mentioned 
- Targeting issue with the mouse -> solved by offsetting the Y by 30 unit
- PathingAPI issue when the character stuck in one place
- PathhingAPI issue when `Alterac` map has multiple? mapids
- MPQTriangleSupplier in SetContinent null

Do you see any improvement since we last talk about the hunter?
Thanks!
