### ISSUE TITLE
error CS0246: The type or namespace name 'IAddonDataProvider' could not be found

### ISSUE THREAD

**Issue by nullspeaker** [Xian55/WowClassicGrindBot#358]
### Description

[here](https://github.com/Xian55/WowClassicGrindBot/blob/dev/Core/Talents/TalentReader.cs#L26)
change `IAddonDataProvider` to `AddonDataProvider` to work with [this merged pr](https://github.com/Xian55/WowClassicGrindBot/pull/290)

### Reproduction Steps

`dotnet build`

**Comment by Xian55** [comment]
Hello, working on `IAddonDataProvider` related stuff at the moment, accidently pushed an unfinished change, apologies about the issue. This PR wont be merged. As my package coming soon ish, when i find the last part of the puzzle 👍

**Comment by nullspeaker** [comment]
👍

**Comment by Xian55** [comment]
#360 should fix the issue. It is already at `dev`. Let me know if you encounter any further issue 🙇
