### ISSUE TITLE
Feature Request: Pull target to safe location and combat

### ISSUE THREAD

**Issue by coolzoom** [Xian55/WowClassicGrindBot#371]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
 during outside Grinding, there is a chance it has a large number of mobs in your grinding area,
We need to find a way to define "Safe location" in the classic config file, 
for example, after pulling mobs, the character runs back to one of the safe locations to keep combat with the mob, 
after killing the mob, pull one again, then run to the "Safe location" again
![image](https://user-images.githubusercontent.com/10232727/182513027-12c3dde9-71bd-4063-a0cd-2c2029aff622.png)
**Additional context**
This is just a suggestion, it is not urgent, I will also have a look and see what I can do in my spare time.

I'm not currently familiar with the GOAP routine, will have to read and understand how to plan a route after pulling the target

**Comment by coolzoom** [comment]
maybe later

**Comment by jsRuner** [comment]
good idea.
but add complex  ，easy error

**Comment by coolzoom** [comment]
> good idea. but add complex ，easy error

yes because the current GOAP system is already very complex. though it is flexible but so complex.

**Comment by Xian55** [comment]
Hey, the suggestion sounds great, im wondering about how could you determine a "safe location" when the only info you been able to gather is the target, without any location info?

**Comment by coolzoom** [comment]
> Hey, the suggestion sounds great, im wondering about how could you determine a "safe location" when the only info you been able to gather is the target, without any location info?

we could use a path file or simple coordinates in the classic config, user can define those "safe locations", normally those are some fixed places, so after pulling a mob the character can move to the closest save location keep combat.

**Comment by coolzoom** [comment]
Reopen for discussion, 
here is what i tried, but without a clear mind, i could not make it happen.
https://github.com/coolzoom/WowClassicGrindBot/commits/blocks
it appears some optimize we could make to the GoapKey.pulled. it was set to fixed false in our current code.
while we will have to use this key to define wheter if we have pulled an mob

**Comment by Xian55** [comment]
[GoapAgent.WorldState](https://github.com/coolzoom/WowClassicGrindBot/commit/72f84da757bc22846841a6e1ec82d4720b3f97dc#diff-9a36734a6778dd9d037e11a596651adbc69fb1b920fdec0d0f808175a10c2513R191) supposed to be stateless or readonly, only accepting data coming from World(AddonReader/PlayerReader). In the long run going to be harder to design more complex Goals.

> we could use a path file or simple coordinates in the classic config, user can define those "safe locations",

Most mobs are patrolling, within a radius of small random movement, not really seeing the point hard coding locations which were marked prematurely "safe".

**Comment by coolzoom** [comment]
> [GoapAgent.WorldState](https://github.com/coolzoom/WowClassicGrindBot/commit/72f84da757bc22846841a6e1ec82d4720b3f97dc#diff-9a36734a6778dd9d037e11a596651adbc69fb1b920fdec0d0f808175a10c2513R191) supposed to be stateless or readonly, only accepting data coming from World(AddonReader/PlayerReader). In the long run going to be harder to design more complex Goals.

yes, I'm not quite clear with that logic, forgive the mess.

**Comment by Xian55** [comment]
the goap implementation based on this [article](https://gamedevelopment.tutsplus.com/tutorials/goal-oriented-action-planning-for-a-smarter-ai--cms-20793) without multi plan support as of now, it picks the first (lowest cost goal)

**Comment by coolzoom** [comment]
> the goap implementation based on this [article](https://gamedevelopment.tutsplus.com/tutorials/goal-oriented-action-planning-for-a-smarter-ai--cms-20793) without multi plan support as of now, it picks the first (lowest cost goal)

I saw this article, but reading to understand the code is also a thing. i dont even know what question to ask for now, so allow me some more time to digest.

**Comment by coolzoom** [comment]
@Xian55  
in-game I don't see the pulled state ever changed, when I check for this
https://github.com/Xian55/WowClassicGrindBot/blob/645b4b59f83e5c26d164113b783bf218e219d969/Core/GOAP/GoapAgent.cs#L214 

the pulled was set to false, so it is always false, how should we know whether we "pulled" a target?

**Comment by Xian55** [comment]
To my knowledge it only suppose to change by a single frame.

https://github.com/Xian55/WowClassicGrindBot/blob/645b4b59f83e5c26d164113b783bf218e219d969/Core/Goals/PullTargetGoal.cs#L134

https://github.com/Xian55/WowClassicGrindBot/blob/645b4b59f83e5c26d164113b783bf218e219d969/Core/Goals/PullTargetGoal.cs#L208

https://github.com/Xian55/WowClassicGrindBot/blob/645b4b59f83e5c26d164113b783bf218e219d969/Core/Goals/PullTargetGoal.cs#L214

But anyway that flag dosen't used for any meaningful way. 

PullGoal was designed such a way, that it, it can executes the specified sequence in respect to the order. That's the only goal.

Detecting pull it self is not an easy task to do. There are couple of scenarios, where it takes considerable amount of time when the player target is targeting the player like using projectile based ability, `Fireball`, `Serpent String` ...

Not exactly sure how you want to achieve this goal, as the `Navigation` component going to face the player away from the target, to show the players back possible getting [dazed](https://www.wowhead.com/spell=38767/daze), you could die before even reaching the marked "Safespot".

**Comment by coolzoom** [comment]
> To my knowledge it only suppose to change by a single frame.
> 
> https://github.com/Xian55/WowClassicGrindBot/blob/645b4b59f83e5c26d164113b783bf218e219d969/Core/Goals/PullTargetGoal.cs#L134
> 
> https://github.com/Xian55/WowClassicGrindBot/blob/645b4b59f83e5c26d164113b783bf218e219d969/Core/Goals/PullTargetGoal.cs#L208
> 
> https://github.com/Xian55/WowClassicGrindBot/blob/645b4b59f83e5c26d164113b783bf218e219d969/Core/Goals/PullTargetGoal.cs#L214
> 
> But anyway that flag dosen't used for any meaningful way.
> 
> PullGoal was designed such a way, that it, it can executes the specified sequence in respect to the order. That's the only goal.
> 
> Detecting pull it self is not an easy task to do. There are couple of scenarios, where it takes considerable amount of time when the player target is targeting the player like using projectile based ability, `Fireball`, `Serpent String` ...
> 
> Not exactly sure how you want to achieve this goal, as the `Navigation` component going to face the player away from the target, to show the players back possible getting [dazed](https://www.wowhead.com/spell=38767/daze), you could die before even reaching the marked "Safespot".

Thanks for the detailed explanation, let me think about it.

**Comment by Xian55** [comment]
for melee characters, you can opt in using the `AfterCastWaitMeleeRange` in order to don't rush into pack of mobs.

Don't get me wrong, appreciate the idea, however the lack of area information, make this Goal more then an assumption or guessing rather then a solid tactic.

**Comment by coolzoom** [comment]
> for melee characters, you can opt in using the `AfterCastWaitMeleeRange` in order to don't rush into pack of mobs.

yes, my goal is not to rush into the group of mobs otherwise the character died very often and will have to pay for equipment repair, it doesnt cost much at low level but at higher level the better gear cost very much.

**Comment by Xian55** [comment]
I suggest to check out of the later Druid profiles Pull goal

https://github.com/Xian55/WowClassicGrindBot/blob/645b4b59f83e5c26d164113b783bf218e219d969/Json/class/Druid_20_cat_bear.json#L25

**Comment by Xian55** [comment]
There could be an another solution to this, might be much simpler.

The "safest" location as of current moment is behind the player. As the player can only move forward, turn left or right, there's no strafe yet.

Have to modify the MinRange to start pulling, currently most of the classes uses the possible max range spell to initiate the pull. ex. Mage uses Fireball which has 30-35y range.

What you can do instead is go in like 20y range, do the cast, and start backpedaling for certain seconds. For that you can use `AfterCastStepBack` with -1 to wait GCD, or specifiy a hard coded millisecond amount. The only issue you can encounter are the following:
* while moving you can't do any spell as of yet
* if you ran out of PullRange, most likely gona switch back to `ApproachTargetGoal` or `CombatGoal`.

**Comment by coolzoom** [comment]
> for melee characters, you can opt in using the `AfterCastWaitMeleeRange` in order to don't rush into pack of mobs.
> 
> Don't get me wrong, appreciate the idea, however the lack of area information, make this Goal more then an assumption or guessing rather then a solid tactic.

yes, to explain, area like this in gadgetzan, these mobs are close to each other, normally after each pull, we will engage with 1~2 mobs,
during Grind, we could just pull one and move to a side "safe" position, because there're some mobs wandering around, if we stay in where we pulled the target there is a very high chance to get more mobs engaged and die.

![image](https://user-images.githubusercontent.com/10232727/182606919-94c2811f-7774-48ac-936a-670c5e080bcd.png)

**Comment by coolzoom** [comment]
> There could be an another solution to this, might be much simpler.
> 
> The "safest" location as of current moment is behind the player. As the player can only move forward, turn left or right, there's no strafe yet.
> 
> Have to modify the MinRange to start pulling, currently most of the classes uses the possible max range spell to initiate the pull. ex. Mage uses Fireball which has 30-35y range.
> 
> What you can do instead is go in like 20y range, do the cast, and start backpedaling for certain seconds. For that you can use `AfterCastStepBack` with -1 to wait GCD, or specifiy a hard coded millisecond amount. The only issue you can encounter are the following:
> 
> * while moving you can't do any spell as of yet
> * if you ran out of PullRange, most likely gona switch back to `ApproachTargetGoal` or `CombatGoal`.

Sounds like a plan, let me play around with it and see how it goes, cheers!

**Comment by Xian55** [comment]
>  these mobs are close to each other, normally after each pull, we will engage with 1~2 mobs,
> we could just pull one and move to a side "safe" position

If the mobs are close to each other, you don't have the option to just pull one and deal with it. They are going to chain.

Then if you start moving to what ever location you picked to safespot you still have to deal with 1 or 2 mobs.

My recommendation is that, just avoid those grinding location where there could be mobs patrolling and only grind mobs which are lower then your current level or be equipped with decent gear to deal with multiple one.

The currently existing profiles, beside a few warrior and druid ones, designed with single mob combat in mind.

**Comment by coolzoom** [comment]
yeah, I saw there are conditions in the code to check for multiple targets, so was just thinking to see whether we can push some limits to the current bots system.
it is not an easy task based on the current goap system and would somehow be beyond the purpose of the bots.
when I think further, even though we could have the "safe spot" defined, during path routing it does care whether there're mobs on the way, so it could end with "train" mobs and died much more easily. 
let me close this issue now.

**Comment by Xian55** [comment]
> current goap system and would somehow be beyond the purpose of the bots.

If you have any suggestion to what kind of system could replace the currently used GOAP planner, with reaction based decision making, you can get all my attention.

**Comment by coolzoom** [comment]
> 

I'm not saying the GOAP planner needs to be replaced, in fact it is the best method for a lot of tasks.
I don't have a good idea in mind, but something in my mind is wow has its own particularity, some times a scenarios control or a flow control might be a better fit for some specific tasks

**Comment by Xian55** [comment]
The current GOAP implementation lacks State machine, where different States have different goal in mind.
Or you can think the current state as focusing in grinding Mobs and following the predefined path.
