### ISSUE TITLE
when loot ,enter combat will die

### ISSUE THREAD

**Issue by jsRuner** [Xian55/WowClassicGrindBot#372]
### Description

when go to loot, enter combat ,  player  no action  ,will die

player 's target  is  die  Corpse  , can not  change  enemy unit

because  die corpse  no thing  to  loot , case player  keep   looting   ,  not  can  in  next action

### Addon Version

1.6.2

### World of Warcraft Client

The Burning Crusade Classic

### Reproduction Steps

normal  setup game

gnome mage  level 10  

use  mage_10.json   

use  default path

**Comment by jsRuner** [comment]
loot   if  add    timeOut  config.

keep timeOut  will cancel loot

**Comment by jsRuner** [comment]
hard to happen , no need to  do.  thinks

**Comment by Xian55** [comment]
Hey, glad you made a report about the issue, wait a minute. There has been some changes, about, after killing the target what should be the upper most priority.

Can you give the following info
* Does `Skin` and/or `Herb` enabled in class configuration setup ? 
* Does `KeyboardOnly` enabled in class configuration setup ?
* Are you fighting with multiple target ?
* Are you body pulled a new target while looting the last killed npc.
* Can you specify what npcid you have been killed which cause trouble ?

**Comment by jsRuner** [comment]
1.  skin  enaled
2. keyboardonly disabled
3.  one target
4. no pull , is  add,  enemy  refesh  player near
5.  noraml  enemy,  no  specify

happen condition:  you ready loot  ,hava target ,   in combat  , Corpse no loot

**Comment by Xian55** [comment]
can you share what client language are you using?

**Comment by jsRuner** [comment]
chinese client . but i change to  enUS.

**Comment by Xian55** [comment]
Thanks for the info, will look into it, reporting back soon 🙇

**Comment by coolzoom** [comment]
yeah, the GOAP system is a little bit too complex, maybe sometimes stuck due to the priority.
I'm scratching my head trying to understand the logic. lol

**Comment by jsRuner** [comment]
class Shanman  level 63    
path config is  

`..\json\path\_pack\60-70\Hellfire Peninsula\58-60 Felspark Ravine.json
`
may be  same  question.   

when repair come back， easy  happen  .

player   no action and  keep  stand  util to exit game  or  die 



log is 

`

15:50:33 | New Plan= NO PLAN
-- | --
15:50:33 | ["Water Shield"] GCD: 1483ms \| Cast: 0ms \| Next spell 1087ms
15:50:32 | ["Water Shield"] instant usable: True->False -- "NONE"->"CAST_SUCCESS"
15:50:32 | ["Water Shield"] instant input 89ms True 56.6822ms
15:50:32 | New Plan= " Adhoc"
15:50:32 | [NpcNameFinder] type = "None"
15:49:37 | Pathfinder - 15.024297 - "<53.808197, 39.2255, 53.069443>" -> "<53.8479, 39.3704, 0>" 1.043ms
15:49:28 | Merchant sell grey items finished, took 471.3902ms
15:49:28 | Merchant sell grey items started after 148.2726ms
15:49:28 | Merchant window opened after 118.5298ms
15:49:27 | /run SelectGossipOption(1)--
15:49:27 | Picked 1th for Vendor
15:49:26 | Found Target!
15:49:26 | Use KeyAction.Key macro to aquire target
15:49:26 | No target found by cursor(Vendor, Repair, Innkeeper)!
15:49:26 | [NpcNameFinder] type = "None"
15:48:01 | Pathfinder - 361.61475 - "<62.2823, 38.4612, 53.231754>" -> "<60.3307, 41.5055, 0>" 17.0173ms
15:48:01 | New Plan= " Adhoc N P C"
15:47:53 | [WalkToCorpseGoal]: Random jump
15:47:42 | [WalkToCorpseGoal]: Random jump
15:47:31 | [WalkToCorpseGoal]: Random jump
15:47:27 | Pathfinder - 518.6886 - "<57.639698, 38.422897, 0>" -> "<62.754402, 37.5606, 0>" 64.9496ms
15:47:26 | [WalkToCorpseGoal]: Corpse location is <62.754402, 37.5606, 0>
15:47:26 | [WalkToCorpseGoal]: Player teleported to the graveyard!
15:47:21 | New Plan= " Walk To Corpse"
15:46:09 | New Plan= NO PLAN
15:46:09 | LootGoal: Loot Failed after 3016.7847ms
15:46:06 | LootGoal: Reached Last Target ? False 10004.4196ms
15:45:56 | LootGoal: Target Last Target Found!
15:45:55 | Look at possible closest corpse and try once again...
15:45:55 | [NpcNameFinder] type = "Corpse"
15:45:55 | New Plan= " Loot"
15:45:55 | ----- Safe to consume a corpse.
15:45:55 | New Plan= " Consume Corpse"
15:45:55 | Kill credit detected! Known kills: 1 \| Fighting with: 0
15:45:55 | New Plan= NO PLAN

`

**Comment by Xian55** [comment]
Are you sure pull the latest `dev`?

Yesterday pushed a fix about https://github.com/Xian55/WowClassicGrindBot/commit/b51a1e6212d482acf42ba72792887fe9f10dcb81

If the issue still persist, please upload the full log file, for further investigation!

**Comment by jsRuner** [comment]
no, today  I  try!   thinks

**Comment by jsRuner** [comment]
great!!!!   run  3 hour  no error.   @Xian55    thinks

**Comment by Xian55** [comment]
Glad to hear, feel free to reach out if you ran into any issue 🙇
