### ISSUE TITLE
Group play - mount when target mounts

### ISSUE THREAD

**Issue by adamssullivan** [Xian55/WowClassicGrindBot#374]
**Is your feature request related to a problem? Please describe.**
When trying to us TargetCastingSpell:348459 (Reawakened Phase-Hunter spell) for ad-hoc to force the AssistFocus to mount when I mount. I am unable to get it to work with the Spell ID of the Mount listed above. It does work though if I change the Spell-ID to a casted heal.

**Describe the solution you'd like**
A way to force the AssistFocus mount when the focus target mounts

**Describe alternatives you've considered**
TargetCastingSpell:348459

**Additional context**
no additional to give

**Comment by Xian55** [comment]
hi, can you share the KeyAction - json file where you tried to achieve such action?

Just tested, the spellid of `348459` appears in `playerReader.SpellBeingCastByTarget`

**Comment by Xian55** [comment]
should see something like this
```json
  "Adhoc": {
    "Sequence": [
      {
        "Cost": 18,
        "Name": "MountUp",
        "Key": "N0", // replace with mount key
        "HasCastbar": true,
        "AfterCastWaitCastbar": true,
        "AfterCastWaitGCD": true,
        "Requirements": [
          "!Mounted",
          "TargetCastingSpell:348459"
        ]
      }
    ]
  },
```

Update it seems that `/dump UnitCastingInfo("target")` returns empty even if they are casting.

**Comment by adamssullivan** [comment]
{
    "Name": "Mount",
	"Key": "N0",
    "UseWhenTargetIsCasting": true,
    "Requirement": "TargetCastingSpell:348459"
      },
I tried yours and there was no difference. 

Works with "Requirement": "TargetCastingSpell:8004" (Lesser healing wave rank 1)

**Comment by Xian55** [comment]
yea it seems with the current skill set unable to tell if the target is mounted. Will look into it soon

Recently added a feature to keep track of player buff cooldown, and target debuff cooldowns, with that logics, it is possible to keep track of target buffs via texture-icon id, most likely gonna expand on this idea.

**Comment by adamssullivan** [comment]
Thanks. FYI: The Target NPC works great. I was able to get through multiple quests and it was working great. Thanks for adding that a couple of weeks ago.

**Comment by Xian55** [comment]
#375, it is possible to keep track of [Target buffs durations](https://github.com/Xian55/WowClassicGrindBot#target-buff-remaining-time-requirements).

Be sure to use the Addon version: **1.6.3**

An example `KeyAction` look like this. For unlimited time buffs such as mount icon it will return `1` when its active, `0` when its not.

```json
  "IntVariables": {
      "TBuff_Mount": 3940790, // texture id
  },
  "Adhoc": {
    "Sequence": [
      {
        "Cost": 18,
        "Name": "MountUp",
        "Key": "N0", // replace with mount key
        "HasCastbar": true,
        "AfterCastWaitCastbar": true,
        "AfterCastWaitGCD": true,
        "Requirements": [
          "!Mounted",
          "TBuff_Mount > 0"
        ]
      }
    ]
  },
```

In order to obtain any kind of identifier i suggest to use [IdTip](https://www.curseforge.com/wow/addons/idtip) addon. 

Let me know if you ran into any issue 🙇 

![image](https://user-images.githubusercontent.com/367101/182704060-df3b3e70-63e2-4489-acbb-964d692c6ddc.png)

**Comment by adamssullivan** [comment]
Thank you. That works well. appreciate it. Thank you for the link for the addon also. That will be helpful.
