### ISSUE TITLE
when no food ,keep site for health add

### ISSUE THREAD

**Issue by jsRuner** [Xian55/WowClassicGrindBot#376]
**Is your feature request related to a problem? Please describe.**

i use rouge level60, player will dead  when no  food .

Whether it can be or not?    when nofood ,keep site for health add

There will always be not enough food  ,  Not every place can easy buy food

**Describe the solution you'd like**

when no food  and health low ,keep site.

Is this supported at present

**Describe alternatives you've considered**

**Additional context**

**Comment by Xian55** [comment]
Hey, just merged a new feature, #377. Should be able to create such requirement to cause waiting for hp reg.

Please look at the example shown in the [docs](https://github.com/Xian55/WowClassicGrindBot#wait-goals)

Let me know if you ran into any issue regarding this. 👋
