### ISSUE TITLE
Misc: Game settings file and parameter

### ISSUE THREAD

**Issue by coolzoom** [Xian55/WowClassicGrindBot#380]
Not a bug nor a feature request, just wish to record some of the game settings file and parameter I collected related to running the required bot, which might help someone or sometimes
Normally we could set it manually to match the requirements, 
by knowing the actual file and parameter we could copy-paste below into a specific file,
Or we could just initial some file templates and copy-paste them to a specific folder.
For the final best solution we could write a function or a script to loop through the game folder, find those files, check for matched lines and change them to the required parameter
Notes: Copy/Paste/Replace/Rewrite action has to done at game close state otherwise after you close the exe it will be overridden by the exe settings

# Graphic Settings

Required game client settings. Press `ESC` -> `System`
  * System > Advanced > Constrast: `50`
  * System > Advanced > Brightness: `50`
  * System > Advanced > Gamma from: `1.0`
  * System > Render Scale: `100%`
  * Disable Glow effect - type in the chat `/console ffxGlow 0`
  * To keep/save this settings make sure to properly shutdown the game.

 Related Game Settings file and reference parameter

```
- WTF\Config.WTF 

SET gxMaximize "0"
SET gxWindowedResolution "1024x768"
SET Contrast "50"
SET Brightness "50"
SET Gamma "1"
SET RenderScale "1"
SET ffxGlow "0"
```

# Interface Options
| Interface Option | Value |
| ---- | ---- |
| Controls - Auto Loot | &#9745; |
| Controls - Interact on Left click | &#9744; |
| Combat - Do Not Flash Screen at Low Health | &#9745; |
| Combat - Auto Self Cast | &#9745; |
| Names - NPC Names | &#9745; |
| Names - Enemy Units (V) | &#9744; |
| Camera - Auto-Follow Speed | **Fast** |
| Camera - Camera Following Style | **Always** |
| Mouse - Click-to-Move | &#9745; |
| Mouse - Click-to-Move Camera Style | **Always** |

 Related Game Settings file and reference parameter

- \WTF\Account\ACCOUNTNAME\config-cache.wtf
```
SET interactOnLeftClick "0" 
SET doNotFlashLowHealthWarning "1" 
SET UnitNameNPC "1" 
SET nameplateShowEnemies "0"  
SET autoInteract "1"  
SET cameraYawSmoothSpeed "270"
SET cameraSmoothStyle "2" 
SET cameraSmoothTrackingStyle "2" 

SET cameraDistanceMaxZoomFactor "1"
```
- \WTF\Account\ACCOUNTNAME\SERVERNAME\CHARNAME\config-cache.wtf
```
SET autoLootDefault "1"
SET autoSelfCast "1"  
```

# Required Key Bindings
`Targeting`:
| In-Game | Key | ClassConfiguration KeyAction Name | Desciption |
| ---- | ---- | ---- | ---- |
| Target Nearest Enemy | Tab | TargetNearestTargetKey | ---- |
| Target Pet | Multiply | TargetPetKey | Only pet based class |
| Target Last Target | G | TargetLastTargetKey | ---- |
| Interact With Target | I | InteractKey | ---- |
| Assist Target | F | TargetTargetOfTargetKey | ---- |
| Pet attack | Subtract | PetAttackKey | Only pet based class |
| Target Focus | PageUp | TargetFocusKey | Only for `"AssistFocus"` Mode |

Related Game Settings file and reference parameter
- \WTF\Account\ACCOUNTNAME\bindings-cache.wtf
```
bind PAGEUP FOCUSTARGET
bind TAB TARGETNEARESTENEMY
bind G TARGETPREVIOUSENEMY
bind NUMPADMULTIPLY TARGETPET
bind NUMPADMINUS PETATTACK
bind F ASSISTTARGET
bind PAGEUP FOCUSTARGET
bind I INTERACTTARGET
bind . INTERACTMOUSEOVER
```

**Comment by coolzoom** [comment]
Since it is not a bug or feature request, i think might just close it.
if someone who needs it can always search from the issues.

**Comment by Xian55** [comment]
Currently it is required to have an already running game client, before starting master of puppet can start initializing. 

Tampering any of the `*.wtf` files while the game is running is not recommended. 

By default those file were getting synced with blizzard servers, at any form the the previously mentioned files were getting corrupted or not properly saved or getting locked by anti virus. The game client just create a new one, throwing away the previous ones without even attempting to recover anything.

**Comment by coolzoom** [comment]
> Currently it is required to have an already running game client, before starting master of puppet can start initializing.
> 
> Tampering any of the `*.wtf` files while the game is running is not recommended.

yes have to do it before strat the game, maybe setting a game folder.

> By default those file were getting synced with blizzard servers, at any form the the previously mentioned files were getting corrupted or not properly saved or getting locked by anti virus. The game client just create a new one, throwing away the previous ones without even attempting to recover anything.

Interesting, so that means all my game settings will be lost? even most of I did manually?
So far I haven't seen such an issue, I modified a few lines manually though. maybe most of the time it works.

**Comment by jsRuner** [comment]
good，config  can  change  more better
