### ISSUE TITLE
No longer Skining

### ISSUE THREAD

**Issue by adamssullivan** [Xian55/WowClassicGrindBot#384]
### Description

After updating to the most current version I am no longer skining.

### Addon Version

1.6.31

### World of Warcraft Client

The Burning Crusade Classic

### Reproduction Steps

1. Enable skinning under the configuration menu or add skinning to the config file. My character is skipping skinning

### Logs

[out20220808_001.log](https://github.com/Xian55/WowClassicGrindBot/files/9284126/out20220808_001.log)

**Comment by Xian55** [comment]
Hi are you sure you using `1.6.31` at that version this kind of issue should not happen.

Based on the logs, `Could not find file 'C:\Users\Adam-Laptop1\Desktop\adam1\yumyum2\json\area\3703.json'.`

The most recent update is `1.7.0` where there was `breaking changes` regarding the `json` folder.

Be sure to check out #383 looking at the breaking changes, and how to adapt.

**Comment by Xian55** [comment]
Also i see that, there's is an issue loading the profile:
`Unexpected character encountered while parsing value: ;. Path 'Skin', line 8, position 14.`

Let me know if you unable to proceed.

**Comment by adamssullivan** [comment]
It looks like it was an issue with the Client addon communication. I restarted my wow client and it is working just fine. It was almost like it was running as keyboard-only maybe. The issue is resolved. Sorry for not doing that first. I will restart the wow client in the future first before posting a bug.

**Comment by Xian55** [comment]
Recently made lot of changes, even `breaking changes`.

Always trying to keep the integrity, but sometimes, just overlook stuff.

I'm glad you managed resolve the issue.  Feel free to reach out for help. 🙇
