### ISSUE TITLE
[Request] Fishing

### ISSUE THREAD

**Issue by adamssullivan** [Xian55/WowClassicGrindBot#385]
**Is your feature request related to a problem? Please describe.**
No problem. Just would like to AFK fish

**Describe the solution you'd like**
Catch fish

**Describe alternatives you've considered**
I have searched for the keyword fish. I was unable to find anything

**Comment by Xian55** [comment]
👋 Hello there! 

You right, there's no fishing functionality. I have not planned adding to it either. But maybe later, never know...

From my side, its going to be a low priority work item.

**Comment by adamssullivan** [comment]
Thanks for the info

**Comment by AsterNighT** [comment]
If you wouldn't mind installing another tool, [FishingFun](https://github.com/julianperrott/FishingFun) actually works well for me, just a few tweaks and calibration.

**Comment by adamssullivan** [comment]
I will have to give that a try thanks!
