### ISSUE TITLE
Mouse Click does not work

### ISSUE THREAD

**Issue by AsterNighT** [Xian55/WowClassicGrindBot#392]
### Description

Since some update the left click and right clicks have been failing. It could move the mouse to proper position but cannot click.

### Addon Version

latest on dev

### World of Warcraft Client

The Burning Crusade Classic

### Reproduction Steps

1. Start the bot
2. Watch it fail to click on enemy and loot

### Last Good Version

At least it is good before the herb update. I would do a binary search if necessary.

### Logs

[out20220814.log](https://github.com/Xian55/WowClassicGrindBot/files/9333501/out20220814.log)

**Comment by Xian55** [comment]
Hello there 👋 !

If you truly using the latest addon version,, please look at #388.

**Comment by AsterNighT** [comment]
oops, that's a breaking change I missed. Would try this tonight.

**Comment by AsterNighT** [comment]
Work like a charm. Thank you for your time.
