### ISSUE TITLE
Index was outside the bounds of the array error while looting

### ISSUE THREAD

**Issue by AsterNighT** [Xian55/WowClassicGrindBot#393]
### Description

The bot occasionally crash when looting/skinning. This mainly occurs when there are two or more corpse in screen. Sorry but I cannot find a way to reproduce the crash solidly.
I don't know if it is relevant but I notice for this crash the bot herb a mob but the herb itself failed (due to insufficient herb level).

### Addon Version

latest on dev, ff7f59d47d051d94abe9a0111c19eea64fc31c8c

### World of Warcraft Client

The Burning Crusade Classic

### Reproduction Steps

1. Kill some mobs, more likely to trigger this if multiple corpse in screen.
2. Wait until the bot crashed while looting.

### Last Good Version

I don't remember any version refraining this crash

### Logs

The final error log is printed in BlazorServer terminal, but not in the `.log` file. I copy that to the log file attached
[out20220815.log](https://github.com/Xian55/WowClassicGrindBot/files/9337494/out20220815.log)

**Comment by Xian55** [comment]
Hello there 👋 

The crash happens when the preallocated array is not enough to suit the npc name coverage on the screen.

You can reproduce it by zooming in with your camera to the npc name to cover huge part of the screen. 

A quick fix atm is to reduce the `64` here. to like `32` or `16`. Both for width and height.
https://github.com/Xian55/WowClassicGrindBot/blob/ff7f59d47d051d94abe9a0111c19eea64fc31c8c/SharedLib/NpcFinder/NpcNameFinder.cs#L522

**Comment by AsterNighT** [comment]
I haven't run into this crash since the fix, but neither can I confirm it can be fixed since I cannot reproduce this issue even before the fix. I will close this issue and reopen it if this should occur once more.

**Comment by Xian55** [comment]
Planning to do more sophisticated fix in the near future. 😅

**Comment by AsterNighT** [comment]
Seems that I met this once more. Check this.

[0827.log](https://github.com/Xian55/WowClassicGrindBot/files/9437174/0827.log)

**Comment by Xian55** [comment]
Hey this one is different. Theres a typo in npcCount vs NpcCount

**Comment by AsterNighT** [comment]
Ugh, so is it fixed or should I post it in another issue?

**Comment by Xian55** [comment]
> Seems that I met this once more. Check this.
> 
> [0827.log](https://github.com/Xian55/WowClassicGrindBot/files/9437174/0827.log)

This issue is different. You can make a new issue if you like. Im not nearby to my workstation. Fix eta end of day.

**Comment by Xian55** [comment]
Should be fixed after https://github.com/Xian55/WowClassicGrindBot/commit/29de2e7c6beb4aacc02d118d120799a3e3dde040
