### ISSUE TITLE
[Bug] After leaving combat. CombatLog(DamageTaken, DamageDone) still getting populated making player stuck forever. 

### ISSUE THREAD

**Issue by jsRuner** [Xian55/WowClassicGrindBot#412]
**Is your feature request related to a problem? Please describe.**

The current logic relies on the combat log. Once the information is missing, the character will be stuck. For example, standing there without any action

**Describe the solution you'd like**

when No movement for more than 2 minutes and  not in combat  , auto  reload  game  ,it  can  solve 90% problem

**Describe alternatives you've considered**

**Additional context**

**Comment by jsRuner** [comment]
damagedone   、damagetaken 、producedcorpse    Three variables  Easy to appear   ,  they no clear , cause player   No action after  combat

**Comment by Xian55** [comment]
Hey, can you give more information what's going on?

> The current logic relies on the combat log. Once the information is missing, the character will be stuck.

Please upload a logfile which contains the mentioned issue, for further investigation. **Do not** cherry pick the log entries, upload the whole file to have better understanding what's going on. 🙇

**Comment by jsRuner** [comment]
You have a queue. You update the queue through the guid in the combat log. However, sometimes the combat is over and the queue still has data

**Comment by jsRuner** [comment]
I will provide the log later

**Comment by Xian55** [comment]
May i ask what's you in-game frame rate(FPS) while using Master of Pupper?

**Comment by jsRuner** [comment]
fps is   28 -32

**Comment by Xian55** [comment]
After many attempt, i was unable to reproduce the issue on its own. Need context about how you end up to that stuck state, and what prior action you took.

Logs would be appreciated 🙇

**Comment by AsterNighT** [comment]
Well I know this issue, met it myself a few times. I would post logs here should it occur again.

**Comment by jsRuner** [comment]
It's not easy to appear recently. Close or wait for feedback from others  。 @AsterNighT  can you  give log ?

**Comment by Xian55** [comment]
Can you share the [class profile](https://github.com/Xian55/WowClassicGrindBot/tree/dev/Json/class) while you encountered the issue?

**Comment by rozv11e** [comment]
I had a similar problem, reinstallation and full reconfiguration did not help, the addon also reinstalled, perhaps after any settings of buttons or binds

**Comment by Xian55** [comment]
Hello there, i require logs in order to investigate, please upload the log file, drag and drop into the comment.

**Comment by rozv11e** [comment]
where to drop?

**Comment by Xian55** [comment]
![image](https://user-images.githubusercontent.com/367101/188897937-13aff817-5939-4e14-a524-3ea5cf09b6bb.png)

**Comment by rozv11e** [comment]
[out20220907.log](https://github.com/Xian55/WowClassicGrindBot/files/9506848/out20220907.log)

**Comment by Xian55** [comment]
At first glance didn't not spotted any issue which could be related to this of being stuck after combat.

Seems like an another issue.

Where your `Del1` named KeyAction has no visible requirement, so it attempts to execute every time?

i recommend to try out the following profile `Json\class\Druid_20_cat_bear.json`

or delete this one from the `Druid_cat.json`

```json
      {
        "Name": "Del1",
        "Key": "F5",
        "Cooldown": 120000
      }
```

**Comment by rozv11e** [comment]
What is it key? Del1

**Comment by Xian55** [comment]
Not sure what you are asking, can you elaborate a little bit further?

**Comment by rozv11e** [comment]
I don't understand what these abilities are: "del1"

**Comment by rozv11e** [comment]
[out20220908_002.log](https://github.com/Xian55/WowClassicGrindBot/files/9526435/out20220908_002.log)
stuck after fight

**Comment by rozv11e** [comment]
he stopped running any way and stucks

**Comment by Xian55** [comment]
Gooday, based on the log you provided, there are couple of issues, but none of them seems to related to the specific case of being stuck after combat.

Inspecting the log, each combat goal follows a consume corpse, loot goal, then a follow route finally and the stuck it self happens in FollowRouteGoal. Section indicates, that the navigation system was unable to calculate a path back to the waypoints.

```
2022-09-08 14:34:42.375 +03:00 [WRN] New Plan= NO PLAN
2022-09-08 14:34:42.849 +03:00 [INF] New Plan=  Follow Route
2022-09-08 14:34:42.850 +03:00 [INF] [LocalPathingApi] distance from nearlest point is 53.72611. Have to clear RouteToWaypoint.
2022-09-08 14:34:42.928 +03:00 [INF] [NpcNameFinder] type = None
2022-09-08 14:34:42.991 +03:00 [INF] Pathfinder - 207.82347 - <-2235,5164  5057,6416  -3,6620483> -> <-2440  5020,533  0> 91.2633ms
2022-09-08 14:34:46.963 +03:00 [INF] Unstuck by turning for 142ms
2022-09-08 14:34:47.133 +03:00 [INF] Unstuck by moving for 1069ms
2022-09-08 14:34:50.849 +03:00 [INF] Unstuck by turning for 280ms
2022-09-08 14:34:51.164 +03:00 [INF] Unstuck by moving for 1270ms
2022-09-08 14:34:53.962 +03:00 [INF] Clear route to waypoint! Stucked for 10016.2907ms
2022-09-08 14:34:54.197 +03:00 [INF] Pathfinder - 211.68132 - <-2232,5176  5062,486  -9,951755> -> <-2440  5020,533  0> 71.9163ms
2022-09-08 14:34:57.366 +03:00 [INF] Unstuck by turning for 131ms
2022-09-08 14:34:57.542 +03:00 [INF] Unstuck by moving for 1561ms
```

**Comment by rozv11e** [comment]
What could be the problem?

**Comment by Xian55** [comment]
That's all i can say based on the provided logs.

If your issue still persist, please open a new issue about it.

**Comment by rozv11e** [comment]
after resetting the keybindings stopped getting stuck

**Comment by rozv11e** [comment]
[out20220913_503.log](https://github.com/Xian55/WowClassicGrindBot/files/9559776/out20220913_503.log)

**Comment by Xian55** [comment]
Going to look at it, when i have some free time!

**Comment by Xian55** [comment]
> [out20220913_503.log](https://github.com/Xian55/WowClassicGrindBot/files/9559776/out20220913_503.log)

I've seen you had many troubles with the paladin_66 profile in general, i did some tidy up for the class, and made a wrath ready [70 lvl paladin profile](https://github.com/Xian55/WowClassicGrindBot/blob/dev/Json/class/Paladin_70_Retribution.json)

---

On the other hand, not sure the the other issues, related to this issues,

**1,**
I'm aware that, on `_pack\60-70\Terokkar Forest\62-64.json` has a point where the pathfinder is unable to find a valid spot
```
2022-09-13 21:15:40.287 +03:00 [WRN] search failed, 10 seconds since last progress, returning the closest spot.
```

**2,**
```
2022-09-13 21:15:47.927 +03:00 [INF] ----- Corpse consumed. Total: 0 | Remaining: 0
2022-09-13 21:15:47.942 +03:00 [INF] New Plan=  Follow Route
2022-09-13 21:15:48.022 +03:00 [INF] [NpcNameFinder] type = None
2022-09-13 21:15:52.995 +03:00 [INF] FollowRouteGoal: Random jump
2022-09-13 21:15:57.943 +03:00 [WRN] search failed, 10 seconds since last progress, returning the closest spot.
2022-09-13 21:16:03.214 +03:00 [INF] FollowRouteGoal: Random jump
2022-09-13 21:16:07.884 +03:00 [INF] FollowRouteGoal: Has target but its dead.
2022-09-13 21:16:07.982 +03:00 [WRN] search failed, 10 seconds since last progress, returning the closest spot.
2022-09-13 21:16:08.102 +03:00 [INF] FollowRouteGoal: Has target but its dead.
2022-09-13 21:16:08.244 +03:00 [INF] FollowRouteGoal: Has target but its dead.
2022-09-13 21:16:08.388 +03:00 [INF] FollowRouteGoal: Has target but its dead.
```
About this one, its like after loot, somehow the current target doesn't get cleared.

**Comment by rozv11e** [comment]
2. why is that? also noticed this

**Comment by Xian55** [comment]
Hi most likely the FollowRouteGoal, targeting thread starts to early, and stuck in that state, as it does not clear target. Going to look into it, so time later

**Comment by rozv11e** [comment]
he also does not use a mount, please see

**Comment by Xian55** [comment]
Be sure to enable in the class profile

```json
{
"UseMount": true,
"MountKey": "N0" // or "N1"
....
```

**Comment by rozv11e** [comment]
it's on but he's not using it, can send log

**Comment by rozv11e** [comment]
[out20220914_002.log](https://github.com/Xian55/WowClassicGrindBot/files/9569498/out20220914_002.log)

and he doesn't use Judgement in the new class json file

**Comment by Xian55** [comment]
Be sure to [update ](https://github.com/Xian55/WowClassicGrindBot#5-blazorserver-configuration-process) everything,
Pull down the repo, [git recommended to keep up to date](https://rogerdudler.github.io/git-guide/)
Update the addon via BlazorServer.
Current addon version is 
```css
## Version: 1.7.20
```

**Comment by rozv11e** [comment]
class works well, thanks! Why doesn't the mount work?

**Comment by rozv11e** [comment]
1. Changed the call button of the mount, he started to use it, maybe over time a bug appears and he just stops using it
 2. If the next target is right in front of him, and he is fighting, then he does not loot it, but runs to the next target
 3. There was a problem with the blacklist, he selects a target from the blacklist to the target and runs straight (at the end of the log)
[out20220915_007.log](https://github.com/Xian55/WowClassicGrindBot/files/9570496/out20220915_007.log)

**Comment by Xian55** [comment]
I would like to ask you kindly, only post [here](https://github.com/Xian55/WowClassicGrindBot/issues/412) if you came across an issue which is related to the title, which is plain and well descriptive.

Other then that, open a [new bug report](https://github.com/Xian55/WowClassicGrindBot/issues/new?assignees=&labels=bug&template=bug_report.yml) and fill the form as much you can in order to provide a clear sight about the issue, others can benefit once they attempt to search for a specific problem.

Finally please be sure to to read [documentation](https://github.com/Xian55/WowClassicGrindBot#readme), if you are opt-in using the [default profiles](https://github.com/Xian55/WowClassicGrindBot/tree/dev/Json), you have to use the recommended settings, key bindings, input language.

**Comment by Xian55** [comment]
Personally i was unable to reproduce the mentioned issue after many attempts, based on the logics 
https://github.com/Xian55/WowClassicGrindBot/commit/5f2390ef30d7d2e4c182c57a0841604e193c46d1 should eliminate the issue.
