### ISSUE TITLE
Dismounts to cast Crusader Aura

### ISSUE THREAD

**Issue by adamssullivan** [Xian55/WowClassicGrindBot#413]
### Description

After mounting I want to cast Crusader Aura, Crusader can be cast while on a mount

### Addon Version

1.7.17

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

When the character mounts it will then dismount to cast Crusader Aura. 
{
        "Name": "Crusader Aura",
        "Key": "N9",
        "Requirements": [
		  "Mounted",
          "!Form:Paladin_Crusader_Aura"
        ],
		"AfterCastWaitBuff": true
      },

### Last Good Version

n/a

### Logs

[out20220830.log](https://github.com/Xian55/WowClassicGrindBot/files/9456902/out20220830.log)

**Comment by AsterNighT** [comment]
Hey, I think I can help with this.

**Comment by Xian55** [comment]
Hey #414 just merged to dev, thanks to @AsterNighT. Should be able to specify `BeforeCastDismount` for the KeyAction.

```json
{
  "Name": "Crusader Aura",
  "Key": "N9",
  "Requirements": [
    "Mounted",
    "!Form:Paladin_Crusader_Aura"
  ],
  "BeforeCastDismount": false,
  "AfterCastWaitBuff": true
},
```

**Comment by adamssullivan** [comment]
Thanks!
