### ISSUE TITLE
add  config for   Don't attack  Horde or  Alliance

### ISSUE THREAD

**Issue by jsRuner** [Xian55/WowClassicGrindBot#426]
**Is your feature request related to a problem? Please describe.**

add  config for   Don't attack  Horde or  Alliance

Would like to add this switch item

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Xian55** [comment]
Hello there,

With the current design, every opposite faction player and its pet supposed to be in the Blacklist.

In the last couple of days, i was doing some farm, where i had an issue, despite the fact should not attack opposite faction players, it happened multiple times, thus not working as intended. So  at current state its more of a bug.
