### ISSUE TITLE
lvl 70-80 grinding paths

### ISSUE THREAD

**Issue by dotaku22** [Xian55/WowClassicGrindBot#429]
Hi,

lvl 70-80 grinding paths would be neat (can only find for 1-70), I really suck at making them myself/don't know good spots.

**Comment by Xian55** [comment]
Hello there. 👋 

* Do you have any issue recording/altering [routes](https://github.com/Xian55/WowClassicGrindBot#recording-a-new-path) ? 
* Does the related documentation lack information, so it is unclear how to use the tool ?

---

Farm routes and class profile contributions always appreciated.
