### ISSUE TITLE
add http interfaces 

### ISSUE THREAD

**Issue by jsRuner** [Xian55/WowClassicGrindBot#430]
**Is your feature request related to a problem? Please describe.**

Can you add some http interfaces? For example, simply start, stop, and load configurations. The purpose is to  use other languages to drive it. I'm a python enthusiast and do not konw  #

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Xian55** [comment]
Hello there 👋 

The described requirements are already implemented in [HeadlessServer](https://github.com/Xian55/WowClassicGrindBot/tree/dev/HeadlessServer):
- start / stop application
- Load Class Configuration

I suggest to try that out, you should be able to interface with it via the [command line](https://github.com/Xian55/WowClassicGrindBot#7-optional---running-headlessserver).

**Comment by Xian55** [comment]
Did you had time to look at HeadlessServer ?
