### ISSUE TITLE
Known issue: After pressing `Init State` button unable to execute flush command.

### ISSUE THREAD

**Issue by Phatlynx** [Xian55/WowClassicGrindBot#440]
### Description

I have 4 Frostweave bags, in Swag it is only able to detect 1 of them thus causing BagFull requirement to trigger the Player action to NPC: Sell when bags aren't full. 

I tried looking in the DataToColor.lua with GetContainerNumFreeSlots but I can't make sense of it. 

### Addon Version

Current Verison

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

N/A

### Last Good Version

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/67671220/195630931-009003b2-81d5-431b-8263-2dc91c0eb1cc.png)

**Comment by Xian55** [comment]
Hello there!

You have to press `Init State` first, in order to initialize available Bags/Actionbars/Spells/Talents.

You can validate the gathered data by following this [guidance](https://github.com/Xian55/WowClassicGrindBot/wiki/Validating-FrameConfiguration)

**Comment by Phatlynx** [comment]
Hey! I have clicked Initiate every time I start or restart the server. The issue still persists.

**Comment by Phatlynx** [comment]
I have found a workaround, if I place 1 item into every bag, the bot will then detect all 4. Issue only exists if any of the bags are empty. 
![image](https://user-images.githubusercontent.com/67671220/195645202-60cc915b-a342-4b5c-a85e-b18550a1a8d1.png)

**Comment by Xian55** [comment]
By any chance are you run as Administrator either `BlazorServer` or the `World of Warcraft` client ?

**Comment by Phatlynx** [comment]
> 

Yes, they're running with admin privileges.

**Comment by Xian55** [comment]
I recommend to run both **without** admin privileges, as `BlazorServer` unable to send certain keystroke event to the game client. Thus preventing working it properly.

**Comment by Phatlynx** [comment]
Sorry if I'm not well versed in this topic. Do you mean log out of my administrator windows account and create a guest user?

**Comment by Xian55** [comment]
> Do you mean log out of my administrator windows account and create a guest user?

No, that's not necessary. 

Just be sure to that, the 
* World of Warcraft client
* Visual Studio / BlazorServer
* Command line

Are running with the default `Compatibility` settings. Like shown in the image.
![image](https://user-images.githubusercontent.com/367101/195650006-e94725cc-4dea-48a8-99fc-e26f295220e3.png)

If that is seems to be correct, you haven't changed anything. There's an alternative approach.

---

While the BlazorServer is running, navigate to the `Addon Config` tab, and see what the `FlushCommand` is. Copy that string, switch to the game, and type in chat, `/<your_addon_name>flush` example `/datatocolorflush` this should be the proper workaround.

 This is what the `Init State` button meant to do, copy this string, paste it into the chat, and press enter. However from some reason at your side, unable to send these keystrokes to the game client. I've encountered this kind of issue before, when i ran mixed privileges with the game client and the BlazorServer.

---

Or just simply type in chat `/reload`, this method entirely eliminates the use of `Init State` button.

**Comment by Phatlynx** [comment]
The administrator Compatibility settings are default and the same as the screenshot. 

The /<your_addon_name>flush worked. 
![image](https://user-images.githubusercontent.com/67671220/195678568-fb307948-957d-46b6-bd76-9b1669c52569.png)
