### ISSUE TITLE
Discord server?

### ISSUE THREAD

**Issue by KayleMine** [Xian55/WowClassicGrindBot#441]
## As in title, maybe you make an "official" discord serv. to let users  share profiles and etc?

**Comment by Xian55** [comment]
Hello there 👋 

Currently GitHub has all the capabilities to host and share those profiles already.

As it stated in the readme, contribution related to class and path profiles are always welcomed, few examples https://github.com/Xian55/WowClassicGrindBot/pull/62 and https://github.com/Xian55/WowClassicGrindBot/pull/131. There are plenty of existing examples of [class profiles](https://github.com/Xian55/WowClassicGrindBot/tree/dev/Json/class) which should give a strong foundation to build on.

In my humble opinion, Discord server does not help at sharing profiles among everyone as those who are not joined the community missing these _rogue files_, which would probably never end up in the version control, sooner or later getting out of date, and only cause trouble and confusion in the long run.

The only convenience it brings is instant messaging. However for me, GitHub issues seems a more reliable way to have a ticketing system, that way when somebody encounters a problem going to have an easier time to look up [existing issues](https://github.com/Xian55/WowClassicGrindBot/issues). 

There are templates to fill, this way can already categorize the issues. While discord you can have a more relaxed discussion which leads a less organized way to keep track of things. On the other hand i would avoid having two ticketing system, while GitHub works well for this this soul purpose.

There are few contributors whom showed interest about improving the project for them there's a Discord server, but not for the purpose of providing support for the mass audience and certainly not for sharing _rogue files_. 

If you would like to contribute you can always create a fork and make a [pull request](https://github.com/Xian55/WowClassicGrindBot/pulls). For me, this seems a more organic way to create a community who's happy to consume but also willing to share its creation while everyone can benefit.

🙇
