### ISSUE TITLE
Path Editor does not showing up

### ISSUE THREAD

**Issue by Phatlynx** [Xian55/WowClassicGrindBot#442]
### Description

How come I do not have this option?

### Addon Version

Current Verison

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

N/A

### Last Good Version

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/67671220/196058886-ee7d5246-5581-4799-b0f1-58eec6f61023.png)

**Comment by Xian55** [comment]
Hey you have to load the class profile first, in order to that to appear.

**Comment by Phatlynx** [comment]
Ah okay thank you.
