### ISSUE TITLE
Hi is currently working on wotlk classic? 

### ISSUE THREAD

**Issue by exwysh** [Xian55/WowClassicGrindBot#448]
**Is your feature request related to a problem? Please describe.**
Hi is currently working on wotlk classic? i'v tryed using the path tracer but wasn t working i write c# theres a way i can get in touch?

**Comment by Xian55** [comment]
Hello there! 

> Is currently working on wotlk classic?

Yes, it should work on wrath of the lich king classic. Please follow the general setup guide on the [front page](https://github.com/Xian55/WowClassicGrindBot#readme) where you can find the documentation about the requirement, setup and how to start.

As long as you can describe your problem in detail, we can provide support.
