### ISSUE TITLE
Evading mobs causing pathing to get stuck at one location while trying to vendor/repair in K3, Storm Peaks

### ISSUE THREAD

**Issue by Phatlynx** [Xian55/WowClassicGrindBot#466]

**Comment by Xian55** [comment]
Hello there. 👋 

If i recall correctly i extracted the [target miss type](https://github.com/Xian55/WowClassicGrindBot/blob/dev/Core/AddonComponent/MissType.cs) so the evade data should be there for the backend.

Just have to write some logic to handle this special case for evading. i will look into it.

If you could share the in game coordinates i might be able to reproduce it. Finding these mobs is not that easy.

**Comment by Phatlynx** [comment]
(39.0, 85.7), Storm Peaks

**Comment by Xian55** [comment]
After #473 should no longer stuck on the evading target.
