### ISSUE TITLE
Error building project on .net sdk 7.0

### ISSUE THREAD

**Issue by rozv11e** [Xian55/WowClassicGrindBot#467]
### Description

built using powershell and visual studio, asks for the previous version

### Addon Version

.net 7.0

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

1. Installed the folder with the bot using git
2. Added MPQ files
3. tried to build the solution with powershell
4. Newtonsoft.Json packages and other non-registered versions of .net 7.0
5. error NU1101 and NU1102

**Comment by Xian55** [comment]
Hi be sure to
* Install the respected [dotnet 7 sdk](https://dotnet.microsoft.com/download/dotnet/7.0) x86 and or x64

Then run the following commands in powershell
* [`dotnet restore`](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-restore) command to resolve the new packages
* `dotnet build --configuration Release --arch x86`

**Comment by rozv11e** [comment]
Errors when building:\WowClassicGrindBot\PathingAPI\PathingAPI.csproj : error NU1102: Could not find package Newtonsoft.Json with version (>=
 13.0.2) [C:\WowClassicGrindBot\MasterOfPuppets.sln]
C:\WowClassicGrindBot\PathingAPI\PathingAPI.csproj : error NU1102: - Found in Microsoft Visual Studio Offline Packages
Several versions already down (1) [ Latest version: 9.0.1 ] [C:\WowClassicGrindBot\MasterOfPuppets.sln] and so on

Did what you said, 
same mistakes

**Comment by ray-0000** [comment]
net7 seems to only be built under win10, win7 does not support

**Comment by Xian55** [comment]
> net7 seems to only be built under win10, win7 does not support

Related changes 
https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md#support-changes-from-net-60

**Comment by ray-0000** [comment]
Yes, rozv11e is probably using win7 so build error

**Comment by Xian55** [comment]
> net7 seems to only be built under win10, win7 does not support
> 
> Related changes
> https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md#support-changes-from-net-60

That was an oversight on my part.

Nonetheless for me the gained benefits overweight the losses in this regard.

If you wish to keep use `win 7 / win 8.1` os, you have the option to roll back until 03ffcedee85fe3a83ba386336cccedc2ec5f471e

**Comment by rozv11e** [comment]
Used win10

**Comment by rozv11e** [comment]
oh sorry, I lost the source of the packages, I just noticed it now
the problem was that)))
