### ISSUE TITLE
[SoM] after start casting lua errors prevents looting

### ISSUE THREAD

**Issue by Obrenov** [Xian55/WowClassicGrindBot#468]
### Description

I was running a bot for a bit, and i noticed when he kills a mob and the mob dies next to him, he wont loot it, even if the mob died in some range, he wont even go up to the mob to try to loot it or whatever. Im fighting only 1 mob, keyboardmode is off, and looting is on. i even tried with consumingcorpse on and salvage, but still wont work.

### Addon Version

.net 7.0

### World of Warcraft Client

Season of Mastery

### Reproduction Steps

Starting the bot, letting it do his own thing, when killing mob wont loot.

### Logs

New Plan=  Consume Corpse
[18:52:55:861 INF] ----- Safe to consume a corpse.
[18:52:55:862 INF] New Plan=  Loot
[18:52:55:926 INF] LootGoal: Should gather 705 ? False
[18:52:55:927 INF] LootGoal: Target Last Target Found!
[18:52:59:014 INF] LootGoal: Loot Failed after 3004,5035ms
[18:52:59:073 INF] New Plan=  Corpse Consumed
[18:52:59:074 INF] ----- Corpse consumed. Total: 0 | Remaining: 0

**Comment by Xian55** [comment]
In order to **GatherCorpse**(Herb, Skinning, Salvage) feature work at all, the a successfully detected Loot is requisite.

---

Please upload the related log files in order to conduct more in depth investigation 🙇 

The related log files can be found the following locations
- `WowClassicGrindBot\BlazorServer\`
- `WowClassicGrindBot\BlazorServer\bin\Release\net7.0`
- `WowClassicGrindBot\BlazorServer\bin\x64\Release\net7.0`
- `WowClassicGrindBot\BlazorServer\bin\x86\Release\net7.0`

example file format: `out20221129.log`

**Comment by Xian55** [comment]
i need more detailed info which can be found in the logs. Please upload them 🙇

**Comment by Xian55** [comment]
Just noticed an issue #469 already in `dev` branch.

Let me know if you notice any change after defb54b6e2127e5e0e73be0878f116b75e04bc20

Be sure to use addon version: `1.7.31`. To how to update the addon [check out](https://github.com/Xian55/WowClassicGrindBot#5-blazorserver-configuration-process).

**Comment by Obrenov** [comment]
Sorry for late answer, here is my log.
[out20221129_014.log](https://github.com/Xian55/WowClassicGrindBot/files/10116609/out20221129_014.log)
Even after updating said addons, its still wont loot the moob, even when i turn everything back to normal.

**Comment by Xian55** [comment]
Does loot worked in prior, for you?

Based on the provided logs, it seems all of your looting attempt fails, consistently.

Are you sure you have followed the related setup guides
* https://github.com/Xian55/WowClassicGrindBot#8-configure-the-wow-client---interface-options
* https://github.com/Xian55/WowClassicGrindBot#9-configure-the-wow-client---key-bindings

---

Please enable in game to show lua errors. Type this in chat `/console scriptErrors 1`

**Comment by Obrenov** [comment]
Loot didnt work, and keybinding were okay, but when i updated addons it started working after a few tries. Now everything is okay. Thank you

**Comment by Xian55** [comment]
The `Hunter_1.json` profile is a bit rough in SoM client as it behaves a bit differently compare to TBC and Wrath client.

I recommend to use this profile temporary. The only adjustments about the Pull Auto shot. Should help prevent often interrupting the Auto shots.
```
"BeforeCastStop": true,
"AfterCastWaitCombat": true,
```
---
```json
{
  "ClassName": "Hunter",
  "PathFilename": "1_Gnome.json",
  "Pull": {
    "Sequence": [
      {
        "Name": "Auto Shot",
        "Key": "3",
        "BeforeCastStop": true,
        "AfterCastWaitCombat": true,
        "Item": true,
        "Requirements": [
          "HasRangedWeapon",
          "!InMeleeRange",
          "!AutoShot",
          "HasAmmo"
        ]
      }
    ]
  },
  "Combat": {
    "Sequence": [
      {
        "Name": "Auto Shot",
        "Key": "3",
        "Item": true,
        "BeforeCastStop": true,
        "Requirements": [
          "HasRangedWeapon",
          "!InMeleeRange",
          "!AutoShot",
          "HasAmmo"
        ]
      },
      {
        "Name": "Raptor Strike",
        "Key": "4",
        "WhenUsable": true,
        "AfterCastWaitSwing": true,
        "Requirements": [
          "MainHandSwing > -400",
          "InMeleeRange",
          "!AutoShot"
        ]
      },
      {
        "Name": "AutoAttack",
        "Requirements": [
          "InMeleeRange",
          "!AutoAttacking"
        ]
      },
      {
        "Name": "Approach",
        "Requirements": [
          "InMeleeRange"
        ]
      }
    ]
  },
  "NPC": {
    "Sequence": [
      {
        "Cost": 6,
        "Name": "Repair",
        "Key": "C",
        "Requirement": "Durability% < 35",
        "PathFilename": "1_Gnome_Vendor.json"
      },
      {
        "Cost": 6,
        "Name": "Sell",
        "Key": "C",
        "Requirements": [
          "BagFull",
          "BagGreyItem"
        ],
        "PathFilename": "1_Gnome_Vendor.json"
      }
    ]
  }
}
```
