### ISSUE TITLE
Addon error

### ISSUE THREAD

**Issue by Adrinalin4ik** [Xian55/WowClassicGrindBot#47]
Hi, I've just pulled your main branch, resetup the bot, and got an error in wow. Also it seems like most of the conditions not working, I think this error the reason why.

Message: Interface\AddOns\WAB\WAB.lua:756: attempt to compare number with boolean
Time: Fri May 14 19:06:03 2021
Count: 8379
Stack: Interface\AddOns\WAB\WAB.lua:756: attempt to compare number with boolean
Interface\AddOns\WAB\WAB.lua:756: in function `MakeIndexBase2'
Interface\AddOns\WAB\WAB.lua:597: in function `Base2Converter'
Interface\AddOns\WAB\WAB.lua:381: in function <Interface\AddOns\WAB\WAB.lua:346>
Interface\AddOns\WAB\WAB.lua:566: in function <Interface\AddOns\WAB\WAB.lua:566>

Locals: self = <table> {
 IsPetVisible = <function> defined @Interface\AddOns\WAB\WAB.lua:1460
 Base2Converter = <function> defined @Interface\AddOns\WAB\WAB.lua:583
 returnItemFromIndex = <function> defined @Interface\AddOns\WAB\WAB.lua:978
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\WAB\Libs\AceTimer-3.0\AceTimer-3.0.lua:147
 getManaMax = <function> defined @Interface\AddOns\WAB\WAB.lua:816
 getGuidFromUUID = <function> defined @Interface\AddOns\WAB\WAB.lua:886
 CastingInfoSpellId = <function> defined @Interface\AddOns\WAB\WAB.lua:779
 GameTime = <function> defined @Interface\AddOns\WAB\WAB.lua:1157
 deadOrAlive = <function> defined @Interface\AddOns\WAB\WAB.lua:1305
 GetDebuffs = <function> defined @Interface\AddOns\WAB\WAB.lua:1120
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\WAB\Libs\AceAddon-3.0\AceAddon-3.0.lua:440
 IsEnabled = <function> defined @Interface\AddOns\WAB\Libs\AceAddon-3.0\AceAddon-3.0.lua:482
 ScheduleTimer = <function> defined @Interface\AddOns\WAB\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 IsCurrentActionOn = <function> defined @Interface\AddOns\WAB\WAB.lua:1453
 getHealthCurrent = <function> defined @Interface\AddOns\WAB\WAB.lua:810
 getTargetLevel = <function> defined @Interface\AddOns\WAB\WAB.lua:832
 RegisterMessage = <function> defined @Interface\AddOns\WAB\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 UnregisterMessage = <function> defined @Interface\AddOns\WAB\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 getUnitXPMax = <function> defined @Interface\AddOns\WAB\WAB.lua:799
 IsTargetOfTargetPlayerAsNumber = <function> defined @Interface\AddOns\WAB\WAB.lua:1413
 SendCommMessage = <function> defined @Interface\AddOns\WAB\Libs\AceComm-3.0\AceComm-3.0.lua:87
 OnMerchantShow = <function> defined @Interface\AddOns\WAB\WAB.lua:196
 actionbarCost = <function> defined @Interface\AddOns\WAB\WAB.lua:912
 UnregisterAllComm = <function> defined @Interface\AddOns\WAB\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 SetEnabledState = <function> defined @Interface\AddOns\WAB\Libs\AceAddon-3.0\AceAddon-3.0.lua:455
 delete = <function> defined @Interface\AddOns\WAB\WAB.lua:657
 getRange = <function> defined @Interface\AddOns\WAB\WAB.lua:858
 hearthZoneID = <function> defined @Interface\AddOns\WAB\WAB.lua:1509
 uniqueGuid = <function> defined @Interface\AddOns\WAB\WAB.lua:891
 sell = <function> defined @Interface\AddOns\WAB\WAB.lua:673
 itemInfo = <function> defined @Interface\AddOns\WAB\WAB.lua:964
 targetHostile = <function> defined @Interface\AddOns\WAB\WAB.lua:841
 shapeshiftForm = <function> defined @Interface\AddOns\WAB\WAB.lua:1322
 OnInitialize = <function> defined @Interface\AddOns\WAB\WAB.lua:283
 UnregisterAllEvents = <function> defined @Interface\AddOns\WAB\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 targetNpcId = <function> defined @Interface\AddOns\WAB\WAB.lua:870
 Deserialize = <function> defined @Interface\AddOns\WAB\Libs\AceSerializer-3.0\AceSerializer-3.0.lua:246
 MakeIndexBase2 = <function> defined @Interface\AddOns\WAB\WAB.lua:755
 RepairItems = <function> defined @Interface\AddOns\WAB\WAB.lua:1566
 GetName = <function> defined @Interface\AddOns\WAB\Libs\AceAddon-3.0\AceAddon-3.0.lua:310
 name = "AceConsole-3.0"
 Disable = <function> defined @Interface\AddOns\WAB\Libs\AceAddon-3.0\AceAddon-3.0.lua:345
 GetCurrentPlayerPosition = <function> defined @Interface\AddOns\WAB\WAB.lua:570
 GetEnemyStatus = <function> defined @Interface\AddOns\

**Comment by Xian55** [comment]
There's no such thing as `Interface\AddOns\WAB\WAB.lua`.

**Comment by Xian55** [comment]
On the other hand please use 
https://github.com/Xian55/WowClassicGrindBot#5-configuration-process

**Comment by Adrinalin4ik** [comment]
I renamed your addon during setting up

**Comment by Xian55** [comment]
Make sure the addon version is `1.0.9`

**Comment by Adrinalin4ik** [comment]
Yes, it's 1.0.9, I've checked it in the wow addon folder in the toc file.

**Comment by Adrinalin4ik** [comment]
This code thow an error
```lua
-- Returns bitmask values.
-- MakeIndexBase2(true, 4) --> returns 16
-- MakeIndexBase2(false, 9) --> returns 0
function WAB:MakeIndexBase2(bool, power)
    if bool ~= nil and bool > 0 then
        return math.pow(2, power)
    else return 0
    end
end
```

**Comment by Xian55** [comment]
ye you right, one moment!

**Comment by Xian55** [comment]
Checkout with this
https://github.com/Xian55/WowClassicGrindBot/commit/0b0183f3b2c93d676b38693550db5b4c67f50991

**Comment by Xian55** [comment]
Consider joining https://discord.gg/pxT33SdW for more immediate help.

**Comment by Adrinalin4ik** [comment]
Thanks at all!

**Comment by Xian55** [comment]
fixed
