### ISSUE TITLE
Off topic question

### ISSUE THREAD

**Issue by rozv11e** [Xian55/WowClassicGrindBot#474]
off topic question: wanted to run bot client and wow in virtual machine, what network settings should be, i can't use main machine to use bot

**Comment by Xian55** [comment]
Hello there 👋 

> bot client and wow in virtual machine, what network settings should be

Without going into any details, to my knowledge there are no special network settings required. If you can play WoW from the VM, im sure you can run the BlazorServer / HeadlessServer, Just be sure to install dotnet sdk / runtime.

>  i can't use main machine to use bot

If you happen to have multiple monitors, you may try to set [KeyboardOnly](https://github.com/Xian55/WowClassicGrindBot#keyboardonly) on the [ClassConfig](https://github.com/Xian55/WowClassicGrindBot#12-class-configuration), the key is the game window has to be visible all times. If that is viable you can avoid using virtual machine.

---

Since the project has been updated to dotnet 7(#465), the minimum OS requirement has been changed(#467).

Related VM issues in the past:
* #188
* #416

Other that that i would recommend to run bot with [HeadlessServer](https://github.com/Xian55/WowClassicGrindBot#7-optional---running-headlessserver) to minimize resource usage also it has a much quicker start time compare to BlazorServer.

**Comment by rozv11e** [comment]
When i try to run the wow client i get error 51900319

**Comment by Xian55** [comment]
If you care to share the details of your setup, i'm sure we would be able to help or point out something.

**Comment by Cybereu** [comment]
I could run bot on a virtual machine on Linux host using VMware besides poor perfomance.

**Comment by rozv11e** [comment]
> I could run bot on a virtual machine on Linux host using VMware besides poor perfomance.

I couldn’t start and use the virtual machine normally, the video memory allocated from the RAM is too slow, which contributes to its overflow and crash from the game
works up to about 5 hours, crashes, it depends on the amount of allocated memory

**Comment by Sattva-108** [comment]
I don't have 2nd screen for my PC yet.
I am not very much experienced VM / remote user. 
I have read all the info i could find about this project in the: **Virtual Machine (VM)**

I'm still wondering if i could just:

1. build according to documentation - (C drive: on main PC, - **not on VM**)
2. install **non-optional dependencies** && make all configurations from [project documentation](https://github.com/Xian55/WowClassicGrindBot?tab=readme-ov-file#getting-it-working)

3. install VM
3.1. install WoW in VM. 
3.2. install **non-optional dependencies** && make all configurations from [project documentation](https://github.com/Xian55/WowClassicGrindBot?tab=readme-ov-file#getting-it-working)
3.3. run WoW process in VM.

1. start **[BlazorServer](https://github.com/Xian55/WowClassicGrindBot?tab=readme-ov-file#5-blazorserver-configuration-process)** (from PC or VM?)
2. **MOST IMPORTANT!** on the PC (not VM) - make code changes / route creating (BlazorServer frontend)


Any advice would be helpful! 
If that's too hard or long topic to discuss:
I would be down to watch some YouTube guide/ Documentation file -  if you could point me.
Thank you.

**Comment by Xian55** [comment]
A long time ago ive attempted to separate the wow client and the backend such a way that it is possible to run them in a different machine.

However after a few attempts i've faced problems and significant delays.


The importance is that to provide BMP quality colors to the backend. Color accurate  data is key.

RDP is slow and takes up too much resources.

Parsec with 4:4 color accuracy might work but it takes a second pc and a subscription.

Playing wow modern client could be a pain to setup in a VM.

Also currently theres a limitation of the wow client needs to be always on top and the top left corner should be not obstructed by any other window. If you as a person can see the wow window then the backend can read it as well.

As the project uses dxgi desktop duplication api.

**Comment by Xian55** [comment]
A long time ago ive attempted to separate the wow client and the backend such a way that it is possible to run them in a different machine.

However after a few attempts i've faced problems and significant delays.


The importance is that ro provide BMP quality colors to the backend. Color accurate  data is key.

RDP is slow and takes up too much resources.

Parsec with 4:4 color accuracy might work but it takes a second pc and a subscription.

Playing wow modern client could be a pain to setup in a VM.

**Comment by Xian55** [comment]
Possible the easiest way is to set the Keyboard Only flag in the ClassConfiguration file. The resize the window for a small size.

**Comment by Sattva-108** [comment]
Thank you for quick reply @Xian55 

Pretty much all i want is "simulate 2nd screen" via VM.

So i can 2 things while bot is running:
1. Edit code in my PC IDE and send to VM.
1.1. This i guess i can solve myself, for example simple copy-paste for changed files.
2. Edit route && control bot via my PC browser (BlazorServer frontend).
2.1. I'm concerned about this one. Can i still do it if bot WoW Process is on the VM? 
2.2. Follow the **[documentation guide](https://github.com/Xian55/WowClassicGrindBot#other-devices)** for 5000 port?

**Comment by Xian55** [comment]
Yes you can do them both.

Like having all the source and binaries on you main macine then mount the topmost folder to the Vm.

Then run the wow client and backend(blazor or headless server) in the vm.

Just be sure to expose a port where the blazorserver could be reached in you local network. Then you could even follow the blazorserver in your phone.

**Comment by Sattva-108** [comment]
> Like having all the source and binaries on you main macine then mount the topmost folder to the Vm.

So even pathing files can be on my PC (not VM) ?
- **mmaps (v3),** 
- **MPQ (v1)**

all i need on VM? 
- give access to the 5000 port
- give access to the folder on PC
- backend folder (blazor or headless)
- wow client
- dotnet?

**Comment by Xian55** [comment]
The vm is only required to run the applications.

Its much easier to store all your data on the host machine.

Then just mount a given folder to the vm.

This way you can avoid copy data between the host and vm.

**Comment by Sattva-108** [comment]
I really appreciate your time and patience with me @Xian55 

I'm new to bots. 

Just read on web:
**That VMs are being easily detected by game Wardens.** 

> Possible the easiest way is to set the Keyboard Only flag in the ClassConfiguration file. The resize the window for a small size.

_To still being able to use PC while bot is online:_

Resizing window && **KeyboardOnly** must be best, "safe" option without 2nd screen?

**Comment by Xian55** [comment]
> Resizing window && KeyboardOnly must be best, "safe" option without 2nd screen?

Thats how i used it in the past.

**Comment by Xian55** [comment]
> Resizing window && KeyboardOnly must be best, "safe" option without 2nd screen?

Thats how i used it in the past.


Its hard to tell what is safe. 

Use it sensibly and you most likely get away with troubles.

**Comment by Sattva-108** [comment]
> Just read on web:
> **That VMs are being easily detected by game Wardens.**

I just want to add that i found that info on web search and not related to Blizzard, also outdated.

And for those whoever reads this:

**We really don't know what is safe.**

**For myself** i don't see any other acceptable way of **active && enjoyable development** of this project:
- without 2nd monitor or VM. 

So may as well try and just see whats up with VM...

**Comment by Xian55** [comment]
I could really recommend to baby sit the app. Never let it run loose.

This app is mostly experiment from my side and many many cases are not covered with a failsafe way.

My mentality is let it crash and i will fix the issue instead of putting most of my code into try catch blocks.

On the other hand i would really recommend to get a cheap 2nd monitor.
