### ISSUE TITLE
Given key '90' was not present in the dictionary. 

### ISSUE THREAD

**Issue by Phatlynx** [Xian55/WowClassicGrindBot#477]

**Comment by Phatlynx** [comment]
I have built the newest build and same error still happens.

**Comment by Xian55** [comment]
Hello there can you tell which zone you are currently in, coordinates also helps.

The the dictionary keys are UiMapID. There's no **90** value at [wow.tools](https://wow.tools/dbc/?dbc=uimap&build=3.4.1.47014#page=1&colFilter[1]=90)

Before getting more info. I have a few ideas
* be sure that the top left corner of the wow window is not covered by any other window.
* If you are using windowed mode, try to go full screen and go back to windowed.
* In case the issue still persist, attempt to recreate `FrameConfig.json` via [Configuration process](https://github.com/Xian55/WowClassicGrindBot#5-blazorserver-configuration-process), deleting the old one.

**Comment by Phatlynx** [comment]
The issue is fixed, I recreated the FrameConfig.json and and went through the Config process again.
