### ISSUE TITLE
Requirement : "BagFull" cant work 

### ISSUE THREAD

**Issue by Billdong1997** [Xian55/WowClassicGrindBot#48]
**Describe the bug**
I started the bot with a brand new character and it only have 2 bags with the inventory 20+6. later, when the number of items reaches 26, the requirement: "BagFull" is still red in blazer so the bot cant sell the trash. Only after I change the requirement  "BagFull" to  "BagCount>26"in the class file will it work properly and sell trash automatically. Is there something wrong with it?

**Comment by Xian55** [comment]
how can you have 20 slot bag at the beginning? To my knowledge the starter bag is 16 slot only

Are you running it retail?

**Comment by Xian55** [comment]
Consider joining us https://discord.gg/CffZKhV for a more immediate conversation.

**Comment by Xian55** [comment]
Good call! Found the issue i messed up with the indexing at the addon side! 😞

**Comment by Billdong1997** [comment]
Thanks! And could you send me a new discord invitation link? The former one is invalid

**Comment by Xian55** [comment]
https://discord.gg/KSqFKu7
