### ISSUE TITLE
CastingHandlerInterruptWatchdog NRE

### ISSUE THREAD

**Issue by Cucoldun** [Xian55/WowClassicGrindBot#480]
### Description

Hello, after the update, a new bug appears, after which the bot stops working:
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Core.Goals.CastingHandlerInterruptWatchdog.Watchdog() in C:\WowClassicGrindBot\Core\GoalsComponent\CastingHandlerInterruptWatchdog.cs:line 59

### Addon Version

1.2.3

### World of Warcraft Client

The Burning Crusade Classic

### Reproduction Steps

when starting the bot and running it for a few minutes, it can reproduce this error.
The last time the same error was 1 week ago.
I don't know how to reproduce this bug

### Logs

[headless_out20221220.log](https://github.com/Xian55/WowClassicGrindBot/files/10267456/headless_out20221220.log)

**Comment by Xian55** [comment]
Hello there 👋 

When i worked on the `CastingHandlerInterruptWatchdog`, i was encountered similar crash while tested with Hunter, `Auto Shot` ability triggered the defect. After tweaking the code i was under the impression that managed to eliminate the effect. Seems not!

As you not specified the addon version, by peeking at the posted log, i'm not seeing my really recent change with more verbose logging.

So first and foremost be sure to checkout the latest [dev](https://github.com/Xian55/WowClassicGrindBot/tree/dev) branch.

Does the uploaded log ([headless_out20221220.log](https://github.com/Xian55/WowClassicGrindBot/files/10267456/headless_out20221220.log)) leads to a crash, can you confirm this ? (and the exception doesn't get written to the file due the crash)

Nonetheless it would be really helpful if you could share a log which contains the sequence of KeyActions event which leads to a crash.

On the other hand i'm seeing that you been using the `Paladin_70_Retribution.json` if you have not made any change regarding the KeyActions, i could do some testing to repro the issue. But it would be best if you upload your `Paladin_70_Retribution.json` file so i can see what changes you were made. Just to cut off any possible differences.

**Comment by Xian55** [comment]
After doing a long session(8h) on the previously mentioned profile `Paladin_70_Retribution.json` i was yet to reproduce the issue.

However i made a small change to avoid Null Reference Exception at the mentioned line. 

Be sure to pull down the repo with and check to be at least 9e961fcd8d82f7263400a5b37956f28806548c62 commit.

Let me know if you still encounter the crash. 🙇

**Comment by Xian55** [comment]
Found another one be sure checkout at least fe54d5fbaec6088920d01537cc7e0cf7ac749828

**Comment by Xian55** [comment]
After a week of testing, i was yet to repro the issue. 

Closing.
