### ISSUE TITLE
Player stuck in place and Random jumps

### ISSUE THREAD

**Issue by rozv11e** [Xian55/WowClassicGrindBot#493]
### Description

After applying the mount, it stays in place and constantly presses the spacebar, does not move anywhere, I can’t understand what is the reason

### Addon Version

1.7.0

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

I started everything according to the instructions, I use the headles server, after a while it gets in place and constantly jumps, restarting helps

### Logs

[headless_out20230127.log](https://github.com/Xian55/WowClassicGrindBot/files/10515835/headless_out20230127.log)

**Comment by rozv11e** [comment]
{
  "ClassName": "DeathKnight",
  "Loot": true,
  "Skin": true,
  "Herb": true,
  "PathFilename": "path1.json", 
  "PathReduceSteps": true,
  "PathThereAndBack": true,
  "NPCMaxLevels_Below": 15,
  "NPCMaxLevels_Above": 15,
  "MountKey": "N0",
  "NPC": true,
  "Blacklist": [
    "Duskwing Eagle",
    "Storm Giant",
    "Proto-Whelp",
    "Proto-Drake Egg",
    "Winterscorn Worg",
    "Winterscorn Hunter",
    "Dragonflayer Handler",
    "Beryl Treasure Hunter",
    "Trapped Mammoth Calf",
    "Risen Longrunner",
    "Beryl Hound",
    "Beryl Reclaimer"
     ],
  
  "IntVariables": {
    "MIN_HP_FOOD%": 40,
    "MIN_RUNE_TO_DUMP": 40,
    "Debuff_Frost Fever": 237522,
    "Debuff_Blood Plague": 237514,
    "MIN_TIME_REFRESH": 3500
  },
  "Form": [
    {
      "Name": "Blood Presence",
      "Key": "F1",
      "Form": "DeathKnight_Blood_Presence"
    },
    {
      "Name": "Frost Presence",
      "Key": "F2",
      "Form": "DeathKnight_Frost_Presence"
    },
    {
      "Name": "Unholy Presence",
      "Key": "F3",
      "Form": "DeathKnight_Unholy_Presence"
    }
  ],
  "Pull": {
    "Sequence": [
      {
        "Name": "Death Coil",
        "Key": "8",
        "WhenUsable": true,
        "Requirements": [
          "MinRange > 25",
          "SpellInRange:1",
          "RunicPower >= MIN_RUNE_TO_DUMP"
        ],
        "AfterCastWaitCombat": true
      },
      {
        "Name": "Icy Touch",
        "Key": "6",
        "WhenUsable": true,
        "Requirements": [
          "!TargetCastingSpell",
          "!Frost Fever",
          "SpellInRange:0"
        ],
        "AfterCastAuraExpected": true,
        "AfterCastWaitCombat": true
      }
    ]
  },
  "Combat": {
    "Sequence": [
      {
        "Name": "Trinket 1",
        "Key": "N1",
        "Item": true,
        "WhenUsable": true,
        "Requirements": [
          "InMeleeRange"
        ]
      },
      {
        "Name": "Mind Freeze",
        "Key": "9",
        "WhenUsable": true,
        "Requirements": [
          "InMeleeRange",
          "TargetCastingSpell"
        ]
      },
      {
        "Name": "Pestilenc",
        "Key": "F6",
        "WhenUsable": true,
        "Requirements": [
          "Frost Fever && Blood Plague && (Debuff_Frost Fever < MIN_TIME_REFRESH || Debuff_Blood Plague < MIN_TIME_REFRESH)",
          "InMeleeRange"
        ]
      },
      {
        "Name": "Blood Tap",
        "Key": "N6",
        "WhenUsable": true,
        "Requirements": [
          "!Blood Tap",
          "BloodRune <= 1"
        ]
      },
      {
        "Name": "Empower Rune Weapon",
        "Key": "N3",
        "WhenUsable": true,
        "Requirements": [
          "TotalRune == 0",
          "RunicPower <= 105",
          "InMeleeRange"
        ]
      },
      {
        "Name": "Unbreakable Armor",
        "Key": "N4",
        "WhenUsable": true,
        "Requirements": [
          "InMeleeRange"
        ]
      },
      {
        "Name": "Howling Blast",
        "Key": "7",
        "WhenUsable": true,
        "Requirements": [
          "SpellInRange:0"
        ]
      },
            {
        "Name": "Blood of Earth",
        "Key": "F10",
        "Requirements": [
          "Health% < 70"
        ]
      },
      {
        "Name": "Death Strike",
        "Key": "F5",
        "WhenUsable": true,
        "Requirements": [
          "Health% < 70"
        ]
      },
      {
        "Name": "Frost Strike",
        "Key": "2",
        "WhenUsable": true,
        "Requirements": [
          "InMeleeRange"
        ]
      },
      {
        "Name": "Death Coil",
        "Key": "8",
        "WhenUsable": true,
        "Requirements": [
          "MobCount < 2",
          "RunicPower >= 100",
          "SpellInRange:1"
        ]
      },
      {
        "Name": "Blood Boil",
        "Key": "1",
        "WhenUsable": true,
        "Requirements": [
          "MobCount > 1",
          "InMeleeRange"
        ]
      },
      {
        "Name": "Blood Strike",
        "Key": "3",
        "WhenUsable": true,
        "Charge": 2,
        "Cooldown": 2000,
        "Requirements": [
          "MobCount < 2",
          "Debuff_Frost Fever > MIN_TIME_REFRESH && Debuff_Blood Plague > MIN_TIME_REFRESH",
          "InMeleeRange"
        ]
      },
      {
        "Name": "Obliterate",
        "Key": "4",
        "WhenUsable": true,
        "Requirements": [
          "MobCount < 2",
          "Frost Fever",
          "Blood Plague",
          "InMeleeRange"
        ]
      },
      {
        "Name": "Icy Touch",
        "Key": "6",
        "WhenUsable": true,
        "Requirements": [
          "!Frost Fever",
          "SpellInRange:0"
        ],
        "AfterCastAuraExpected": true
      },
      {
        "Name": "Plague Strike",
        "Key": "5",
        "WhenUsable": true,
        "Requirements": [
          "!Blood Plague",
          "InMeleeRange"
        ],
        "AfterCastAuraExpected": true
      },
      {
        "Name": "AutoAttack",
        "Requirements": [
          "!AutoAttacking"
        ]
      },
      {
        "Name": "Approach",
        "Log": false
      }
    ]
  },
  "Adhoc": {
    "Sequence": [
      {
        "Cost": 3.1,
        "Name": "Horn of Winter",
        "Key": "F4",
        "InCombat": "i dont care",
        "WhenUsable": true,
        "Requirements": [
          "!Horn of Winter",
          "!Mounted"
        ]
      }
    ]
  },
  "Parallel": {
    "Sequence": [
      {
        "Name": "Food",
        "Key": "=",
        "Requirement": "Health% < MIN_HP_FOOD%"
      },
      {
            "Name": "lether",
            "Key": "F12",
            "Requirement": "BagItem:33567:5"
      },
      {
        "Name": "lether",
        "Key": "N1",
        "Requirement": "BagItem:33567:5"
      }
    ]
  },
  "NPC": {
    "Sequence": [
    {
        "Name": "Repair",
        "Key": "C",
        "Requirement": "Items Broken",
        "PathFilename": "__Path_Howling Fjord_Vendor_Horde.json"
    },
    {
        "Name": "Sell",
        "Key": "C",
        "Requirement": "BagFull",
        "PathFilename": "__Path_Howling Fjord_Vendor_Horde.json"
    }
    ]
}
}

**Comment by rozv11e** [comment]
[json.zip](https://github.com/Xian55/WowClassicGrindBot/files/10516383/json.zip)

**Comment by Xian55** [comment]
hello there 👋 

Did you have bindpad addon enabled with [ClearTarget] macro bound to -> "Insert" hotkey?

Based on the logs i have an assumption about the target was not cleared.

```
[07:47:02:233 INF] [NpcNameFinder] type = None
[07:47:02:461 INF] MountHandler: Cast started ? True 204,0933ms
[07:47:02:477 INF] MountHandler: Cast ended ? True 0,0002ms
[07:47:02:477 INF] FollowRouteGoal: Has target but its dead.
[07:47:07:223 INF] FollowRouteGoal: Random jump
[07:47:17:361 INF] FollowRouteGoal: Random jump
[07:47:28:245 INF] FollowRouteGoal: Random jump
```

**Comment by rozv11e** [comment]
yes, I checked several times

**Comment by Xian55** [comment]
```
[07:47:02:477 INF] FollowRouteGoal: Has target but its dead.
```

Does the target get cleared after ?

**Comment by rozv11e** [comment]
no, which is strange, because using an account on another computer, there is no such thing

**Comment by rozv11e** [comment]
I'll try to reinstall and try, I'll write back

**Comment by rozv11e** [comment]
still having this problem...
He doesn't stick to the target of the mob, but still stands still and jumps

**Comment by Xian55** [comment]
Can you send logs about this?

**Comment by rozv11e** [comment]
[headless_out20230129.log](https://github.com/Xian55/WowClassicGrindBot/files/10529356/headless_out20230129.log)
he does not hold a corpse in the target, this only happens after the mount has been summoned

**Comment by Xian55** [comment]
Hey just pushed a few changes on `dev` branch be sure to pull to get latest changes. https://github.com/Xian55/WowClassicGrindBot/commit/c3bcdec75715ddc13a44642515b72d30a1634f4b

It would be nice if you could send a new log with the latest version.

**Comment by rozv11e** [comment]
I'll try it, thanks, I'll write it off as I try it, do I need to rebuild?

**Comment by Xian55** [comment]
Yes, always rebuild when checking out changes!

**Comment by rozv11e** [comment]
[headless_out20230130.log](https://github.com/Xian55/WowClassicGrindBot/files/10534866/headless_out20230130.log)
problem still exists..

**Comment by Xian55** [comment]
Hey i've seeing mixed results in the logs, sometimes it can clear the target sometimes not. 

Be sure to enable `/console scriptErrors 1` in game to see if there's any LUA error happening.

**Comment by Xian55** [comment]
Hey in case the issue still persist, i would like to ask you to checkout `dev` branch latest commit ca915bf5e6152bbad6b5ab5ccb85563c8a7a380d.
