### ISSUE TITLE
Multiple mobs not picking up on Asian servers

### ISSUE THREAD

**Issue by ray-0000** [Xian55/WowClassicGrindBot#496]
### Description

Hello, killing multiple monsters in the Asian server does not pick up, only the last monster that was killed will be picked up, and multiple monsters will only be picked up when the camera is zoomed in very close.

### Addon Version

1.7.0

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

N/A

### Last Good Version

Works fine in China server

### Logs

[out20230209.log](https://github.com/Xian55/WowClassicGrindBot/files/10698672/out20230209.log)

**Comment by Xian55** [comment]
Hey  👋 

With the provided limited context of the issue, i could only rely on past experiences with eastern game client languages.

In the past, there were numerous report such issues, please use the [github issue search](https://github.com/Xian55/WowClassicGrindBot/issues?q=is%3Aissue+is%3Aclosed) feature if you interested in what resolution they had. one example: #167 

There's a known limitation what the current `NpcNameFinder` is capable of. Which might goes the following:

Certain Npc names in different languages can be described very few characters / glyphs. To be more specific, if you take a look at the following [bear npc names](https://www.wowhead.com/classic/zone=267/hillsbrad-foothills#npcs;q=bear) in the English client, its decent sized for `NpcNameFinder`, while in other eastern languages they might be only a single Glyph / character.

In that case the `NpcNameFinder` unable to distinguish between "NPC name pixel" or anything else on the screen while having the color match. There's a lower bound which prevents detecting "false NPC Names".

---

All the previous testing was conducted in English client. If its possible, to change the game language to English. i would encourage to try it out!

**Comment by ray-0000** [comment]
I changed the language to English and the problem still exists

https://user-images.githubusercontent.com/110283658/217993552-b24f59ea-dd25-4193-a410-9584cda69ac2.mp4


Only works properly if the npc name is big enough


https://user-images.githubusercontent.com/110283658/217993411-7a2f383a-ea9d-4dcd-9245-8c0cca45d2d3.mp4



My understanding is that the gray of the Asian server may be grayer, and the correct gray will only appear when the npc name is bigger

[out20230210.log](https://github.com/Xian55/WowClassicGrindBot/files/10703439/out20230210.log)

**Comment by Xian55** [comment]
Probably due the different font rendering theres transparency involved.

 If you could provide more .bmp type screenshots i could do some testing at my end

**Comment by ray-0000** [comment]
![WoWScrnShot_021023_165228](https://user-images.githubusercontent.com/110283658/218047786-c26e4a51-d609-408e-a974-8743dbf439bc.jpg)
This is a screenshot of the game, sorry I changed back to Chinese font. The font folder will be automatically generated in the Asian server. Even if the recommended font is used, it will not be picked up normally.

![QQ图片20230210170039](https://user-images.githubusercontent.com/110283658/218048700-248fbdb7-c212-475f-a4e5-1bd359c98fd5.png)

The above is the file generated by the font folder

I try to modify    private SearchMode searchMode = SearchMode.Fuzzy;
It has been improved, but the mouse will click several times next to the monster name to correctly click on the monster

**Comment by Xian55** [comment]
Its been a long time since ive touched on SearchMode.Fuzzy.

In the project theres a project called coretests

It has an npcnamefinder section where you can visualize what npc names are detected on screen. You may have to edit a few constants. Its called overlay

**Comment by ray-0000** [comment]
My ability is limited to modifying the answers given, editing constants is beyond my knowledge，thank you for your help。

**Comment by Xian55** [comment]
If you plan not using the skinning feature, you set [KeyboardOnly](https://github.com/Xian55/WowClassicGrindBot#keyboardonly)

**Comment by Xian55** [comment]
> ![WoWScrnShot_021023_165228](https://user-images.githubusercontent.com/110283658/218047786-c26e4a51-d609-408e-a974-8743dbf439bc.jpg) This is a screenshot of the game, sorry I changed back to Chinese font. The font folder will be automatically generated in the Asian server. Even if the recommended font is used, it will not be picked up normally.
> 
> ![QQ图片20230210170039](https://user-images.githubusercontent.com/110283658/218048700-248fbdb7-c212-475f-a4e5-1bd359c98fd5.png)
> 
> The above is the file generated by the font folder
> 
> I try to modify private SearchMode searchMode = SearchMode.Fuzzy; It has been improved, but the mouse will click several times next to the monster name to correctly click on the monster

after doing a quick search about the provided file name it seems blizzard doing something with the fonts.
https://us.forums.blizzard.com/en/wow/t/unable-to-change-fonts/1388615
https://eu.forums.blizzard.com/en/wow/t/crazy-fps-drops-when-panning-camera-since-prepatch/396350/22?page=2
https://www.reddit.com/r/WowUI/comments/yeav2h/help_how_do_i_change_wows_fonts_i_think_theyve/

**Comment by ray-0000** [comment]
Deleted wow today, re-downloaded from the Asian server customer service, reinstalled win10, it has worked normally, thank you for your help.

**Comment by Xian55** [comment]
I'm glad you found a solution, thanks for the detailed info. Closing
