### ISSUE TITLE
Enter the fight, fight back now

### ISSUE THREAD

**Issue by ray-0000** [Xian55/WowClassicGrindBot#497]
### Description

Hi, may I ask how to modify the counterattack immediately after entering the battle, because occasionally it will run straight without counterattack, and it will get stuck if it deviates from the route，I searched the question and found no answer。

### Addon Version

1.7.0

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

N/A

**Comment by Xian55** [comment]
Hey please upload a which contains the issue in order to investigate the issue

**Comment by ray-0000** [comment]
Sorry, my description is inaccurate. It should be entering the battle. If the player’s life is not damaged, they will not fight back. They will only run in a straight line until they are hit by a monster chasing behind or leave the battle. Then they will stop returning to the correct path. Part of the situation is going back to the city to sell and repair, so the document should be quite large. I want to modify any situation, and immediately dismount and fight back when entering the battle, but I don't know how to modify it.

**Comment by Xian55** [comment]
Yo can modify this behaivour by altering the goapgoal preconditions. 

Lookat [FollowRouteGoal](https://github.com/Xian55/WowClassicGrindBot/blob/ca915bf5e6152bbad6b5ab5ccb85563c8a7a380d/Core/Goals/FollowRouteGoal.cs#L96) and [npcGoal](https://github.com/Xian55/WowClassicGrindBot/blob/ca915bf5e6152bbad6b5ab5ccb85563c8a7a380d/Core/Goals/AdhocNPCGoal.cs#L92)

**Comment by ray-0000** [comment]
Ok, thank you, I will learn how to modify it.
