### ISSUE TITLE
Dismounting when unstuck

### ISSUE THREAD

**Issue by Cucoldun** [Xian55/WowClassicGrindBot#498]
Hi, sometimes when the bot gets stuck, there is a situation where dismounting would solve this problem. Is it possible to add a condition that, when stuck, the bot would dismount? Thanks in advance for your reply!

**Comment by Xian55** [comment]
Hey definitely!

**Comment by Cucoldun** [comment]
and how can this be done?

**Comment by Xian55** [comment]
[StuckDetector.cs](https://github.com/Xian55/WowClassicGrindBot/blob/dev/Core/GoalsComponent/StuckDetector.cs) is responsible for detecting this state. I will extend it to consider mounted state.

**Comment by Xian55** [comment]
Hey be sure to checkout pull the latest `dev` branch. Let me know if you encounter any further issues: 👋
