### ISSUE TITLE
Bot Program Unable to initiate FreelyFlush in game

### ISSUE THREAD

**Issue by officiallevij** [Xian55/WowClassicGrindBot#504]
### Description

I'm sorry if this is put in the wrong place. I stopped using my bot program in October 22 and it was working great. fired it back up yesterday. I cannot initiate FreelyFlush in the game to initialize the bot and allow me to load the leveling profile. In game, it won't allow /freeflush to be executed, meaning enter doesn't execute it. It stays in the chat box and won't let you put it through. Thank you for any assistance that can be given! The only change I can think of is I moved to a different physical location. I can only get the Bot UI to load in browser if I start the BOT first, rather than when the game client is already open.

### Addon Version

1.7.19

### World of Warcraft Client

The Burning Crusade Classic

### Reproduction Steps

Open Bot Program
Open WoW
Go through automatic restart of bot to connect to wow client
Press Initiate State in Bot UI
Unable to initiate state in game

### Last Good Version

1.7.19

### Screenshots

![BotError](https://user-images.githubusercontent.com/78989779/231171365-0fe9e334-f5c7-4920-83e4-5e9a9edbee51.PNG)
![UI Pic 1](https://user-images.githubusercontent.com/78989779/231172767-661b51ab-cc5b-42e8-8bf0-56c18e371454.PNG)
![In Game Issue](https://user-images.githubusercontent.com/78989779/231172800-dbe50699-44ba-49e0-a7b9-0d7c8fa72cc4.PNG)

### Logs

[out20230411.log](https://github.com/Xian55/WowClassicGrindBot/files/11200746/out20230411.log)

**Comment by Xian55** [comment]
Hello there!

This kind of issue happened to me before. The problem was, the game client were placed in a location where it was required to run game with higher privileges (even administrator mode) compare to the BlazorServer.exe.

The BlazorServer.exe itself dosen't require to administrator privileges by default, in order to run. It all comes down how you setup the locations

So what you can attempt, is to give administrator privileges to the BlazorServer.exe in order to send keystroke to the WoW.exe.

---

On the other hand be sure to get the latest version from github.

**Comment by officiallevij** [comment]
Thank you for much for the response. I tried that and nothing changed.

I am getting LUA errors from the Freely addon.

**Comment by officiallevij** [comment]
It seems to me that being unable to execute the /freelyflush command in game is the problem. :/

**Comment by Xian55** [comment]
As i asked you before, please update to the latest version by checking out the dev branch of the project.

Your version **1.7.19** vastly out of date.
Currently **1.7.39** is the target.

**Comment by officiallevij** [comment]
Thankk you. Which part do I update? I am sorry, I was not the one to set this up originally so I am very new.

**Comment by Xian55** [comment]
I'm not sure how you downloaded the project to your machine, but i recommend using git for this purpose.
If that's not available, download link [here](https://github.com/Xian55/WowClassicGrindBot/archive/refs/heads/dev.zip).

unzip it the folder where its already located on your machine, then follow the [Build the solution](https://github.com/Xian55/WowClassicGrindBot#42-build-the-solution)

Finally to update the addon it self follow this [guide](https://github.com/Xian55/WowClassicGrindBot#5-blazorserver-configuration-process)

**Comment by officiallevij** [comment]
@Xian55 I was able to get it working. I REALLY appreciate your help!!

**Comment by Xian55** [comment]
Hey, im glad you managed to figure out. I hope you learned something new along the line.
