### ISSUE TITLE
Classic era no Focus target | Assist focus does not work

### ISSUE THREAD

**Issue by adamssullivan** [Xian55/WowClassicGrindBot#520]
**Is your feature request related to a problem? Please describe.**
When playing Classic Era there is no way to focus a character. When trying to use Assist focus it needs that to work.

**Describe the solution you'd like**
I would like something like Target Party Member 1 to be the key used for Target Focus 

**Describe alternatives you've considered**
I am not sure if anything can be done

**Additional context**

**Comment by Xian55** [comment]
Hey, Indeed the `Focus` system only got introduced with TBC. Really good idea to use the `partyN` members. I will look into it

**Comment by Xian55** [comment]
Be sure to use Addon version `1.7.43` to make it working.

Of course there's one additional requirement, party is required for `AssistFocus` Mode in Vanilla.

`focus` can be replaced with `party1` unit name. So no backend changes were required. However have to use a different keybind. In the keybind settings please set the following

<html>
<body>


Target Party Member 1 | PageUp
-- | --

</body>
</html>

**Comment by adamssullivan** [comment]
This works as intended. Thanks!
