### ISSUE TITLE
Will this project be able to support clients with some new original maps?

### ISSUE THREAD

**Issue by BillDong2021** [Xian55/WowClassicGrindBot#524]
A story expansion inspired by the Warcraft universe of Blizzard Entertainment and developed by the Turtle WoW Team. This expansion aims to take a different path from the Burning Crusade, emphasizing the familiar Azeroth of Vanilla WoW over the cosmic battle with the Burning Legion. While being heavily based on the lore from Warcraft 3 and Vanilla WoW, Mysteries of Azeroth seeks to enhance the game by adding content that matches the already well-established lore of Warcraft Universe. 

You can see more in turtle-wow.org

I noticed that they have many new original maps, the data is also in MPQ. If it is supposed to apply the bot in that client, what should be done?

**Comment by Xian55** [comment]
Hey, to my knowledge Turtle WoW uses the old legacy client, which is vastly different compare to the *"modern"* Classic WoW client.

Similar question has been asked before #450.

While a - HermesProxy - compatibility layer already exists with 1.12.1 client, but Turtle WoW uses custom 1.12.x client it might be incompatible.
