### ISSUE TITLE
I cant build  from Powershell

### ISSUE THREAD

**Issue by starnodes** [Xian55/WowClassicGrindBot#525]
### Description

C:\Program Files\dotnet\sdk\7.0.109\Current\SolutionFile\ImportAfter\Microsoft.NET.Sdk.Solution.targets(27,5): error NE
TSDK1134: сборка решения с заданным идентификатором RuntimeIdentifier не поддерживается. Если вы хотите выполнить публикацию для одного RID, укажите RID на уровне отдельного проекта. [C:\WowClassicGrindBot\MasterOfPuppets.sln]

### Addon Version

latest

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

1) Unpacking to directory C:\WowClassicGrindBot
2) Im trying build with dotnet-sdk-7.0.100-win-x64 dotnet-sdk-7.0.109-win-x64 dotnet-sdk-7.0.306-win-x64 dotnet-sdk-7.0.306-win-x86
3) Using windows 11 pro latest update
3) Always got error:
C:\Program Files\dotnet\sdk\7.0.109\Current\SolutionFile\ImportAfter\Microsoft.NET.Sdk.Solution.targets(27,5): error NE
TSDK1134: сборка решения с заданным идентификатором RuntimeIdentifier не поддерживается. Если вы хотите выполнить публикацию для одного RID, укажите RID на уровне отдельного проекта. [C:\WowClassicGrindBot\MasterOfPuppets.sln]

Ошибка сборки.

C:\Program Files\dotnet\sdk\7.0.109\Current\SolutionFile\ImportAfter\Microsoft.NET.Sdk.Solution.targets(27,5): error NE
TSDK1134: сборка решения с заданным идентификатором RuntimeIdentifier не поддерживается. Если вы хотите выполнить публикацию для одного RID, укажите RID на уровне отдельного проекта. [C:\WowClassicGrindBot\MasterOfPuppets.sln]
    Предупреждений: 0
    Ошибок: 1

**Comment by Xian55** [comment]
Hello thanks for letting me know.

I assume you've tried to build with the [mentioned](https://github.com/Xian55/WowClassicGrindBot#42-build-the-solution) cli command.

For me, it fails as well. At the time - probably it was dotnet 6 - when i made docs about the build process it worked.

Try with the following command instead.

```ps
dotnet build -c Release /p:Platform=x64
```
or
```ps
dotnet build -c Release /p:Platform=x86
```

Sorry for the inconveniences

**Comment by starnodes** [comment]
> Hello thanks for letting me know.
> 
> I assume you've tried to build with the [mentioned](https://github.com/Xian55/WowClassicGrindBot#42-build-the-solution) cli command.
> 
> For me, it fails as well. At the time - probably it was dotnet 6 - when i made docs about the build process it worked.
> 
> Try with the following command instead.
> 
> ```postscript
> dotnet build -c Release /p:Platform=x64
> ```
> 
> or
> 
> ```postscript
> dotnet build -c Release /p:Platform=x86
> ```
> 
> Sorry for the inconveniences

tnx, its working!

**Comment by Xian55** [comment]
fixed with fa199208183cc8f315ad08bb64de18b1877d7e4d
