### ISSUE TITLE
Bot can't move (Unstuck error)

### ISSUE THREAD

**Issue by starnodes** [Xian55/WowClassicGrindBot#526]
### Description

I configured the bot according to the instructions, but it does not follow the routes. The bot only moves if it sees a target.

### Addon Version

latest

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

1) Set up the wotlk client as in the documentation (i use Russian language)
2) Start BlazorServer (as admin or just user)
3) Create new dranei shaman with profile Shaman_1
4) Shaman cant run in route, but can run if see mobs.
[04:47:33:557 I] [StuckDetector  ] Unstuck by turning for 283ms
[04:47:33:881 I] [StuckDetector  ] Unstuck by moving for 1713ms
5) I also tried running the bot on my level 49 shaman in Azshara. I chose the appropriate route and the bot also did not go anywhere until it saw the target or was not attacked.
6) Where did I go wrong?

### Logs

[out20230718_004.log](https://github.com/Xian55/WowClassicGrindBot/files/12074948/out20230718_004.log)

**Comment by Xian55** [comment]
👋 Hello there.

By default the bot uses arrow keys(←, ↑, →, ↓) for movement. Be sure to have them setup.
![image](https://github.com/Xian55/WowClassicGrindBot/assets/367101/23b077c6-6534-40dc-ad5a-5967110e0ede)

On the other hand, when you press the `Start Bot` button be sure you are outside, there's nothing above your head to block the sky.

---
when you see the following messages in the logs
```
[StuckDetector  ] Unstuck by turning for 219ms
[StuckDetector  ] Unstuck by moving for 1748ms
```
Does the character turns or moves at all?

**Comment by starnodes** [comment]
> Xian55

Dear Xian55, you were right, it seems I missed only 1 key assignment and this is the forward key :))
