### ISSUE TITLE
“BagFull” again

### ISSUE THREAD

**Issue by Billdong1997** [Xian55/WowClassicGrindBot#53]
The bot will show “BagFull” as soon as the backpack is full, although I have another 4 bags. I think the question is still in the Addon.

BTW: I joined the discord group but cannot see anything, I guess it is due to the Great Firewall of China. :(

**Comment by LarryLan** [comment]
you need somehow do a screen shot for the pixels then we can investigate it cos there's no way to reproduce it atm.

**Comment by LarryLan** [comment]
btw do you use Chinese version client or English version client?

**Comment by Billdong1997** [comment]
Well, I just change LootableItemSlotCount() and it works, but i know it is not the best way to solve it.

****
        public long LootableItemSlotCount()
        {
           // int count = 0;
           // for(int i = 0; i<BagItems.Count; i++)
           // {
           //     if (bagForLoot[BagItems[i].Bag])
           //     {
           //         count++;
           //     }
           // }
           // return count;
           return BagItems.Count;
        }

**Comment by Xian55** [comment]
> btw do you use Chinese version client or English version client?
There's no localization involved here. The bag IDs should have the same in both clients.

Make sure to use the latest addon version.
```
## Version: 1.0.15
```
and the 
```
Json\dbc\containers.txt
```
file is present

**Comment by Billdong1997** [comment]
I have checked the version of addon but the problem persists

**Comment by Xian55** [comment]
In the blazorserver, under the `Swagger` can you see what items do you have in the inventory ?

**Comment by Xian55** [comment]
can you show me your output of this command? Just paste in in the chat
```
/dump GetInventoryItemLink("player", 20)
```

**Comment by Billdong1997** [comment]
Yes, I can see what i have In the blazorserver.

the response of the command is like this
![1](https://user-images.githubusercontent.com/83825966/118757124-ffbf4200-b89e-11eb-812a-8af6eada419f.PNG)

**Comment by Xian55** [comment]
I see the issue now. The `4498` bag is not included in the `containers.txt` strange... Not my best idea it seems.
I'm going to do some changes around this. i've just found an api which contains the necessary information `GetContainerNumFreeSlots`
