### ISSUE TITLE
Looting while still in combat and actively being attacked

### ISSUE THREAD

**Issue by aislehealzju** [Xian55/WowClassicGrindBot#533]
**Is your feature request related to a problem? Please describe.**
My character (mage) kills 1st of n mobs in engagement and then ignores the other n mobs while proceeding with loot goal. Character then kills 2nd of n mobs and ignores the n remaining mobs while looting the 2nd etc.

**Describe the solution you'd like**
Character does not attempt loot goal while in combat.

**Describe alternatives you've considered**
Blacklist monsters that spawn in groups.

**Additional context**
Thank you, Xian55, for creating and supporting this product and community.

EDIT: This is for classic WOTLK version.

**Comment by Xian55** [comment]
Hello there,

During combat when fighting with multiple enemies after killling one, the loot only going to be attempted when the **KeyboardOnly** mode is set to **true**.

This seems a bug. To conduct an investigation, please upload the related log files.

Gooday

**Comment by aislehealzju** [comment]
You rock Xian55! I'm at work now. As soon as I'm back home I'll upload logs and then try to test the KeyboardOnly mode.

**Comment by aislehealzju** [comment]
Evening Xian55!

I tried testing a bit more tonight but my pathing seems to be broken. I'll detail it here but maybe I should start a new "issue" thread.

When I start bot it attempts to follow the route and then crashes with an exception: "System.Exception: Failed to set continent to: 530"

In log 001 I was trying to use a path that I made. I was using AttendedGrind mode for a while and then switched to Grind and immediately got the exception:
[out20230827_001.log](https://github.com/Xian55/WowClassicGrindBot/files/12449313/out20230827_001.log)


In log 003 I tried one of the supplied paths on Grind mode and immediately got the exception:
[out20230827_003.log](https://github.com/Xian55/WowClassicGrindBot/files/12449314/out20230827_003.log)

Let me know if you need any more info.

Thank you again Xian55!

**Comment by Xian55** [comment]
Hello,

after doing a quick peek at the logs, im seeing that you are trying to load the profile with `Outland` continent.
```
[19:41:39:211 I] [BotController  ] ClassConfig: Mage_54_Frost_Arcane.json with Path: Hellfire Peninsula_2023_08_24_21_55_23.json
```

The issue
```
[19:41:41:259 E] Failed to set continent to: 530
```
Means that the 530 wdt file was not found which is TBC Outland

Please follow the instructions here to get the [mpq files](https://github.com/Xian55/WowClassicGrindBot#21-using-v1-localremote-pathhing)

**Comment by Xian55** [comment]
Hi, does the 
```
"System.Exception: Failed to set continent to: 530"
```
issue still persists ?
