### ISSUE TITLE
Known Issue: Loot is disabled, however while fighting multiple enemies `Enable Interact Key` cause unexpected Loot attempts

### ISSUE THREAD

**Issue by starnodes** [Xian55/WowClassicGrindBot#539]
### Description

{
  "ClassName": "Paladin",
  "TargetLastTargetKey": "F9",
  "InteractMouseOverKey": "F8",
  "InteractKey": "F7",
  "TargetTargetOfTargetKey": F6",
  "TargetPetKey": "F12",
  "PetAttackKey": "F11",
  "TargetFocusKey": "F10",
  "NPCMaxLevels_Below": 99,
  "NPCMaxLevels_Above": 3,
  "Mode": "Grind",
//  "Mode": "AssistFocus",
//  "Mode": "AttendedGrind",
  "Loot": false,
  "Skin": false,
  "KeyboardOnly": true,
  "PathFilename": "Howling Fjord_2023_07_21_15_08_37.json",
  "PathThereAndBack": true,
  "PathReduceSteps": true,
  "MountKey": "N2",
  "IntVariables": {
    "MIN_SPEED_SEAL": 3000,
    "MIN_TARGET_HP%": 20,
    "MIN_HP_BEFORE_HEAL%": 20,
    "MIN_MANA%": 30,
    "Buff_Art of War": 236246
  },

### Addon Version

1.7.44

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

disable loot and skin in config file
start wow and bot
bot is still trying to loot the target and rip off the skin))

### Logs

<html>
<body>

14:15:16 | ["Judgement" ] Update "Mana" cost to 88 from 147
-- | --
14:15:16 | ["Правосудие света"] Update "Mana" cost to 88 from 147
14:15:15 | Inactive, kill credit detected!
14:15:08 | 17 -> 18 "Borean Leather Scraps"
14:15:08 | New Plan= NO PLAN
14:15:06 | New Plan= " Approach Target"
14:15:06 | ["Judgement" ] Update "Mana" cost to 147 from 88
14:15:06 | ["Правосудие света"] Update "Mana" cost to 147 from 88
14:15:06 | ["Длань возмездия"] PrevGCD: 0ms \| GCD: 0ms \| Cast: 0ms \| Next spell -400ms
14:15:06 | ["Длань возмездия"] instant usable: True->True \| current: False->True \| "NONE"->"CAST_SUCCESS"
14:15:06 | ["Длань возмездия"] instant input 88ms 0.0001ms
14:15:06 | Found target!
14:15:06 | 19 -> 20 "Pearly Seashell Fragment"
14:15:06 | Stop auto interact!
14:15:06 | New Plan= " Pull Target"
14:15:06 | Mounted ? False
14:15:06 | Cast ended 143.0431ms
14:15:06 | Cast started 100.4699ms
14:15:06 | ["Judgement" ] Update "Mana" cost to 88 from 147
14:15:06 | ["Правосудие света"] Update "Mana" cost to 88 from 147
14:15:06 | Mount up
14:15:06 | New Plan= " Follow Route"
14:15:05 | Found target!
14:15:05 | New Plan= " Approach Target"
14:15:05 | ["LocalPathingApi"] total distance 49.057053 > 100. Have to clear RouteToWaypoint.
14:15:05 | New Plan= " Follow Route"
14:15:05 | Total: 0 \| Remaining: 0
14:15:05 | New Plan= " Corpse Consumed"
14:15:05 | Safe to consume a corpse.
14:15:05 | New Plan= " Consume Corpse"
14:15:05 | Kill credit detected! Known kills: 1 \| Fighting with: 0
14:15:03 | ["Божественная буря"] PrevGCD: 0ms \| GCD: 74ms \| Cast: 0ms \| Next spell -326ms
14:15:03 | ["Божественная буря"] instant usable: True->False \| current: False->True \| "NONE"->"CAST_SUCCESS"
14:15:03 | ["Божественная буря"] instant input 60ms 0.0001ms
14:15:02 | ["Удар воина света"] PrevGCD: 0ms \| GCD: 1500ms \| Cast: 0ms \| Next spell 1100ms
14:15:02 | ["Удар воина света"] instant usable: False->False \| current: True->False \| "NONE"->"CAST_SUCCESS"
14:15:02 | ["Удар воина света"] instant input 58ms 32.3609ms
14:15:01 | React to SPELL_FAILED_NOT_READY -- wait until its ready
14:15:01 | ["Удар воина света"] instant usable: True->False \| current: False->True \| "NONE"->"SPELL_FAILED_NOT_READY"
14:15:01 | ["Удар воина света"] instant input 74ms 0.0001ms
14:15:00 | ["Judgement" ] ... AfterCastDelay 25ms
14:15:00 | ["Judgement" ] PrevGCD: 1500ms \| GCD: 1442ms \| Cast: 0ms \| Next spell 1100ms
14:15:00 | ["Judgement" ] instant usable: False->False \| current: True->False \| "NONE"->"SPELL_FAILED_NOT_READY"
14:15:00 | ["Judgement" ] instant input 73ms 0ms
14:15:00 | React to SPELL_FAILED_NOT_READY -- wait until its ready
14:15:00 | ["Judgement" ] instant usable: True->False \| current: False->True \| "NONE"->"SPELL_FAILED_NOT_READY"
14:15:00 | ["Judgement" ] instant input 75ms 0ms
14:14:58 | ["AutoAttack" ] instant input 75ms 75ms
14:14:58 | 16 -> 17 "Borean Leather Scraps"
14:14:57 | New Plan= NO PLAN
14:14:57 | ["Удар воина света"] PrevGCD: 1500ms \| GCD: 1405ms \| Cast: 0ms \| Next spell 1100ms
14:14:57 | ["Удар воина света"] instant usable: False->False \| current: False->False \| "NONE"->"SPELL_FAILED_NOT_READY"
14:14:57 | ["Удар воина света"] instant input 86ms 0ms
14:14:57 | React to ERR_SPELL_OUT_OF_RANGE -- (5) Just wait for the target to get in range.
14:14:57 | ["Удар воина света"] instant usable: True->True \| current: False->False \| "NONE"->"ERR_SPELL_OUT_OF_RANGE"
14:14:57 | ["Удар воина света"] instant input 60ms 0.0001ms
14:14:57 | ["Exorcism" ] PrevGCD: 0ms \| GCD: 0ms \| Cast: 199ms \| Next spell -400ms
14:14:57 | ["Exorcism" ] instant usable: True->True \| current: False->True \| "NONE"->"CAST_START"
14:14:57 | ["Exorcism" ] instant input 84ms 0.0001ms
14:14:57 | ["Judgement" ] ... AfterCastDelay 25ms
14:14:57 | ["Judgement" ] PrevGCD: 0ms \| GCD: 0ms \| Cast: 316ms \| Next spell -400ms
14:14:57 | ["Judgement" ] instant usable: True->True \| current: False->True \| "NONE"->"CAST_START"
14:14:57 | ["Judgement" ] instant input 75ms 0.0001ms
14:14:57 | ["Judgement" ] ... GCD usable: True \| remain: 133ms \| -133.8368ms
14:14:56 | New Plan= " Combat"
14:14:55 | ["Judgement" ] Update "Mana" cost to 147 from 88
14:14:55 | ["Правосудие света"] Update "Mana" cost to 147 from 88
14:14:55 | New Plan= " Approach Target"
14:14:55 | ["Длань возмездия"] PrevGCD: 0ms \| GCD: 305ms \| Cast: 0ms \| Next spell -95ms
14:14:55 | ["Длань возмездия"] instant usable: True->True \| current: False->True \| "NONE"->"CAST_SUCCESS"
14:14:55 | ["Длань возмездия"] instant input 90ms 0.0001ms
14:14:55 | Stop auto interact!
14:14:55 | New Plan= " Pull Target"
14:14:55 | Found target!
14:14:55 | Pathfinder - 60.052532 - "<25,295898  -6031,7886  1,2081989>" -> "<28,689941  -5971,832  0>" 0.7294ms
14:14:55 | ["LocalPathingApi"] total distance 16.547516 > 100. Have to clear RouteToWaypoint.
14:14:55 | New Plan= " Follow Route"
14:14:55 | ["Judgement" ] Update "Mana" cost to 88 from 147
14:14:55 | ["Правосудие света"] Update "Mana" cost to 88 from 147
14:14:54 | New Plan= NO PLAN
14:14:54 | Total: 0 \| Remaining: 0
14:14:54 | New Plan= " Corpse Consumed"
14:14:54 | Safe to consume a corpse.
14:14:54 | New Plan= " Consume Corpse"
14:14:54 | ["Молот гнева" ] PrevGCD: 0ms \| GCD: 1500ms \| Cast: 0ms \| Next spell 1100ms
14:14:54 | ["Молот гнева" ] instant usable: False->False \| current: True->False \| "NONE"->"CAST_SUCCESS"
14:14:54 | ["Молот гнева" ] instant input 73ms 38.934ms
14:14:54 | Kill credit detected! Known kills: 1 \| Fighting with: 0
14:14:54 | ["Молот гнева" ] instant usable: True->False \| current: False->True \| "NONE"->"ERR_SPELL_FAILED_INTERRUPTED"
14:14:54 | ["Молот гнева" ] instant input 59ms 0.0005ms
14:14:54 | New Plan= " Combat"
14:14:53 | New Plan= NO PLAN
14:14:53 | Total: 0 \| Remaining: 0
14:14:53 | New Plan= " Corpse Consumed"
14:14:53 | Safe to consume a corpse.
14:14:53 | New Plan= " Consume Corpse"
14:14:53 | Kill credit detected! Known kills: 1 \| Fighting with: 1
14:14:52 | ["Божественная буря"] PrevGCD: 0ms \| GCD: 0ms \| Cast: 0ms \| Next spell -400ms
14:14:52 | ["Божественная буря"] instant usable: True->False \| current: False->True \| "NONE"->"CAST_SUCCESS"
14:14:52 | ["Божественная буря"] instant input 75ms 0ms
14:14:52 | ["Божественная буря"] ... GCD usable: True \| remain: 641ms \| -644.7393ms
14:14:50 | ["Божественная буря"] PrevGCD: 0ms \| GCD: 0ms \| Cast: 0ms \| Next spell -400ms
14:14:50 | ["Божественная буря"] instant usable: True->False \| current: False->True \| "NONE"->"CAST_START"
14:14:50 | ["Божественная буря"] instant input 75ms 0.0001ms
14:14:50 | ["Удар воина света"] PrevGCD: 0ms \| GCD: 0ms \| Cast: 0ms \| Next spell -400ms
14:14:50 | ["Удар воина света"] instant usable: True->True \| current: False->True \| "NONE"->"CAST_START"
14:14:50 | ["Удар воина света"] instant input 67ms 0.0001ms
14:14:50 | ["Удар воина света"] ... GCD usable: True \| remain: 308ms \| -308.0354ms
14:14:48 | ["Judgement" ] ... AfterCastDelay 25ms
14:14:48 | ["Judgement" ] PrevGCD: 1500ms \| GCD: 0ms \| Cast: 0ms \| Next spell 1100ms
14:14:48 | ["Judgement" ] instant usable: True->False \| current: False->True \| "NONE"->"CAST_SUCCESS"
14:14:48 | ["Judgement" ] instant input 90ms 0.0001ms
14:14:33 | 17 -> 18 "Huge Jaws"
14:14:32 | New Plan= NO PLAN
14:14:32 | ["Божественная буря"] PrevGCD: 0ms \| GCD: 0ms \| Cast: 0ms \| Next spell -400ms
14:14:32 | ["Божественная буря"] instant usable: True->False \| current: False->True \| "NONE"->"CAST_SUCCESS"
14:14:32 | ["Божественная буря"] instant input 75ms 0ms
14:14:32 | ["AutoAttack" ] instant input 59ms 59ms
14:14:32 | New Plan= " Combat"
14:14:32 | New Plan= NO PLAN
14:14:31 | Total: 0 \| Remaining: 0
14:14:31 | New Plan= " Corpse Consumed"
14:14:31 | Safe to consume a corpse.
14:14:31 | New Plan= " Consume Corpse"
14:14:31 | Lost target!
14:14:31 | Kill credit detected! Known kills: 1 \| Fighting with: 0
14:14:30 | Turning too fast!
14:14:30 | ["Удар воина света"] PrevGCD: 0ms \| GCD: 0ms \| Cast: 0ms \| Next spell -400ms
14:14:30 | ["Удар воина света"] instant usable: True->False \| current: False->True \| "NONE"->"ERR_BADATTACKFACING"
14:14:30 | ["Удар воина света"] instant input 59ms 0.0001ms
14:14:30 | React to ERR_BADATTACKFACING - Fast turn with Interact 162,2883ms
14:14:30 | ["Удар воина света"] instant usable: True->False \| current: False->True \| "NONE"->"ERR_BADATTACKFACING"
14:14:30 | ["Удар воина света"] instant input 75ms 0ms
14:14:28 | 15 -> 16 "Borean Leather Scraps"
14:14:27 | ["Удар воина света"] PrevGCD: 0ms \| GCD: 0ms \| Cast: 233ms \| Next spell -400ms
14:14:27 | ["Удар воина света"] instant usable: True->True \| current: False->True \| "NONE"->"CAST_START"
14:14:27 | ["Удар воина света"] instant input 83ms 0ms
14:14:26 | ["Judgement" ] ... AfterCastDelay 25ms
14:14:26 | ["Judgement" ] PrevGCD: 1500ms \| GCD: 0ms \| Cast: 0ms \| Next spell 1100ms
14:14:26 | ["Judgement" ] instant usable: True->False \| current: False->True \| "NONE"->"CAST_SUCCESS"
14:14:26 | ["Judgement" ] instant input 75ms 0.0001ms
14:14:25 | 5 -> 6 "Chilled Meat"
14:14:25 | 16 -> 17 "Huge Jaws"
14:14:24 | New Plan= NO PLAN
14:14:24 | ["AutoAttack" ] instant input 74ms 74ms
14:14:24 | New Plan= " Combat"
14:14:22 | New Plan= NO PLAN
14:14:22 | Total: 0 \| Remaining: 0
14:14:22 | New Plan= " Corpse Consumed"
14:14:22 | Safe to consume a corpse.
14:14:22 | New Plan= " Consume Corpse"
14:14:22 | Lost target!
14:14:22 | Kill credit detected! Known kills: 1 \| Fighting with: 1
14:14:22 | ["Божественная буря"] PrevGCD: 1500ms \| GCD: 66ms \| Cast: 0ms \| Next spell 1100ms
14:14:22 | ["Божественная буря"] instant usable: True->False \| current: False->True \| "NONE"->"CAST_SUCCESS"
14:14:22 | ["Божественная буря"] instant input 85ms 0.0001ms
14:14:20 | ["Удар воина света"] PrevGCD: 0ms \| GCD: 65ms \| Cast: 0ms \| Next spell -335ms
14:14:20 | ["Удар воина света"] instant usable: True->False \| current: False->True \| "NONE"->"CAST_SUCCESS"
14:14:20 | ["Удар воина света"] instant input 70ms 0ms
14:14:19 | ["Exorcism" ] PrevGCD: 1500ms \| GCD: 33ms \| Cast: 0ms \| Next spell 1100ms
14:14:19 | ["Exorcism" ] instant usable: True->False \| current: False->True \| "NONE"->"CAST_SUCCESS"
14:14:19 | ["Exorcism" ] instant input 63ms 0ms
14:14:17 | ["Judgement" ] ... AfterCastDelay 25ms
14:14:17 | ["Judgement" ] PrevGCD: 0ms \| GCD: 67ms \| Cast: 0ms \| Next spell -333ms
14:14:17 | ["Judgement" ] instant usable: True->False \| current: False->True \| "NONE"->"CAST_SUCCESS"
14:14:17 | ["Judgement" ] instant input 71ms 0ms

</body>
</html>

**Comment by Xian55** [comment]
👋 Hello there,

While the `ESC -> Options -> Control -> Enable Interact Key [x]` is enabled and fighting with multiple enemies in the same location sadly the game behaves somewhat unexpectedly.

While tried to reproduce the issue i've observed the followings:
* Fighting with multiple mobs at the same location.
* First enemy is killed. Depending on `Enable Interact Key` different scenarios going to happen.
* The player still in combat and awaits for the next enemy to become the player's primary target.
* ![image](https://github.com/Xian55/WowClassicGrindBot/assets/367101/22e24065-bc95-45d8-9cb0-78227bcb736b)
* However after the new target is acquired and pressing the `Interact` key, the player instead of start attacking the new target, its going to loot the previous dead one. I assume its because how the soft targeting system might have higher priority over a non sticky target?

---

I suggest to try to out with `ESC -> Options -> Control -> Enable Interact Key [ ]` disabled

![image](https://github.com/Xian55/WowClassicGrindBot/assets/367101/155da15c-19ac-4a95-ac9d-f343f36abb08)

**Comment by starnodes** [comment]
tnx, it works for me!

**Comment by Xian55** [comment]
Thanks for brining it to my attention. Have a gooday!
