### ISSUE TITLE
My bot, using a flying mount, begins to fly upward endlessly.

### ISSUE THREAD

**Issue by starnodes** [Xian55/WowClassicGrindBot#540]
### Description

My bot, using a flying mount, begins to fly upward endlessly. This happens periodically while grinding mobs along a route. This can happen in any location in Northrend. Bot just say "Random jump" and go up :)
In the logs I have attached the logs from the time of this bug. The target was found after I manually lowered the bot down.

### Addon Version

1.7.44

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

start bot
grind mobs using fly mount

### Logs

<html>
<body>

:35:30 | New Plan= " Pull Target"
-- | --
15:35:30 | Found target!
15:35:21 | Random jump
15:35:10 | Random jump
15:34:59 | Random jump
15:34:55 | Mounted ? True
15:34:55 | Cast ended 1527.7219ms
15:34:54 | Cast started 118.5305ms
15:34:54 | Mount up
15:34:54 | ["LocalPathingApi"] distance from nearlest point is 30.380526. Have to clear RouteToWaypoint.
15:34:54 | New Plan= " Follow Route"
15:34:54 | Total: 0 \| Remaining: 0
15:34:54 | New Plan= " Corpse Consumed"
15:34:53 | 10 -> 11 "Borean Leather Scraps"
15:34:52 | Loot Successful 666.2814ms
15:34:52 | Gathering Successful!
15:34:50 | Waiting for "Skinning" castbar to end! 1915ms
15:34:50 | Started casting or interrupted ? True - casting: True 235.7381ms
15:34:50 | Last Target found!
15:34:50 | + 1 "Icy Hoof"
15:34:50 | New Plan= " Skinning"
15:34:50 | Loot Successful 789.5249ms
15:34:49 | ["Judgement" ] Update "Mana" cost to 97 from 162
15:34:49 | ["Правосудие света"] Update "Mana" cost to 97 from 162
15:34:49 | Target Last Target Found!

</body>
</html>

**Comment by Xian55** [comment]
Hello there 👋 

Yes while in the `FollowRouteGoal` there's a randomly timed `Jump` keypress and sure it can align such a way that it seems your character is keep flying upwards endlessly.

Currently only the [IsFalling](https://wowwiki-archive.fandom.com/wiki/API_IsFalling) is used to determine if the player is not grounded. Probably its a good idea to combine with [IsFlying](https://wowwiki-archive.fandom.com/wiki/API_IsFlying).

With the existing logic, i should be able to prevent pressing `Jump` button while the player is in mid air, riding a flying mount.

I will take a look.

**Comment by Xian55** [comment]
Be sure to use Addon version **1.7.47** to check out if it solved the problem.

If you wish to adjust how much lift off is allowed from the ground i suggest to adjust the `Jump.PressDuration` you can set that in the `ClassConfig` by the following

```json
{
  //....
  "PathFilename": "_pack\\60-70\\Terokkar Forest\\62-64.json",
  "PathThereAndBack": false,
  "PathReduceSteps": true,
  //...
  "Jump":
  {
    "PressDuration": 200 // amount of time in milliseconds, randomized during runtime
  },
  //...
```

**Comment by starnodes** [comment]
> Be sure to use Addon version **1.7.47** to check out if it solved the problem.
> 
> If you wish to adjust how much lift off is allowed from the ground i suggest to adjust the `Jump.PressDuration` you can set that in the `ClassConfig` by the following
> 
> ```json
> {
>   //....
>   "PathFilename": "_pack\\60-70\\Terokkar Forest\\62-64.json",
>   "PathThereAndBack": false,
>   "PathReduceSteps": true,
>   //...
>   "Jump":
>   {
>     "PressDuration": 200 // maximum amount in milliseconds, randomized during runtime
>   },
>   //...
> ```

Thanks, I'll test the update.
