### ISSUE TITLE
Update to work with Season of Discovery

### ISSUE THREAD

**Issue by adamssullivan** [Xian55/WowClassicGrindBot#554]
Hello, looking to see if this will be updated to support the new abilities in Season of Discovery.

**Comment by Xian55** [comment]
Hello there!

Have you noticed any particular problem such as an nexception or error message?

What class you would prefer to play?

As you may know all the classes got extra abilites, passives and active. Without PTR it might take a long manual labour to level them up one by one and collect the runes to test them.

Im not planning to play to that intensively. So if you have a preference please let me know.

Last time i've checked i havent seen the new items added to the db2 database at wago.

It seems they updated the [spells](https://wago.tools/db2/SpellName?build=1.15.0.52409&filter[Name_lang]=Saber%20slash&page=1)

**Comment by Xian55** [comment]
I've just updated the local database with items and spells from Season of Discovery dataset
https://github.com/Xian55/WowClassicGrindBot/commit/6b0deff153c86e19eff8457601f1cc5eeb304196 already pushed to `dev` branch.

For me trying out with a Rogue which has a few runes, i did not experience any immediate errors. I assume its should work out of the box.

If you encounter any problem please feel free to let me know.

**Comment by adamssullivan** [comment]
I have not encountered any issues with spells. Thanks again for updating with spells.
