### ISSUE TITLE
Allowing game client to be on 2nd or 3rd monitor

### ISSUE THREAD

**Issue by adamssullivan** [Xian55/WowClassicGrindBot#560]
**Is your feature request related to a problem? Please describe.**
When setting up the program it will only detect the client window if it is on monitor 1

**Describe the solution you'd like**
I would like to either pick or have it auto-detect the client on any window

**Describe alternatives you've considered**
I do not see a way to accomplish this

**Additional context**

**Comment by Xian55** [comment]
Gooday,

That feature is supposed to be working. Be sure when you start the game move the game to the desired monitor. You can cycle between monitors by `WIN + SHIFT + Left Arrow`.

As long as the primary monitor and the desired monitor shares the same resolution and DPI settings, the `FrameConfig.json` should be working.

However there's one limitation. While the bot is running, currently you don't have the option to move the game window to another monitor.

Wait a moment, let me check this!

**Comment by Xian55** [comment]
When i did the refactor around WoWScreen, i forgot to account for this case. **DXGI** is more restricted then **CopyFromScreen** and requires explicit mention about the used Output/Monitor.

Let me know if it solves the issue at your end.

**Comment by adamssullivan** [comment]
That worked thanks!
