### ISSUE TITLE
Build Failed - No definition for WorldToMap?

### ISSUE THREAD

**Issue by thejefu** [Xian55/WowClassicGrindBot#568]
### Description

Looking forward to testing this out.

I think I followed the guidelines using V1 pathing, created the MPQ folder and attempted the build, but have received the following error.

Would appreciate any advice on if I've made a mistake or if there's a problem. Gonna give V3 pathing a try in the meantime.

PS D:\WoWBot> dotnet build -c Release
MSBuild version 17.9.4+90725d08d for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  WinAPI -> D:\WoWBot\WinAPI\bin\Release\net8.0\WinAPI.dll
  DataConfig -> D:\WoWBot\DataConfig\bin\Release\net8.0\DataConfig.dll
D:\WoWBot\SharedLib\Data\WorldMapAreaFactory.cs(14,108): error CS1061: 'DataConfig' does not contain a definition for '
WorldToMap' and no accessible extension method 'WorldToMap' accepting a first argument of type 'DataConfig' could be fo
und (are you missing a using directive or an assembly reference?) [D:\WoWBot\SharedLib\SharedLib.csproj]
D:\WoWBot\SharedLib\DataFrameConfig\DataFrameConfiguration.cs(39,31): warning CS8602: Dereference of a possibly null re
ference. [D:\WoWBot\SharedLib\SharedLib.csproj]
D:\WoWBot\SharedLib\DataFrameConfig\DataFrameConfiguration.cs(48,16): warning CS8602: Dereference of a possibly null re
ference. [D:\WoWBot\SharedLib\SharedLib.csproj]
D:\WoWBot\SharedLib\DataFrameConfig\DataFrameConfiguration.cs(57,17): warning CS8602: Dereference of a possibly null re
ference. [D:\WoWBot\SharedLib\SharedLib.csproj]
D:\WoWBot\SharedLib\Data\WorldMapAreaFactory.cs(27,18): warning CA1860: Prefer comparing 'Count' to 0 rather than using
 'Any()', both for clarity and for performance (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-r
ules/ca1860) [D:\WoWBot\SharedLib\SharedLib.csproj]
D:\WoWBot\SharedLib\DataFrameConfig\DataFrameConfiguration.cs(18,23): warning CA1852: Type 'DataFrameConfig' can be sea
led because it has no subtypes in its containing assembly and is not externally visible (https://learn.microsoft.com/do
tnet/fundamentals/code-analysis/quality-rules/ca1852) [D:\WoWBot\SharedLib\SharedLib.csproj]

Build FAILED.

D:\WoWBot\SharedLib\DataFrameConfig\DataFrameConfiguration.cs(39,31): warning CS8602: Dereference of a possibly null re
ference. [D:\WoWBot\SharedLib\SharedLib.csproj]
D:\WoWBot\SharedLib\DataFrameConfig\DataFrameConfiguration.cs(48,16): warning CS8602: Dereference of a possibly null re
ference. [D:\WoWBot\SharedLib\SharedLib.csproj]
D:\WoWBot\SharedLib\DataFrameConfig\DataFrameConfiguration.cs(57,17): warning CS8602: Dereference of a possibly null re
ference. [D:\WoWBot\SharedLib\SharedLib.csproj]
D:\WoWBot\SharedLib\Data\WorldMapAreaFactory.cs(27,18): warning CA1860: Prefer comparing 'Count' to 0 rather than using
 'Any()', both for clarity and for performance (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-r
ules/ca1860) [D:\WoWBot\SharedLib\SharedLib.csproj]
D:\WoWBot\SharedLib\DataFrameConfig\DataFrameConfiguration.cs(18,23): warning CA1852: Type 'DataFrameConfig' can be sea
led because it has no subtypes in its containing assembly and is not externally visible (https://learn.microsoft.com/do
tnet/fundamentals/code-analysis/quality-rules/ca1852) [D:\WoWBot\SharedLib\SharedLib.csproj]
D:\WoWBot\SharedLib\Data\WorldMapAreaFactory.cs(14,108): error CS1061: 'DataConfig' does not contain a definition for '
WorldToMap' and no accessible extension method 'WorldToMap' accepting a first argument of type 'DataConfig' could be fo
und (are you missing a using directive or an assembly reference?) [D:\WoWBot\SharedLib\SharedLib.csproj]
    5 Warning(s)
    1 Error(s)

Time Elapsed 00:00:04.79

### Addon Version

Unknown

### World of Warcraft Client

The Burning Crusade Classic

### Reproduction Steps

1. Extracted build
2. Installed .net
3. Put the 3 MPQ files into the json/MPQ
4. Attempted to build via powershell with: dotnet build -c Release

**Comment by Xian55** [comment]
Hey, `WorldMapAreaFactory.cs` is no longer part of the project.

I would recommend to clean up your local changes in git and be sure to pull down the `dev` branch then checkout the latest commit(54a7cda3f7132a3a6d59f74740ad87eb6ac1129f).

That compilation error should be resolved by itself.

**Comment by thejefu** [comment]
Did a fresh start and it resolved the issue. Thanks for the reply.
