### ISSUE TITLE
Bot will keep trying to skin over and over again.

### ISSUE THREAD

**Issue by adamssullivan** [Xian55/WowClassicGrindBot#571]
### Description

While in combat the bot will keep trying to skin over and over again until it just dies. 

### Addon Version

current

### World of Warcraft Client

SOD Classic

### Reproduction Steps

1. in combat with more than one mob that is skinnable. 
2. after the first kill it will try and skin the first mob until it dies or gets lucky

### Logs

[out20240215.log](https://github.com/Xian55/WowClassicGrindBot/files/14305738/out20240215.log)

**Comment by Xian55** [comment]
After #573 the situation should be improved! Its already in `dev` branch!

**Comment by adamssullivan** [comment]
This does seem to be better thanks

**Comment by Xian55** [comment]
Meanwhile i noticed a conflicting feature in the game itself.

In case you have killed a skinnable mob, and you are facing it and the soft targeting is enabled, once you press the interact button, the skinnable target going to be preferred over the other enemy which is engaged with you in combat.

In order to avoid the endless loop of attempting skinning and getting interrupted, the player has to face away from the corpse.

The previously mentioned situation can occur without using the bot. Sadly that's how the game is currently works

**Comment by Sattva-108** [comment]
Wouldn't it be easy fix to make him attempt to cast "Skinning" only once if bot is currently in combat? 
(Assuming no mobs left, should be fine?)

Or if that is too hard, then only skin after: 
1. Recently looted.
2. Combat ended.

I don't do any AOE farm, and I'm new to project. 
So please tell me if these methods are gonna break something. 

P.S: I really appreciate your recent update for bot skinning only eligible mobs.

**Comment by Xian55** [comment]
> Meanwhile i noticed a conflicting feature in the game itself.
> 
> In case you have killed a skinnable mob, and you are facing it and the soft targeting is enabled, once you press the interact button, the skinnable target going to be preferred over the other enemy which is engaged with you in combat.
> 
> In order to avoid the endless loop of attempting skinning and getting interrupted, the player has to face away from the corpse.
> 
> The previously mentioned situation can occur without using the bot. Sadly that's how the game is currently works

One you get familiar how the backend operates, its going to be more clear what i just explained here.

The project heavily relies on the interact with target feature which is a capability in the game.

However once soft targeting is enabled things can go wrong easily.

Interact with targert is used for turning the target if its in melee range as well.
