### ISSUE TITLE
Update addon for new items in SOD

### ISSUE THREAD

**Issue by adamssullivan** [Xian55/WowClassicGrindBot#578]
**Is your feature request related to a problem? Please describe.**
I am trying to automate quests in the new incursion event. Item is unknown ItemID 219770

**Describe the solution you'd like**
Adding New SOD items to addon

**Describe alternatives you've considered**
I tried to add a variable it still did not work

**Comment by Xian55** [comment]
Hello, 

Updated on `dev` branch with https://github.com/Xian55/WowClassicGrindBot/commit/aca2e5096ecc103b4ce850bf94e678669d18957c

Have a nice day!
