### ISSUE TITLE
Bug remote pathing trying to connect to IPv6 address along with IPv4

### ISSUE THREAD

**Issue by adamssullivan** [Xian55/WowClassicGrindBot#581]
### Description

When trying to set up Remote Pathing API v3 it is showing what looks like a IPv6 IP along with my IPv4 IP. 

### Addon Version

1.7.54

### World of Warcraft Client

Season of Mastery

### Reproduction Steps

Changed from the local host to the IP of the host running the server and it didn't change. Shows what looks like a combined IPv6 IP and IPv4 IP.

[08:04:04:623 E] [RemotePathingAPIV3] No connection could be made because the target machine actively refused it. [::ffff:192.168.2.2]:47110
[appsettings.json](https://github.com/Xian55/WowClassicGrindBot/files/15026818/appsettings.json)

### Last Good Version

unknown

### Logs

[out20240418.log](https://github.com/Xian55/WowClassicGrindBot/files/15026789/out20240418.log)

**Comment by Xian55** [comment]
Hello, does the RemoteV1 and RemoteV3 pathing services are running, and its unable to make connection ?

Or you just kind enough to let me know that something does not seems right ? 😄

**Comment by Xian55** [comment]
It seems like on your local network the ivp6 and ivp4 address are both enabled and ivp6 is the preferred one.

Unless you have a specific need or enforced to use ivp6 in your area, i recommend to completely disable ivp6. 

In the past i had lot of head aches about it and it was really painful for me to debug.

The fact that ivp6 meant to be the successor of ivp4, the adoption rate is really really slow.

**Comment by adamssullivan** [comment]
This was a setting on my computer. Windows 11 does default IPv6 as enabled in the LAN settings. I removed this and was able to use it. Thanks for your guidance.

**Comment by Xian55** [comment]
Im still using Windows 10.

So i have not tested, how the applications behave on Windows 11.

It might seem unprofessional to disable IPv6, but probably its the easiest way to solve the issue.
