### ISSUE TITLE
Add support for the Cataclysm Client

### ISSUE THREAD

**Issue by adamssullivan** [Xian55/WowClassicGrindBot#583]
**Is your feature request related to a problem? Please describe.**
When trying to setup the frame configuration it tells me: Unable to identify ClientVersion UnitRace and UnitClass!

**Describe the solution you'd like**
Would like to be updated to recognize the Cata Client

**Describe alternatives you've considered**
I do not belive there is anything that I can do to fix the issue

**Additional context**
![image](https://github.com/Xian55/WowClassicGrindBot/assets/3653097/7c2810a6-d1b8-4c1c-9108-1f02afc4ac14)

**Comment by Xian55** [comment]
Hey yea that's correct. The Client version is not known by the backend.

I've requested Beta access for a while ago however they did not granted me access yet.

Navigation wont work properly with LocalV1 pathfinder nor RemoteV3. None of them have supports the Cataclysm changed zones.

**Comment by adamssullivan** [comment]
Cataclysm pre-patch is out now so access would not be a problem. I found some Cataclysm mmap files that I was going to try with remoteV3 and see if they work.

**Comment by Xian55** [comment]
> Cataclysm pre-patch is out now so access would not be a problem

Thanks for the heads up!

> I found some Cataclysm mmap files that I was going to try with remoteV3 and see if they work.

I doubt its going to work. Upon loading the mmap files into RemoteV3, in each mmaps header file there's a [special magic string](https://github.com/Xian55/AmeisenNavigation/blob/master/AmeisenNavigation/src/AmeisenNavigation.hpp#L26) which validates whether the file is compatible with the navigation program. 

LocalV1 and RemoteV1 may _work_, however it depends on how much the zone has changed compare to vanilla map. The accuracy may be really poor.

**Comment by adamssullivan** [comment]
Is there something I can do to overcome the special magic string issue? The Vanilla overworld changes dramatically.

**Comment by Xian55** [comment]
I would not call this one an issue but rather a safeguard. To avoid unexpected incompatibility.

**Comment by Xian55** [comment]
I've started working on the [AmeisenNavigation](https://github.com/Xian55/AmeisenNavigation/tree/feature/multi-version-guess-z-coord) made a new branch for it `multi-version-guess-z-coord`.

It seems [Jnnshschl](https://github.com/Jnnshschl) was put in some effort to refactor the code of the [original AmeisenNavigation](https://github.com/Jnnshschl/AmeisenNavigation/tree/master). With a rough first iteration it seems to be working, it even shows way better loading times, almost instantly usable. Quite significant improvement!

The good news is that, AmeisenNavigation no longer requires Visual Studio 2019 but rather uses Visual Studio 2022.

To my luck TrinityCore project has made a branch for [cata_classic](https://github.com/TrinityCore/TrinityCore/tree/cata_classic) i specifically, think this would be convenient to bake **mmaps** for cataclysm client.

Frankly it seems the [v15 mmaps magic string remained](https://github.com/TrinityCore/TrinityCore/blob/cata_classic/src/common/Collision/Maps/MMapDefines.h), however i found it confusing how to actually extract the necessary data from the game files. I'm not familiar how to extract any of the game files after wotlk client which was using MPQ based file format.

**Comment by Xian55** [comment]
Little update, I've found a working [mmaps files](https://github.com/seobryn/cata-client-data/releases/download/v.10/FC_V10.zip) however these are meant to be used by private server, server side NPC movements. Players cannot follow these paths due slope limitation.

**Comment by Xian55** [comment]
Be sure to download the latest version. I suggest to read the following in order to be able to use the project in Cataclysm classic
* https://github.com/Xian55/WowClassicGrindBot/pull/586
* https://github.com/Xian55/WowClassicGrindBot?tab=readme-ov-file#supporting-cataclysm-classic-limitations
* https://github.com/Xian55/WowClassicGrindBot?tab=readme-ov-file#22-optional---using-v3-remote-pathing

As of now the PPather(V1 Local, V1 Remote pathfinder) project cannot be used for the Cataclysm changed zones, and i do not recommend to try them out, it may cause unpredictable behaviour. 

**Note**: the provided mmaps files for Cataclysm client was not created by me. At first glance it seems fine, however it might not be suitable for player movement. Once TrinityCore team progresses forward and their extractor tool is ready to process Cataclysm Classic client, i'm going to revisit how to improve the navmesh for the project. Until then expect may more stuck situation during navigation.

**Comment by adamssullivan** [comment]
Wow, thanks for all the hard work. You Rock!

**Comment by Xian55** [comment]
Hi i have to say that the current state of the wow classic client is a joke compare to vanilla tbc and wotlk combined.

**Comment by adamssullivan** [comment]
When trying to build the AmeisenNavigation.server I am getting 
![image](https://github.com/Xian55/WowClassicGrindBot/assets/3653097/f44599cd-a940-4680-8c66-02a1c78e5fca)

VS2022 with C++ I have build this in the past not sure what I am doing wrong. The addon is loading and is working. Just no navigation.

**Comment by Xian55** [comment]
Hi, navigate to solution explorer.

Right click on the AmeisenNavigation.Pack project and in click on Unload Project.

We dont need that project.

Sorry, i forgot to mention that.

You may have to do the same with the  Tester app.

**Comment by adamssullivan** [comment]
Hmm. Still getting that error. 
![image](https://github.com/Xian55/WowClassicGrindBot/assets/3653097/b23c5f2e-8e03-4a61-8b4c-f20ed2c26432)

**Comment by Xian55** [comment]
Hey can you disable the exporter as well

**Comment by Xian55** [comment]
Hold on, i got a busy day today, sorry for the late response. Let me see how i build the **AmeisenNavigation.Server**

![image](https://github.com/Xian55/WowClassicGrindBot/assets/367101/8534341c-0484-4e49-bf06-2fb9d9e30504)

I've only disabled the **AmeisenNavigation.Exporter** project.
Then i have some warnings in the build, but they are not breaking the build.

I've updated #585

**Comment by adamssullivan** [comment]
I was able to get this to build. I had to change some settings to 64bit for it to work. Thanks again.

**Comment by Xian55** [comment]
Oh sorry about that, i've forgot about that. Thanks for bringing it to my attention.
