### ISSUE TITLE
DK doesn't attack with abilities due most of the Rank 1 spells have been removed since Cataclysm

### ISSUE THREAD

**Issue by starnodes** [Xian55/WowClassicGrindBot#589]
### Description

Hello!
I play official Cataclysm Classic Version: 4.4.0.54737
I downloaded the latest version of the addon and it seems a lot has changed :)
I have 2 problems:
1) I tried to run the bot in AttendedGrind mode, but my dk just runs up to the target and hits him with a basic attack, then collects the skin.
2) Also, custom button changes stopped working for me.
 "TargetLastTargetKey": "F9",
 "InteractMouseOverKey": "F8",
 "InteractKey": "F7",
 "TargetTargetOfTargetKey": "F6",
 "TargetPetKey": "F12",
 "PetAttackKey": "F11",
 "TargetFocusKey": "F10",
Although I tried in different ways to change the configuration in accordance with the documentation update, nothing worked for me :) The bot simply pressed "I" instead of "F7".
I temporarily changed the settings in the game to test the work further.

My full config:

{
  "ClassName": "DeatkKnight",
  "TargetLastTargetKey": "F9",
  "InteractMouseOverKey": "F8",
  "InteractKey": "F7",
  "TargetTargetOfTargetKey": "F6",
  "TargetPetKey": "F12",
  "PetAttackKey": "F11",
  "TargetFocusKey": "F10",
  "MountKey": "-",
  "NPCMaxLevels_Below": 99,
  "NPCMaxLevels_Above": 99,
//  "Mode": "Grind",
//  "Mode": "AssistFocus",
  "Mode": "AttendedGrind",
  "Loot": true,
  "Skin": true,
  "KeyboardOnly": true,
  "PathFilename": "_pack\\70-80\\Zul'Drak\\76-80_Zul'Drak_Heb'Valok_spiders.json",
  "PathThereAndBack": false,
  "PathReduceSteps": true,
  "IntVariables": {
    "MIN_HP_FOOD%": 40,
    "MIN_RUNE_TO_DUMP": 40,
    "ITEM_CORPSE_DUST": 37201,
    "Debuff_Frost Fever": 237522,
    "Debuff_Blood Plague": 237514,
    "MIN_TIME_REFRESH": 3500
  },
 
  "Pull": {
    "Sequence": [
     {
        "Name": "Icy Touch",
        "Key": "5",
        "WhenUsable": true,
        "Requirements": [
          "!TargetCastingSpell",
          "!Frost Fever",
          "SpellInRange:0"
        ],
        "AfterCastAuraExpected": true,
        "AfterCastWaitCombat": true
      },
      {
        "Name": "Death Grip",
        "Key": "F1",
        "WhenUsable": true,
        "Requirements": [
          "SpellInRange:2",
          "!Falling"
        ],
        "AfterCastWaitCombat": true,
        "AfterCastWaitMeleeRange": true
      }
    ]
  },

  "Combat": {
    "Sequence": [
      {
        "Name": "Заморозка разума",
        "Key": "R",
        "WhenUsable": true,
        "Requirements": [
          "InMeleeRange",
          "TargetCastingSpell"
        ]
      },

      {
        "Name": "Death Strike",
        "Key": "3",
        "WhenUsable": true,
        "Requirements": [
          "InMeleeRange"
        ]
      },
      {
        "Name": "dnd", // macro /cast [@player] Death and Decay
        "Key": "V",
        "WhenUsable": true,
        "Requirements": [
          "MobCount > 2",
          "InMeleeRange"
        ]
      },

      {
        "Name": "Icy Touch",
        "Key": "5",
        "WhenUsable": true,
        "Requirements": [
          "!Frost Fever",
          "SpellInRange:0"
        ],
        "AfterCastAuraExpected": true
      },
      {
        "Name": "Удар в сердце",
        "Key": "4",
        "WhenUsable": true,
        "Cooldown": 2000,
        "Requirements": [
          "MobCount < 2",
          "Frost Fever",
          "Blood Plague",
          "InMeleeRange"
        ]
      },
      {
        "Name": "Pestilence",
        "Key": "E",
        "WhenUsable": true,
        "Requirements": [
          "MobCount > 2",
          "TargetHealth% <= 50 && (Frost Fever || Blood Plague)",
          "InMeleeRange"
        ]
      },
      {
        "Name": "Рунический удар",
        "Key": "2",
        "WhenUsable": true,
        "Requirements": [
          "RunicPower >= 60",
          "SpellInRange:1"
        ]
      },
      {
        "Name": "Plague Strike",
        "Key": "1",
        "WhenUsable": true,
        "Requirements": [
          "!Blood Plague",
          "InMeleeRange"
        ],
        "AfterCastAuraExpected": true
      },

      {
        "Name": "AutoAttack",
        "Requirements": [
          "!AutoAttacking"
        ]
      },
      {
        "Name": "Approach",
        "Log": false
      }
    ]
  },
  "Adhoc": {
    "Sequence": [
      {
        "Name": "Зимний горн",
        "Key": "7",
	"Cooldown": 60000,
        "Requirements": [
	 "!Mounted"
        ]
      },

      {
        "Name": "Food",
        "Key": "=",
        "Requirement": "Health% < MIN_HP_FOOD%"
      }
    ]
  },
}

### Addon Version

1.7.57

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

Description

### Logs

<html>
<body>

03:10:22 | 1 -> 2 "Roasted Beef"
-- | --
03:10:20 | Inactive, kill credit detected!
03:10:12 | ...
03:10:12 | New Plan= " Wait"
03:10:12 | Total: 0 \| Remaining: 0
03:10:12 | New Plan= " Corpse Consumed"
03:10:12 | [NpcNameFinder] type = "None" \| mode = "Fuzzy"
03:10:11 | + 2 "Savage Leather Scraps"
03:10:11 | 14 -> 20 "Savage Leather Scraps"
03:10:11 | Loot Successful 599.9702ms
03:10:10 | Gathering Successful!
03:10:09 | Waiting for "Skinning" castbar to end! 1915ms
03:10:09 | Started casting or interrupted ? True - casting: True 527.6697ms
03:10:09 | [I] press random 58ms
03:10:08 | + 1 "Split Hoof"
03:10:08 | New Plan= " Skinning"
03:10:08 | Loot Successful 0.0001ms
03:10:08 | [I] press random 51ms
03:10:08 | [I] press random 42ms
03:10:08 | Should gather 39588 ? True
03:10:08 | ["Interact"] I pressed 58ms
03:10:08 | [I] press random 58ms
03:10:08 | Keyboard soft target found!
03:10:08 | Look at possible closest corpse and try once again...
03:10:08 | [RightArrow] move Pressed 141ms
03:10:08 | [NpcNameFinder] type = "Corpse" \| mode = "Simple"
03:10:07 | Keyboard loot failed! Has target ? True
03:10:07 | ["ClearTarget"] Insert pressed 57ms
03:10:07 | [Insert] press random 57ms
03:10:07 | Keyboard Don't attack alive target!
03:10:07 | ["Interact"] I pressed 48ms
03:10:07 | [I] press random 48ms
03:10:07 | Keyboard soft target found!
03:10:07 | Keyboard last target found!
03:10:07 | ["TargetLastTarget"] G pressed 75ms
03:10:07 | [G] press random 75ms
03:10:07 | New Plan= " Loot"
03:10:07 | Safe to consume a corpse.
03:10:07 | New Plan= " Consume Corpse"
03:10:07 | Kill credit detected! Session Total: 1 \| Last Combat: 1 \| Currently fighting: 1
03:10:07 | ["Approach"] I pressed 38ms
03:10:07 | [I] press random 38ms
03:10:06 | ["Approach"] I pressed 26ms
03:10:06 | [I] press random 26ms
03:10:06 | ["Approach"] I pressed 10ms
03:10:06 | [I] press random 10ms
03:10:05 | ["Approach"] I pressed 30ms
03:10:05 | [I] press random 30ms
03:10:05 | ["Approach"] I pressed 16ms
03:10:05 | [I] press random 16ms
03:10:05 | ["Approach"] I pressed 13ms
03:10:05 | [I] press random 13ms
03:10:04 | ["Approach"] I pressed 25ms
03:10:04 | [I] press random 25ms
03:10:04 | ["Approach"] I pressed 38ms
03:10:04 | [I] press random 38ms
03:10:03 | ["Approach"] I pressed 12ms
03:10:03 | [I] press random 12ms
03:10:03 | ["Approach"] I pressed 21ms
03:10:03 | [I] press random 21ms
03:10:02 | ["Approach"] I pressed 27ms
03:10:02 | [I] press random 27ms
03:10:02 | ["Approach"] I pressed 20ms
03:10:02 | [I] press random 20ms
03:10:01 | ["Approach"] I pressed 33ms
03:10:01 | [I] press random 33ms
03:10:01 | ["Approach"] I pressed 14ms
03:10:01 | [I] press random 14ms
03:10:01 | ["Approach"] I pressed 38ms
03:10:01 | [I] press random 38ms
03:10:00 | ["Approach"] I pressed 13ms
03:10:00 | [I] press random 13ms
03:10:00 | ["Approach"] I pressed 24ms
03:10:00 | [I] press random 24ms
03:09:59 | ["Approach"] I pressed 17ms
03:09:59 | [I] press random 17ms
03:09:59 | ["Approach"] I pressed 14ms
03:09:59 | [I] press random 14ms
03:09:58 | ["Approach"] I pressed 29ms
03:09:58 | [I] press random 29ms
03:09:58 | ["Approach"] I pressed 32ms
03:09:58 | [I] press random 32ms
03:09:57 | ["Approach"] I pressed 35ms
03:09:57 | [I] press random 35ms
03:09:57 | ["Approach"] I pressed 30ms
03:09:57 | [I] press random 30ms
03:09:57 | ["Approach"] I pressed 19ms
03:09:57 | [I] press random 19ms
03:09:56 | ["Approach"] I pressed 14ms
03:09:56 | [I] press random 14ms
03:09:56 | ["Approach"] I pressed 11ms
03:09:56 | [I] press random 11ms
03:09:55 | ["Approach"] I pressed 27ms
03:09:55 | [I] press random 27ms
03:09:55 | ["Approach"] I pressed 34ms
03:09:55 | [I] press random 34ms
03:09:54 | ["Approach"] I pressed 33ms
03:09:54 | [I] press random 33ms
03:09:54 | ["Approach"] I pressed 21ms
03:09:54 | [I] press random 21ms
03:09:53 | ["Approach"] I pressed 25ms
03:09:53 | [I] press random 25ms
03:09:53 | ["Approach"] I pressed 23ms
03:09:53 | [I] press random 23ms
03:09:53 | ["Approach"] I pressed 12ms
03:09:53 | [I] press random 12ms
03:09:52 | ["Approach"] I pressed 34ms
03:09:52 | [I] press random 34ms
03:09:52 | ["Approach"] I pressed 32ms
03:09:52 | [I] press random 32ms
03:09:51 | ["Approach"] I pressed 28ms
03:09:51 | [I] press random 28ms
03:09:51 | ["Approach"] I pressed 25ms
03:09:51 | [I] press random 25ms
03:09:50 | ["Approach"] I pressed 34ms
03:09:50 | [I] press random 34ms
03:09:50 | ["Approach"] I pressed 28ms
03:09:50 | [I] press random 28ms
03:09:49 | ["Approach"] I pressed 34ms
03:09:49 | [I] press random 34ms
03:09:49 | ["Approach"] I pressed 16ms
03:09:49 | [I] press random 16ms
03:09:49 | ["Approach"] I pressed 32ms
03:09:49 | [I] press random 32ms
03:09:48 | ["Approach"] I pressed 21ms
03:09:48 | [I] press random 21ms
03:09:48 | ["Approach"] I pressed 11ms
03:09:48 | [I] press random 11ms
03:09:47 | ["Approach"] I pressed 11ms
03:09:47 | [I] press random 11ms
03:09:47 | ["Approach"] I pressed 31ms
03:09:47 | [I] press random 31ms
03:09:46 | ["Approach"] I pressed 12ms
03:09:46 | [I] press random 12ms
03:09:46 | ["Approach"] I pressed 34ms
03:09:46 | [I] press random 34ms
03:09:45 | ["Approach"] I pressed 20ms
03:09:45 | [I] press random 20ms
03:09:45 | ["Approach"] I pressed 35ms
03:09:45 | [I] press random 35ms
03:09:45 | ["Approach"] I pressed 29ms
03:09:45 | [I] press random 29ms
03:09:44 | ["Approach"] I pressed 16ms
03:09:44 | [I] press random 16ms
03:09:44 | ["Approach"] I pressed 17ms
03:09:44 | [I] press random 17ms
03:09:43 | ["Approach"] I pressed 21ms
03:09:43 | [I] press random 21ms
03:09:43 | ["Approach"] I pressed 33ms
03:09:43 | [I] press random 33ms
03:09:42 | ["Approach"] I pressed 28ms
03:09:42 | [I] press random 28ms
03:09:42 | ["Approach"] I pressed 19ms
03:09:42 | [I] press random 19ms
03:09:41 | ["Approach"] I pressed 39ms
03:09:41 | [I] press random 39ms
03:09:41 | ["Approach"] I pressed 36ms
03:09:41 | [I] press random 36ms
03:09:41 | ["Approach"] I pressed 17ms
03:09:41 | [I] press random 17ms
03:09:40 | ["Approach"] I pressed 38ms
03:09:40 | [I] press random 38ms
03:09:40 | New Plan= " Approach Target"
03:09:40 | Combat Enter
03:09:40 | ["Approach"] I pressed 16ms
03:09:40 | [I] press random 16ms
03:09:39 | ["Approach"] I pressed 28ms
03:09:39 | [I] press random 28ms
03:09:39 | ["Approach"] I pressed 12ms
03:09:39 | [I] press random 12ms
03:09:38 | ["Approach"] I pressed 30ms
03:09:38 | [I] press random 30ms
03:09:38 | ["Approach"] I pressed 17ms
03:09:38 | [I] press random 17ms
03:09:37 | ["Approach"] I pressed 13ms
03:09:37 | [I] press random 13ms
03:09:37 | ["Approach"] I pressed 21ms
03:09:37 | [I] press random 21ms
03:09:36 | ["Approach"] I pressed 16ms
03:09:36 | [I] press random 16ms
03:09:36 | ["Approach"] I pressed 37ms
03:09:36 | [I] press random 37ms
03:09:36 | ["StopAttack"] Delete pressed 37ms
03:09:36 | [Delete] press random 37ms
03:09:36 | Stop auto interact!
03:09:36 | New Plan= " Pull Target"
03:09:36 | ["Approach"] I pressed 14ms
03:09:36 | [I] press random 14ms
03:09:35 | ["TargetNearestTarget"] Tab pressed 50ms
03:09:35 | [Tab] press random 50ms
03:09:35 | ["Approach"] I pressed 39ms
03:09:35 | [I] press random 39ms
03:09:35 | New Plan= " Approach Target"
03:09:34 | ...
03:09:34 | New Plan= " Wait"
03:09:34 | ["Horn of Winter"] instant input 60ms "SPELL_FAILED_NOT_READY" -119.1235ms
03:09:34 | ["Horn of Winter"] D7 pressed 51ms
03:09:34 | [D7] press random 51ms
03:09:34 | ["Horn of Winter"] instant usable: True->False \| current: False->False \| "CAST_SUCCESS"->"CAST_SUCCESS"
03:09:34 | ["Horn of Winter"] D7 pressed 71ms
03:09:34 | [D7] press random 71ms
03:09:33 | New Plan= " Adhoc"
03:09:25 | Elapsed time: 63.9332 ms
03:09:25 | Thread stopped!
03:09:25 | Thread stopped!
03:09:25 | Thread stopped!
03:09:25 | ClassConfig: "DKNEW.json" with Path: "_pack\70-80\Zul'Drak\76-80_Zul'Drak_Heb'Valok_spiders.json"
03:09:25 | GatherCorpse limited to the last target. Rest going to be skipped!
03:09:25 | KeyboardOnly mode is enabled. Mouse based actions ignored.
03:09:25 | ["Food Buff" ] Requirement: ""Health% < 100""
03:09:25 | ["Food Buff" ] Requirement: ""Food""
03:09:25 | ["Food Buff" ] has no valid Key="" or ConsoleKey=None
03:09:25 | ["Wait"] Init KeyActions
03:09:25 | ["Food" ] Requirement: ""!Falling""
03:09:25 | ["Food" ] Requirement: ""!Swimming""
03:09:25 | ["Food" ] Requirement: ""!Food""
03:09:25 | ["Food" ] Requirement: ""Health% < MIN_HP_FOOD%""
03:09:25 | ["Food" ] Actionbar Key:"=" -> Actionbar:12 -> Index:11
03:09:25 | ["Horn of Winter"] Requirement: ""!Mounted""
03:09:25 | ["Horn of Winter"] Actionbar Key:"7" -> Actionbar:7 -> Index:6
03:09:25 | ["Adhoc"] Init KeyActions
03:09:25 | ["Approach" ] Non Actionbar "I" -> I
03:09:25 | ["AutoAttack" ] Requirement: ""!AutoAttacking""
03:09:25 | ["AutoAttack" ] Non Actionbar "I" -> I
03:09:25 | ["Plague Strike"] Requirement: ""InMeleeRange""
03:09:25 | ["Plague Strike"] Requirement: ""!Blood Plague""
03:09:25 | ["Plague Strike"] Actionbar Key:"1" -> Actionbar:1 -> Index:0
03:09:25 | ["Rune Strike" ] Requirement: ""SpellInRange:1""
03:09:25 | ["Rune Strike" ] Requirement: ""RunicPower >= 60""
03:09:25 | ["Rune Strike" ] Actionbar Key:"2" -> Actionbar:2 -> Index:1
03:09:25 | ["Pestilence" ] Requirement: ""InMeleeRange""
03:09:25 | ["Pestilence" ] Requirement: ""Blood Plague""
03:09:25 | ["Pestilence" ] Requirement: ""Frost Fever""
03:09:25 | ["Pestilence" ] Requirement: ""TargetHealth% <= 50""
03:09:25 | ["Pestilence" ] Requirement: ""MobCount > 2""
03:09:25 | ["Pestilence" ] Non Actionbar "E" -> E
03:09:25 | [Pestilence] Unable to assign Actionbar Slot!
03:09:25 | ["Heart Strike" ] Requirement: ""InMeleeRange""
03:09:25 | ["Heart Strike" ] Requirement: ""Blood Plague""
03:09:25 | ["Heart Strike" ] Requirement: ""Frost Fever""
03:09:25 | ["Heart Strike" ] Requirement: ""MobCount < 2""
03:09:25 | ["Heart Strike" ] Actionbar Key:"4" -> Actionbar:4 -> Index:3
03:09:25 | ["Icy Touch" ] Requirement: ""SpellInRange:0""
03:09:25 | ["Icy Touch" ] Requirement: ""!Frost Fever""
03:09:25 | ["Icy Touch" ] Actionbar Key:"5" -> Actionbar:5 -> Index:4
03:09:25 | ["dnd" ] Requirement: ""InMeleeRange""
03:09:25 | ["dnd" ] Requirement: ""MobCount > 2""
03:09:25 | ["dnd" ] Non Actionbar "V" -> V
03:09:25 | [dnd] Unable to assign Actionbar Slot!
03:09:25 | ["Death Strike" ] Requirement: ""InMeleeRange""
03:09:25 | ["Death Strike" ] Actionbar Key:"3" -> Actionbar:3 -> Index:2
03:09:25 | ["Mind Freeze" ] Requirement: ""TargetCastingSpell""
03:09:25 | ["Mind Freeze" ] Requirement: ""InMeleeRange""
03:09:25 | ["Mind Freeze" ] Non Actionbar "R" -> R
03:09:25 | [Mind Freeze] Unable to assign Actionbar Slot!
03:09:25 | ["Combat"] Init KeyActions
03:10:22 | 1 -> 2 "Roasted Beef"

</body>
</html>

**Comment by Xian55** [comment]
Hello, could you upload the log files ?

Just drag and drop into the comment.

it can be found next to the executable.

Please dont do any post processing of the logs.

I will look into it tomorrow. Thanks for bringing it to my attention.

Have a good day!

**Comment by Xian55** [comment]
> "TargetLastTargetKey": "F9",
> "InteractMouseOverKey": "F8",
> "InteractKey": "F7",

These wont work anymore. They are consolidated.

I would recommend to try this #553

If you experience something which does not work, i recommend to use the following serach keyword under the pull requests.

https://github.com/Xian55/WowClassicGrindBot/pulls?q=is%3Apr+is%3Aclosed+breaking+change

Every breaking changes what i made should be noted there.

**Comment by starnodes** [comment]
[out20240529_002.log](https://github.com/Xian55/WowClassicGrindBot/files/15477252/out20240529_002.log)

I first tried to use this format in the character configuration, but the bot stubbornly used the standard setting.
"Mount": { "Key": "N0" }

**Comment by Xian55** [comment]
Ye based on the logs the key mapping is wrong. 

I will look into it tomorrow.

**Comment by starnodes** [comment]
> Ye based on the logs the key mapping is wrong.
> 
> I will look into it tomorrow.

This is a really old key setting. I propose to start the investigation with the problem due to which my dk does not use abilities. And tomorrow I will upload a log with the key configuration from your recommendation.
Thank you!

**Comment by Xian55** [comment]
> [dnd] Unable to assign Actionbar Slot!
> [02:58:36:797 I] [dnd            ] Non Actionbar V -> V
> [02:58:36:798 W] [Pestilence] Unable to assign Actionbar Slot!
> [02:58:36:798 I] [Pestilence     ] Non Actionbar E -> E

These wont work. Based on the rules probably stuck at trying to use a key which is not bound to the acrionbar.

Currently the actionbar is fixed. Customization is not supported for actionbar.

Please look at the valid actionbar keys
https://github.com/Xian55/WowClassicGrindBot/blob/9216f25a75e873705b70b2f826363358f3ed33da/Core/ClassConfig/KeyReader.cs#L17

Either you add those E and V keys into the dictionaries.

Or you setup secondary keybinds in game for the actionbar slots.

When you setup the class config be sure to use valid ([F/N])0-9 keys.

Without these mapping the program will not know which actionbar slot to look for the usable and cost info. So its never going to use the given "E" and "V" mentioned spells.

**Comment by starnodes** [comment]
> > [dnd] Unable to assign Actionbar Slot!
> > [02:58:36:797 I] [dnd            ] Non Actionbar V -> V
> > [02:58:36:798 W] [Pestilence] Unable to assign Actionbar Slot!
> > [02:58:36:798 I] [Pestilence     ] Non Actionbar E -> E
> 
> These wont work. Based on the rules probably stuck at trying to use a key which is not bound to the acrionbar.
> 
> Currently the actionbar is fixed. Customization is not supported for actionbar.
> 
> Please look at the valid actionbar keys
> 
> https://github.com/Xian55/WowClassicGrindBot/blob/9216f25a75e873705b70b2f826363358f3ed33da/Core/ClassConfig/KeyReader.cs#L17
> 
> Either you add those E and V keys into the dictionaries.
> 
> Or you setup secondary keybinds in game for the actionbar slots.
> 
> When you setup the class config be sure to use valid ([F/N])0-9 keys.
> 
> Without these mapping the program will not know which actionbar slot to look for the usable and cost info. So its never going to use the given "E" and "V" mentioned spells.

I reassigned the keys, but my DK still attacks without abilities.

[DKNEW.json](https://github.com/Xian55/WowClassicGrindBot/files/15483303/DKNEW.json)

[out20240529.log](https://github.com/Xian55/WowClassicGrindBot/files/15483298/out20240529.log)

**Comment by Xian55** [comment]
It seems the bot unable to enter the `CombatGoal`, it stuck at the `ApproachTarget`

> [14:03:56:161 I] [GoapAgent      ] New Plan=  Approach Target

To enter `CombatGoal` specific conditions needs to met.

> AddPrecondition(GoapKey.incombat, true);
> AddPrecondition(GoapKey.hastarget, true);
> AddPrecondition(GoapKey.targetisalive, true);
> AddPrecondition(GoapKey.targethostile, true);
> AddPrecondition(GoapKey.incombatrange, true);

It might be that blizzard introduced some breaking changes regarding to these conditions, i will look at it later today.

**Comment by Xian55** [comment]
I can see the problem now, the spell ranges are not working at all.

During WOTLK the Icy Touch (Rank 1) spell id was [49903](https://www.wowhead.com/classic/spell=49903) which is no longer used in the Cataclysm client.

I will try to resolve this issue by using a different way to identify the spells no mater the game client version. Basically using the spell icons over the ids and looking up the spells from the spell book at startup.

**Comment by Xian55** [comment]
Spell ranges should be fixed, be sure to use the [Addon: 1.7.59] version. Get the latest `dev` branch and [follow this guide](https://github.com/Xian55/WowClassicGrindBot?tab=readme-ov-file#5-blazorserver-configuration-process).

For me changing the `Mount` works fine.

Overriding it the following way works.
```json
"Mount": { "Key": "N0"},
```
So the rest of the BaseAction keys should behave the same way. The BaseAction keys can be [found here](https://github.com/Xian55/WowClassicGrindBot/blob/dev/Core/ClassConfig/ClassConfigurationBaseActions.cs).

Let me know if you have further issue regarding to this.

TODO: remind myself to fix Druid Wrath Spell Icon ID, as its been changed from Wrath to Cata...

**Comment by starnodes** [comment]
Hello! ))
My bot often writes "[I] press random" and is bad at skinning animals. What could go wrong?
[out20240530_006.log](https://github.com/Xian55/WowClassicGrindBot/files/15503122/out20240530_006.log)

**Comment by Xian55** [comment]
Hey, 
> bad at skinning animals

Based on the logs i can see 
> Loot Failed 

3x times.

> Loot Successful

50x times.

So i'm not sure how to interpret this. A little bit more context would be helpful.

---

> My bot often writes "[I] press random"

That means it presses the [i] / interact button where the "press random" means that the `keydown press duration` is a random interval, you don't have to bother with that, that's just part of the implementation. There are a few places where exact keypress duration is used, like the character turning left right. The rest of the key presses are random in order to avoid using constant key presses.

Are you using custom keybinds ?

Without more context its ambiguous for me if that's a problem or not even with the provided logs i'm not sure what i'm supposed to look at.

Gooday

**Comment by starnodes** [comment]
> Hey,
> 
> > bad at skinning animals
> 
> Based on the logs i can see
> 
> > Loot Failed
> 
> 3x times.
> 
> > Loot Successful
> 
> 50x times.
> 
> So i'm not sure how to interpret this. A little bit more context would be helpful.
> 
> > My bot often writes "[I] press random"
> 
> That means it presses the [i] / interact button where the "press random" means that the `keydown press duration` is a random interval, you don't have to bother with that, that's just part of the implementation. There are a few places where exact keypress duration is used, like the character turning left right. The rest of the key presses are random in order to avoid using constant key presses.
> 
> Are you using custom keybinds ?
> 
> Without more context its ambiguous for me if that's a problem or not even with the provided logs i'm not sure what i'm supposed to look at.
> 
> Gooday

Thank you for your answer, I’ll keep watching for longer and report back with the results. At the moment I have only used numbers 1-9.0 for the key

**Comment by starnodes** [comment]
I also have a problem that I can’t get the bot to work on the 2nd monitor.
My main monitor is 3440 x 1440 and my second monitor is 1920 x 1080.
Before updating the bot (Version: 3.4.3.52237 Addon version: 1.7.47) it worked, but now it also stopped (Version: 4.4.0.54901 Addon version: 1.7.59)

**Comment by Xian55** [comment]
> My main monitor is 3440 x 1440 and my second monitor is 1920 x 1080.

I actually have the exact same setup. For me its working fine, i did some fixes a couple of months about it.
So i would require more info about you use case.

However this issue has not related to #589 so open about a new issue please.
