### ISSUE TITLE
Build - AmeisenNavigation.Pack.lib not found - AntTcp was built by different compiler

### ISSUE THREAD

**Issue by KevSchi** [Xian55/WowClassicGrindBot#592]
### Description

While building the AmeisenServer it closes due to not finding  
LNK1104	Datei "AmeisenNavigation.Pack.lib"  cant be opened

Cataclysm classic

### Addon Version

actual

### World of Warcraft Client

The Burning Crusade Classic

### Reproduction Steps

Just the standard Steps out of the readme

**Comment by Xian55** [comment]
Hello, be sure to follow the mentioned #585 guide about how to build it.

If you still having isses heres a x64 release binary.
 https://github.com/Xian55/WowClassicGrindBot/pull/585#issuecomment-2138428666

If you still ran into an issue please provide more info about your setup.

Like complilation errors.
Active projects
Target platform
Windows version

**Comment by KevSchi** [comment]
I followed every step. I had to download the AnTCP.Client nuget and placed it locally. The Exporter is unloaded 
![image](https://github.com/Xian55/WowClassicGrindBot/assets/66352672/879f4054-297a-4fe9-8e6f-f7fa3e470c9a)
When trying to build for debug or release the same error occurs 
![image](https://github.com/Xian55/WowClassicGrindBot/assets/66352672/9e6127f9-ecc3-4f03-ad08-b5077d24bcc3)

I wanted to modify the server a bit so thats why i wanted to build it on my own. 

It works with the precompiled binary but like i said i wanted to build it on my own :)

**Comment by Xian55** [comment]
Have you tried to build `AmeisenNavigation.Pack` project ?

I'm using the following settings for the Pack project
![image](https://github.com/Xian55/WowClassicGrindBot/assets/367101/6d74293f-ff27-44d3-8db1-ef931f3432ad)
![image](https://github.com/Xian55/WowClassicGrindBot/assets/367101/195f4be9-f990-498f-b60f-d82294a1d089)

Command line:
```
/permissive- /ifcOutput "build\x64\int\Release\" /GS /GL /W3 /Gy /Zc:wchar_t /Zi /Gm- /O2 /sdl /Fd"build\x64\Release\AmeisenNavigation.Pack.pdb" /Zc:inline /fp:precise /D "NDEBUG" /D "_CONSOLE" /D "_UNICODE" /D "UNICODE" /errorReport:prompt /WX- /Zc:forScope /Gd /Oi /MD /std:c++latest /FC /Fa"build\x64\int\Release\" /EHsc /nologo /Fo"build\x64\int\Release\" /Fp"build\x64\int\Release\AmeisenNavigation.Pack.pch" /diagnostics:column 
```

---

Be sure to set the `Set As Startup Project` as `AmeisenNavigation.Server`

**Comment by KevSchi** [comment]
I managed it by loading Exporter and trying to build it. After that, I got errors that my AntTcp was built by different compilers. I then unloaded it and built the .Server again. It worked that way. 

I also wanted to say thank you for your crazy project. I actually fell in love with what you are doing here. Also the support is crazy dude

**Comment by Xian55** [comment]
i've just checked out the repo from git, by default the target platform going to be `Any CPU`, which does not work.
![image](https://github.com/Xian55/WowClassicGrindBot/assets/367101/a681b913-8320-4e2f-a87c-cc299a0d3985)


Be sure to set the target platform either `x86` or `x64`
![image](https://github.com/Xian55/WowClassicGrindBot/assets/367101/ffe99428-4e0b-47fa-a853-e1d61df27908)

Set start up Project `AmeisenNavigation.Server`

The rebuild solution should work.

Note: For the final version be sure to use `Release`.

```log
Rebuild started at 11:52...
1>------ Rebuild All started: Project: AmeisenNavigation.Pack, Configuration: Debug x64 ------
2>------ Rebuild All started: Project: recastnavigation, Configuration: Debug x64 ------
Restored T:\help\AmeisenNavigation\AmeisenNavigation.Tester\AmeisenNavigation.Tester.csproj (in 12 ms).
1>miniz.c
2>DetourAlloc.cpp
2>DetourAssert.cpp
2>DetourCommon.cpp
2>DetourCrowd.cpp
2>DetourLocalBoundary.cpp
2>DetourNavMesh.cpp
1>AmeisenNavigation.Pack.vcxproj -> T:\help\AmeisenNavigation\AmeisenNavigation.Pack\build\x64\Debug\AmeisenNavigation.Pack.lib
2>DetourNavMeshBuilder.cpp
2>DetourNavMeshQuery.cpp
2>DetourNode.cpp
2>DetourObstacleAvoidance.cpp
2>DetourPathCorridor.cpp
2>DetourPathQueue.cpp
2>DetourProximityGrid.cpp
2>DetourTileCache.cpp
2>DetourTileCacheBuilder.cpp
2>Recast.cpp
2>RecastAlloc.cpp
2>RecastArea.cpp
2>RecastAssert.cpp
2>RecastContour.cpp
2>Generating Code...
2>Compiling...
2>RecastFilter.cpp
2>RecastLayers.cpp
2>RecastMesh.cpp
2>RecastMeshDetail.cpp
2>RecastRasterization.cpp
2>RecastRegion.cpp
2>Generating Code...
2>recastnavigation.vcxproj -> T:\help\AmeisenNavigation\recastnavigation\build\x64\Debug\recastnavigation.lib
3>------ Rebuild All started: Project: AmeisenNavigation, Configuration: Debug x64 ------
3>AmeisenNavigation.cpp
3>T:\help\AmeisenNavigation\AmeisenNavigation.Pack\src\Anp.hpp(83,85): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
3>T:\help\AmeisenNavigation\AmeisenNavigation\src\NavSources\Mmap\MmapNavSource.hpp(54,19): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
3>AmeisenNavigation.vcxproj -> T:\help\AmeisenNavigation\AmeisenNavigation\build\x64\Debug\AmeisenNavigation.lib
3>Done building project "AmeisenNavigation.vcxproj".
4>------ Rebuild All started: Project: AmeisenNavigation.Server, Configuration: Debug x64 ------
4>Main.cpp
4>T:\help\AmeisenNavigation\AmeisenNavigation.Pack\src\Anp.hpp(83,85): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
4>T:\help\AmeisenNavigation\AmeisenNavigation\src\NavSources\Mmap\MmapNavSource.hpp(54,19): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
4>AmeisenNavigation.Server.vcxproj -> T:\help\AmeisenNavigation\AmeisenNavigation.Server\build\x64\Debug\AmeisenNavigationServer.exe
4>Done building project "AmeisenNavigation.Server.vcxproj".
5>------ Rebuild All started: Project: AmeisenNavigation.Tester, Configuration: Debug Any CPU ------
5>AmeisenNavigation.Tester -> T:\help\AmeisenNavigation\AmeisenNavigation.Tester\bin\Debug\net8.0-windows7.0\AmeisenNavigation.Tester.dll
========== Rebuild All: 5 succeeded, 0 failed, 0 skipped ==========
========== Rebuild completed at 11:52 and took 09.785 seconds ==========
```

**Comment by KevSchi** [comment]
i forgot to say above that i also compiled for x64

but before the "fix" i was not be able to compile for x86 or x64

**Comment by Xian55** [comment]
As long as you learn something new and keeps you pushing forward, i think everyone is happy.  :)
