### ISSUE TITLE
Unhandled exception rendering component: Focus

### ISSUE THREAD

**Issue by starnodes** [Xian55/WowClassicGrindBot#594]
### Description

Hello! I'm try to play as hunter but got error:
[19:18:43:030 W] [RemoteRenderer ] Unhandled exception rendering component: Focus
System.NotImplementedException: Focus
* official cata classic

### Addon Version

1.7.59

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

start bot and got crash

### Logs

[out20240618.log](https://github.com/user-attachments/files/15889706/out20240618.log)

**Comment by Xian55** [comment]
Hello, gooday!

I will look into it, what's going on here.

Have a nice day!

**Comment by Xian55** [comment]
Should be fixed, let me know if you can reproduce the issue.
