### ISSUE TITLE
Why don't I have an option（Record Path） on the left?

### ISSUE THREAD

**Issue by cppbeliever** [Xian55/WowClassicGrindBot#598]
Why don't I have an option（Record Path） on the left?

![1111](https://github.com/Xian55/WowClassicGrindBot/assets/115885361/3e2f7feb-aa04-412d-a18d-4a05d9173869)

**Comment by Xian55** [comment]
Hello, first you have to load a Class Configuration. Any Class configuration will do. This is a requirement.

![image](https://github.com/Xian55/WowClassicGrindBot/assets/367101/ea0a3e21-4ee2-4d4b-a6f5-d392ce0fb617)

**Comment by cppbeliever** [comment]
@Xian55 
Thanks so much for your help bro, you're awesome.
