### ISSUE TITLE
Sell function Parameters ?

### ISSUE THREAD

**Issue by cppbeliever** [Xian55/WowClassicGrindBot#601]
@Xian55 

/tar Jannos Ironwill
/run DataToColor:sell();

If I want to sell all the grey items in the package, what should I fill in the Sell parameter?

**Comment by Xian55** [comment]
Hello.

The name of the items, in list.

example: https://github.com/Xian55/WowClassicGrindBot/pull/562

**Comment by cppbeliever** [comment]
> Hello.
> 
> The name of the items, in list.
> 
> example: #562

There are so many grey items. It is impossible to manually input all the grey item lists into the sell function, right?

**Comment by Xian55** [comment]
The addon supposed to sell all the grey items. 
https://github.com/Xian55/WowClassicGrindBot/blob/dev/Addons/DataToColor/SellJunk.lua

**Comment by cppbeliever** [comment]
> The addon supposed to sell all the grey items. https://github.com/Xian55/WowClassicGrindBot/blob/dev/Addons/DataToColor/SellJunk.lua

thanks!
