### ISSUE TITLE
The backpack is full, but the vendor is not triggered

### ISSUE THREAD

**Issue by cppbeliever** [Xian55/WowClassicGrindBot#604]
### Description

The backpack is full, but the vendor is not triggered.The robot will continue to kill the monsters.

### Addon Version

1.7.57

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

I remember selling white items to merchants manually.

### Screenshots

![notsell](https://github.com/Xian55/WowClassicGrindBot/assets/115885361/c750a45c-1f74-48a9-b546-526a82409125)

### Logs

BlazorServer Log:

[out20240708_003.log](https://github.com/user-attachments/files/16125409/out20240708_003.log)

HeadLessServer log:

[headless_out20240708.log](https://github.com/user-attachments/files/16125420/headless_out20240708.log)

class/json:

[Mage_Gnome_10-12.json](https://github.com/user-attachments/files/16125428/Mage_Gnome_10-12.json)

class/path:

[Loch_Modan_SaiErSaMa_Vendor.json](https://github.com/user-attachments/files/16125438/Loch_Modan_SaiErSaMa_Vendor.json)

BindPad macro:

/tar 雅尼·铁心
/run SellJunkFunc()

**Comment by Xian55** [comment]
The built in sell junk function only works if the follow conditions are met

```json
{
  "Cost": 6,
  "Name": "Sell",
  "Key": "C",
  "Requirements": [
    "BagFull",
    "BagGreyItem"
  ],
  "PathFilename": "Loch_Modan_SaiErSaMa_Vendor.json"
}
```

Where the `Requirements` are mentioned in the [readme.md](https://github.com/Xian55/WowClassicGrindBot?tab=readme-ov-file#buff--debuff--general-boolean-condition-requirements). It is worth to mention that the action going to only run when both requirements are met, since they are using `and`/`&&` operator.

> "BagGreyItem" | Indicates that there are at least one Grey Quality level item.

At first glance of the image, it seems you have only common items(white) or the bagitems are not getting properly extracted by the c# backend.

**Comment by cppbeliever** [comment]
> The built in sell junk function only works if the follow conditions are met
> 
> ```json
> {
>   "Cost": 6,
>   "Name": "Sell",
>   "Key": "C",
>   "Requirements": [
>     "BagFull",
>     "BagGreyItem"
>   ],
>   "PathFilename": "Loch_Modan_SaiErSaMa_Vendor.json"
> }
> ```
> 
> Where the `Requirements` are mentioned in the [readme.md](https://github.com/Xian55/WowClassicGrindBot?tab=readme-ov-file#buff--debuff--general-boolean-condition-requirements). It is worth to mention that the action going to only run when both requirements are met, since they are using `and`/`&&` operator.
> 
> > "BagGreyItem" | Indicates that there are at least one Grey Quality level item.
> 
> At first glance of the image, it seems you have only common items(white) or the bagitems are not getting properly extracted by the c# backend.

Thank you for your reply. I feel that this is indeed the problem. I can vendor it by deleting "BagGreyItem".

**Comment by Xian55** [comment]
> I can vendor it by deleting "BagGreyItem".

No, not really, you have to use another third party addon if you want to sell non grey items such ash common or uncommon items.

The built in functionality only cares about grey items which are safe to sell at any point in time.

If your bag is full and you remove the `"BagGreyItem"` and there's no grey item in your bag, then your character most likely get stuck at the vendor NPC indefinitely.
