### ISSUE TITLE
Questions about Stormlib

### ISSUE THREAD

**Issue by cppbeliever** [Xian55/WowClassicGrindBot#608]
### Description

What is the purpose of the Precompiled x86 and x64 Stormlib you mentioned in the rule (Using V1 Local/Remote Pathing)?

Does your intention mean that I should use Stormlib to read the map information in the file (WOTLK: lichking.MPQ (2.5Gb)) for navigation?

### Addon Version

1.7.57

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

no

### Screenshots

no

### Logs

no

**Comment by Xian55** [comment]
Thats correct.

The original author of the project was used the existing way as is.

Using the precompiled dll of stormlib.

If you are not trusting the precompiled stormlib source feel free to compile it yourself.

The V1 pathfinder is based on the stormlib which works till Warth of the Lich King expansion.

After that they switched from mpq to casc which im not familiar with and seems tediius to setup, decryption is still in progress for classic client to my knowledge.

If you have a proposal to make the reliance of stormlib easier to use, im all ears.


Gooday

**Comment by Xian55** [comment]
Also the v1 pathfinder uses "ppather" which was written by someboy over 10 years ago.

Last year i took the time to modernize it from C# side. Applying modern memory management techniques such as stackalloc and ArrayPool ing.

On the other hand i rewrote the data streaming from the mpq's into memory avoiding a bottleneck by using temporary disk access.

Reducing total compute time and more efficient memory usage.

**Comment by cppbeliever** [comment]
I am currently considering using V1 Local and not RemoteV3 for the time being. So, I start Blazor Server first, and then use the command (.\run.bat Mage_Gnome_14-18.json -m Local -r DXGI) to start HeadLessServer, and receive the following error:

"fileName - World\Maps\Azeroth\Azeroth.wdt"

Blazor Server Log:
[out20240710.log](https://github.com/user-attachments/files/16146714/out20240710.log)

HeadBlessServer Log:
[headless_out20240710.log](https://github.com/user-attachments/files/16146725/headless_out20240710.log)

I got this error, I think it was the precompiled stormlib and it didn't read the map data in lichking.MPQ (WowClassicGrindBot-dev\Json\MPQ).

**Comment by Xian55** [comment]
V1 pathfinder / ppather works decently well in vanilla + TBC + Wrath.

[Instructions to install V1](https://github.com/Xian55/WowClassicGrindBot?tab=readme-ov-file#21-using-v1-localremote-pathing)

Under the `WowClassicGrindBot\Json\MPQ` folder there has to be the following files:
* `common-2.MPQ`
* `expansion.MPQ`
* `lichking.MPQ`

Has to exists in order to make it working for Wrath expansion.

**Comment by cppbeliever** [comment]
Because my client is WLK, I only downloaded lichking.MPQ, next  I also downloaded the other two mpq files.
