### ISSUE TITLE
Combat Problems

### ISSUE THREAD

**Issue by cppbeliever** [Xian55/WowClassicGrindBot#610]
Hello, xian55.
Does your bot have this problem:
My character (Mage) used Frost Arrow to pull the first mob to kill, and during the battle, my character attracted the second mob to attack me from behind. After I killed the first mob, the Mage would not turn around to kill the second mob.

**Comment by Xian55** [comment]
Duplicated https://github.com/Xian55/WowClassicGrindBot/issues/570

**Comment by cppbeliever** [comment]
My situation was different from his. When the monsters attacked me from behind, my character was not idle. My character kept trying to shoot ice arrows, but failed because I was facing away from the monsters.

**Comment by Xian55** [comment]
Based on the description what you given for me essentially the same, unless you provide logs i won't treat differently.

**Comment by cppbeliever** [comment]
It happened at 23:04:56. I don't know if it was caused by this annoying negative number problem.

[out20240721.log](https://github.com/user-attachments/files/16325011/out20240721.log)

**Comment by Xian55** [comment]
Based on what i'm seeing is that, the addon and the backend cannot work properly due the keypresses feedback does not seems to reliably get back to the backend.

```shell
   1047  [18:37:30:954 D] [ConfigurableInput] [寒冰箭] D1 pressed 71ms
   1048: [18:37:30:954 I] [ReactCastError ] React to ERR_SPELL_COOLDOWN -- wait until its ready
   1049  [18:37:31:266 I] [CombatGoal     ] Lost target!

   3763  [18:47:39:934 D] [ConfigurableInput] [寒冰箭] D1 pressed 67ms
   3764: [18:47:39:934 I] [ReactCastError ] React to CAST_SUCCESS -- wait until its ready
   3765  [18:47:40:306 I] [CombatGoal     ] Lost target!

  14770  [19:22:15:069 I] [WowProcessInput] [I] press random 31ms
  14771: [19:22:15:194 W] [ReactCastError ] Unable to react to ERR_BADATTACKFACING - Fast turn with Interact 0.0004ms
  14772  [19:22:15:240 I] [WowProcessInput] [Delete] press random 43ms
  14773  [19:22:15:240 V] [ConfigurableInput] [StopAttack] Delete pressed 43ms
  14774: [19:22:15:240 I] [ReactCastError ] React to ERR_BADATTACKFACING - Slow turn 180deg
  14775  [19:22:15:240 I] [CombatGoal     ] Lost target!

  16275  [19:27:51:458 D] [ConfigurableInput] [寒冰箭] D1 pressed 77ms
  16276: [19:27:51:458 I] [ReactCastError ] React to CAST_SUCCESS -- wait until its ready
  16277  [19:27:51:471 I] [GoapAgent      ] New Plan=  Consume Corpse

  18107  [19:33:53:453 D] [ConfigurableInput] [寒冰箭] D1 pressed 50ms
  18108: [19:33:53:453 I] [ReactCastError ] React to CAST_SUCCESS -- wait until its ready
  18109  [19:33:53:468 I] [GoapAgent      ] New Plan=  Consume Corpse

  18996  [19:36:43:782 D] [ConfigurableInput] [寒冰屏障] D4 pressed 59ms
  18997: [19:36:43:782 I] [ReactCastError ] React to ERR_SPELL_COOLDOWN -- wait until its ready
  18998  [19:36:44:093 I] [CombatGoal     ] Lost target!

  23015  [19:48:04:321 D] [ConfigurableInput] [寒冰箭] D1 pressed 66ms
  23016: [19:48:04:321 I] [ReactCastError ] React to ERR_SPELL_COOLDOWN -- wait until its ready
  23017  [19:48:04:321 I] [CombatGoal     ] Lost target!

  33328  [20:59:43:376 D] [ConfigurableInput] [寒冰屏障] D4 pressed 68ms
  33329: [20:59:43:377 I] [ReactCastError ] React to SPELL_FAILED_NOT_READY -- wait until its ready
  33330  [20:59:43:377 I] [CombatGoal     ] Lost target!

  33905  [21:01:43:518 I] [WowProcessInput] [I] press random 42ms
  33906: [21:01:43:626 W] [ReactCastError ] Unable to react to ERR_BADATTACKFACING - Fast turn with Interact 0.0001ms
  33907  [21:01:43:673 I] [WowProcessInput] [Delete] press random 34ms
  33908  [21:01:43:673 V] [ConfigurableInput] [StopAttack] Delete pressed 34ms
  33909: [21:01:43:674 I] [ReactCastError ] React to ERR_BADATTACKFACING - Slow turn 180deg
  33910  [21:01:43:674 I] [CombatGoal     ] Lost target!

  34207  [21:04:14:931 I] [WowProcessInput] [I] press random 40ms
  34208: [21:04:15:040 W] [ReactCastError ] Unable to react to ERR_BADATTACKFACING - Fast turn with Interact 0.0002ms
  34209  [21:04:15:103 I] [WowProcessInput] [Delete] press random 58ms
  34210  [21:04:15:103 V] [ConfigurableInput] [StopAttack] Delete pressed 58ms
  34211: [21:04:15:104 I] [ReactCastError ] React to ERR_BADATTACKFACING - Slow turn 180deg
  34212  [21:04:15:104 I] [CombatGoal     ] Lost target!

  40617  [21:28:20:830 I] [WowProcessInput] [I] press random 42ms
  40618: [21:28:20:927 W] [ReactCastError ] Unable to react to ERR_BADATTACKFACING - Fast turn with Interact 0.0004ms
  40619  [21:28:20:986 I] [WowProcessInput] [Delete] press random 45ms
  40620  [21:28:20:986 V] [ConfigurableInput] [StopAttack] Delete pressed 45ms
  40621: [21:28:20:987 I] [ReactCastError ] React to ERR_BADATTACKFACING - Slow turn 180deg
  40622  [21:28:20:987 I] [CombatGoal     ] Lost target!

  46393  [21:50:08:497 D] [ConfigurableInput] [寒冰箭] D1 pressed 59ms
  46394: [21:50:08:497 I] [ReactCastError ] React to CAST_SUCCESS -- wait until its ready
  46395  [21:50:08:510 I] [GoapAgent      ] New Plan=  Consume Corpse

  62977  [22:44:53:124 D] [ConfigurableInput] [寒冰箭] D1 pressed 61ms
  62978: [22:44:53:124 I] [ReactCastError ] React to CAST_SUCCESS -- wait until its ready
  62979  [22:44:53:498 I] [CombatGoal     ] Lost target!
  ```

The **ReactCastError** component is responsible to handle any issues what the game error notification presents, however it is clear for me that this issue is caused by the negative numbers in the **CastingHandler**.

The following code snippet ensures that if the player unable to cast on the target then [its going to attempt to turn fast if it can, otherwise falls back to slowly turning](https://github.com/Xian55/WowClassicGrindBot/blob/db048b61af2c3c4f5c983046a85715ef09149359/Core/GoalsComponent/ReactCastError.cs#L185)

It's hard to say why it happens, i can only guess, but most likely i wont be able to figure out what's going on without myself inspecting your machine.

**Comment by cppbeliever** [comment]
Previously you told me to fix the negative number problem by recreating the framework, but I recreated the framework exactly as instructed and the negative number problem persists.

**Comment by Xian55** [comment]
> fix the negative number problem by recreating the framework, but I recreated the framework exactly as instructed and the negative number problem persists

I understand that. For me when such issues happened regarding the negative numbers, usually managed to resolve the problem by creating a new frame config. 

However, i just cannot handle every customization what every person could make on their system.

The best support what i can offer is to invite you to a discord server, were more personal investigation can be conducted. However i'm just a little afraid that our language barrier would be too big of a problem to make meaningful progress in the matter.

**Comment by cppbeliever** [comment]
@Xian55  thanks for your response.

**Comment by Xian55** [comment]
Hello @cppbeliever

I just want to let you know that on the latest version of `dev` branch, i did some changes which might help you investigate better why might the bot unable to read the input feedback from the game.

Be sure to check the at least this version: https://github.com/Xian55/WowClassicGrindBot/pull/617
* Addon: [1.7.60]
* There are further commits such as 2da1ae148e6abcd0f419a14483d96ad7010c0330, this version seems to be stable.

Have a good day!
