### ISSUE TITLE
support dungeon

### ISSUE THREAD

**Issue by cppbeliever** [Xian55/WowClassicGrindBot#612]
Does Pixel Robot support dungeons?
1. If not, why?
2. If it does, thank you for providing me with ideas

**Comment by Xian55** [comment]
Hello

Duplicated, you can learn more about it by reading the following issues:
* https://github.com/Xian55/WowClassicGrindBot/issues?q=dungeon+instance
* https://github.com/Xian55/WowClassicGrindBot/issues/265
* https://github.com/Xian55/WowClassicGrindBot/issues/344
* https://github.com/Xian55/WowClassicGrindBot/issues/449
