### ISSUE TITLE
Could not find a part of the path 'C:\WowClassicGrindBot\json\MPQ'

### ISSUE THREAD

**Issue by 0Ezic0** [Xian55/WowClassicGrindBot#615]
### Description

Im stuck at 5. BlazorServer Configuration process
cuz this error occurs

### Addon Version

1.2.3

### World of Warcraft Client

Season of Mastery

### Reproduction Steps

![image](https://github.com/user-attachments/assets/a3911cde-040a-4cf2-97fd-4affbeb95a28)

**Comment by Xian55** [comment]
Hello, please follow [Getting it working](https://github.com/Xian55/WowClassicGrindBot?tab=readme-ov-file#getting-it-working)

**Comment by 0Ezic0** [comment]
C:\WowClassicGrindBot\Json\MPQ
The MPQ has to be a folder or just the file i need to download?

**Comment by Xian55** [comment]
![image](https://github.com/user-attachments/assets/ee0c08ab-b113-436e-afb9-b0ea03c332b8)

**Comment by 0Ezic0** [comment]
Ok ty! Im dumb <3
