### ISSUE TITLE
Hunter sumpet macro

### ISSUE THREAD

**Issue by keviny86** [Xian55/WowClassicGrindBot#621]
### Description

I can't get the sumpet macro to work, anyone got it to work? Pet is dead and cant be targeted.

```
#showtooltip
/cast [target=pet,dead] Revive Pet
/cast [target=pet,noexists] Call Pet
```

### Addon Version

dev

### World of Warcraft Client

World of Warcraft Classic

### Reproduction Steps

1. Add the sumpet macro.
2. Make sure pet is dead.
3. Press the macro.

**Comment by Xian55** [comment]
Hello,
I assume you are took an example from a higher level hunter profile such as [hunter_66_farm_pet_pull.json](https://github.com/Xian55/WowClassicGrindBot/blob/f3b3b6e7f4ed788df988a21ffab067df43687f95/Json/class/Hunter_66_farm_pet_pull.json#L253).

Based on that you can extend the existing logic by adding `PetHealth% == 1`. Which means the pet is dead.

due the [formula](https://github.com/Xian55/WowClassicGrindBot/blob/f3b3b6e7f4ed788df988a21ffab067df43687f95/Core/Addon/PlayerReader.cs#L138)
```cs
public int PetHealthPercent() => (1 + PetHealth()) * 100 / (1 + PetMaxHealth());
```

Based on that the following should cover for both cases for the macro statements.

```json
{
  "Name": "sumpet",
  "Key": "N6",
  "HasCastBar": true,
  "Cooldown": 4000,
  "Requirements": [
    "!Has Pet || PetHealth% == 1",
    "!Mounted"
  ]
}
```

I have not tested it. 

Let me know if you further struggle with the issue.

Gooday!

**Comment by keviny86** [comment]
Still not working, i think the issue is with the macro,` /cast [target=pet,dead] Revive Pet` here it want to target pet and check if its dead, but the pet can be dead and not targable (not summoned)

**Comment by Xian55** [comment]
I did some test after your feedback.

```json
{
  "Name": "sumpet",
  "Key": "N6",
  "HasCastBar": true,
  "AfterCastWaitCastbar": true,
  "Cooldown": 4000,
  "Requirements": [
    "!Has Pet || PetHealth% == 1",
    "!Mounted"
  ]
}
```

After adding `"AfterCastWaitCastbar": true,` `Revive Pet` spell won't be prematurely interrupted.

On the other hand, provided macro works fine for both scenarios
* Call Pet
* Revive Pet

I've did my test on Classic Era PTR version 1.15.4 (56857)

---

You have to provide more evidence - like Logs from either(HeadlessServer or BlazorServer) - beside your repro steps in order to understand your problem.

On the other hand i don't see any kind of issue regarding the WowClassicGrindBot it self. 

Creating suitable macros is outside of the project scope. All of the examples what's shown suggestion for probable application. 

In Game behaviour is subject to change by the developers by each update.

**Comment by keviny86** [comment]
Is there a way to in Adhoc to call revive pet and if it fails just move on, i tried it but it get stuck on trying to revive.

Try it when pet is dead and cant be targeted.

**Comment by Xian55** [comment]
I'm sorry i cannot help you if you are not willing to provide what you did to resolve your problem.

Please be more specific about your problem, i cannot understand what you mean by 

> Try it when pet is dead and cant be targeted.

[What i've tried in in pas comment](https://github.com/Xian55/WowClassicGrindBot/issues/621#issuecomment-2408668634) and also extending the case with the repro case bellow

1. I let my pet die
1. I went far away(100 yard) from my pet corpse to unable to target it.
1. pressed the macro
1. My character started casting `Revive Pet` spell after the cast ended the pet got alive.

did no difference between my repro case outcome.

**Comment by keviny86** [comment]
Does not work.. i manged to fix it with this:

```
  "Adhoc": {
    "Sequence": [
      {
        "Name": "Call Pet",
        "Key": "N1",
        "Requirements": [
          "Spell:Call Pet",
          "!Has Pet"
        ]
      },
      {
        "Name": "Revive Pet",
        "Key": "N2",
        "HasCastBar": true,
        "AfterCastWaitCastbar": true,
        "Cooldown": 4000,
        "Requirements": [
          "Spell:Revive Pet",
          "!Has Pet"
        ]
      }
   ]
}
```

**Comment by Xian55** [comment]
Hello, I see you split into two actions.

I guess that's works fine as well, however it may results a few seconds downtime after call your pet, as it may attempt to press the `Revive Pet` as well.

You can avoid that by extending the conditions

```json
      {
        "Name": "Revive Pet",
        "Key": "N2",
        "HasCastBar": true,
        "AfterCastWaitCastbar": true,
        "Cooldown": 4000,
        "Requirements": [
          "Spell:Revive Pet",
          "Has Pet && PetHealth% == 1"
        ]
      }
```

Gooday!
