### ISSUE TITLE
Add a way to use potion and spells before Flee

### ISSUE THREAD

**Issue by lionaneesh** [Xian55/WowClassicGrindBot#644]
for example: A mage is at 30% hp and suddenly aggro by 1 more mob. Then it starts to flee and it want to cast FrostNova and Pop a healing potion before starting to navigate. As this will improve the chances of escaping a lot.

**Comment by Xian55** [comment]
Gooday, its a good idea, and its somewhat easy to incorporate, well at least adding the most basic support to be able to use any KeyActions while the `FleeGoal` is active.

Added with #645 

Here's a snippet which allows you achieve your goal.
its important to keep in mind that the first action called `Flee` is important to remain as its used for the `FleeGoal` condition to be executed at all.

```json
"Flee": {
  "Sequence": [
    {
      "Name": "Flee",
      "Requirement": "MobCount > 1" //&& Health% < 50
    },
    {
      "Name": "Frost Nova",
      "Key": 6,
      "Requirement": "InMeleeRange"
    },
    {
      "Name": "HP Potion",
      "Key": 7,
      "Requirement": "Health% < 50"
    },
    {
      "name": "Blink",
      "Key": "F3",
      "Requirement": "!InMeleeRange"
    }
  ]
},
```

Although `Blink` may cause issues with the Navigation. Be advised.

**Comment by Xian55** [comment]
Also added more examples when the `FleeGoal` could be used in the [Readme.md](https://github.com/Xian55/WowClassicGrindBot?tab=readme-ov-file#flee-goal)
