### ISSUE TITLE
Two problems with warlock

### ISSUE THREAD

**Issue by Billdong1997** [Xian55/WowClassicGrindBot#88]
I noticed some problems with warlock
1. The soulstone resurrection doesn't work : when you died, it will release the spirit inmedietely rather than revive using the soulstone
2. Warlock cast summon Felsteel to use a mount. it cannot use mount normally

**Comment by Xian55** [comment]
1. soulstone resurrection need s bit more work at the addon side.
2. Can you elaborate about the issue?

**Comment by Billdong1997** [comment]
Thanks for reply!
For 2: In julianperrott's readme it states that use key "O" to use a mount and it is bound with the marco "/use Chestnut Mare Bridle". I change it to "/cast Summon Felsteed" but the bot cannot use mount

**Comment by Xian55** [comment]
What level are you? 
Currently the mount usage is hardcoded to be at least 40lvl in general except for druids

**Comment by Billdong1997** [comment]
Allright. Yeah that is the problem. Im level 30. You know that all characters can use a mount after level 30 in TBC. :)

**Comment by Xian55** [comment]
i check what could i do about this

**Comment by Xian55** [comment]
Warlock SS will be taken care of another time.
