### ISSUE TITLE
One bug in pathing

### ISSUE THREAD

**Issue by BillDong2021** [Xian55/WowClassicGrindBot#91]
**Describe the bug**
When pathing from one point to another, if the distance between the two point is not too far or too close, the bot will get stuck. 
If the distance is close enough, the bot can run directly to next point; if the distance is too far, the bot will call PPather to find a route which is consist of a series of small route. 
But some small route could be a little far (usually some straight line), and the bot will consider the route too far and create new route. But the distance is not "too far", it cannot create any new route, then the bot cannot move anymore and get stuck.

**Screenshots**
![image](https://user-images.githubusercontent.com/83825966/120582348-ec93a100-c45e-11eb-96c1-f84402ba4acb.png)

**Logs**
If applicable, attach `*.log` files to reduce the investigation time.
[log1.log](https://github.com/Xian55/WowClassicGrindBot/files/6588768/log1.log)

**Comment by Billdong1997** [comment]
The log information is here and it's consistent with my feeling. When it is the last point in the route and distanceToRoute > 200, it will get stuck.  o(╥﹏╥)o . Should I change 200 to a larger number?
![image](https://user-images.githubusercontent.com/83825966/120617112-668e4f00-c48c-11eb-9cc9-048dd928d19f.png)

**Comment by Xian55** [comment]
> The log information is here and it's consistent with my feeling. When it is the last point in the route and distanceToRoute > 200, it will get stuck. o(╥﹏╥)o . Should I change 200 to a larger number?
> ![image](https://user-images.githubusercontent.com/83825966/120617112-668e4f00-c48c-11eb-9cc9-048dd928d19f.png)

No it wont help. The issue lies deeper in the logic it self. The code what you are referring to is quite spaghetti and has some craft in it.

**Comment by Xian55** [comment]
I just found a repro for this issue consistently. Managed to repro with V1 `LocalPathingAPI` and `RemotePathingAPI` and also RemoteV2 and V3. The the character no longer should stuck in place.

Let me know if you have encounter the case

**Comment by BillDong2021** [comment]
I haven't encounter the case for a long time. I think it tends to happen in the situation that the route needed to plan is too long. Recently I just put the charater close to the hunting route so that the pathing algorithm will only plan a very litte path, and I dont encouter the case anymore.
