### ISSUE TITLE
"item broken" cant work

### ISSUE THREAD

**Issue by Billdong1997** [Xian55/WowClassicGrindBot#92]
**Describe the bug**
my item is broken, but the bot cannot read this massage

![image](https://user-images.githubusercontent.com/83825966/120656216-014f5380-c4b6-11eb-9d55-dcc94ac21595.png)

**Comment by Billdong1997** [comment]
Some buff such as DemonArmor has the same problem. i dont have it but the requirement "not Demon Armor"is always red so the bot cant cast it.

**Comment by Xian55** [comment]
> Some buff such as DemonArmor has the same problem. i dont have it but the requirement "not Demon Armor"is always red so the bot cant cast it.

This most likely comes from the localization issue what we talked about in previous issue before.
