### ISSUE TITLE
Wrong number of data frames?

### ISSUE THREAD

**Issue by jjbrunton** [Xian55/WowClassicGrindBot#93]
When running the configuration on TBC classic I get:

I see 77 data frames. Should see 100

Have I messed something up?

**Comment by Xian55** [comment]
First make sure to follow the https://github.com/Xian55/WowClassicGrindBot#5-configuration-process

If the issue still persist, need more info about your system/setup such as
- Windows version
- Resolution / aspect ratio
- installed addon version

**Comment by jjbrunton** [comment]
Resolution was the issue thank you. I was running 1440p but changing to 1080p fixed it!

**Comment by Xian55** [comment]
May i ask what resolution we talking about? 
- Render Scale
- window Rect resolution

Last time when tinkered about the code around the window rect resolution it worked for me 
- 1080p
- 1440p
- 4k

**Comment by jjbrunton** [comment]
1080p resolution with 100% render scale is the only setting that appears to work for me. I have 1440p monitors and running at 1440p with 100% render scale results in incorrect number of frames being read.

**Comment by futureproof123** [comment]
I am having the same issue.

**Comment by Xian55** [comment]
Dear @jjbrunton can you send me a picture of the data frames (when it says `I see 77 data frames. Should see 100`) 
Basically top left hand corner of the screen, at least 500x35 rectangle. it would help me speed up the investigation process.

and the exact resolution when you encounter the issue. 1440p could be very vague.

Thanks, have a good day.
